### ISSUE TITLE
Bot Binary Differ -  3 digits in sequence 

### ISSUE THREAD

**Issue by juliosilva10** [binary-com/binary-bot#1334]
Hello guys. Sorry, for my English.
I'm trying to develop the bot that parses 3 equal digits in sequence.
Example: In the volatility index 100, the last digits 4,4,4 were left in sequence. I wanted to get the bot into the next tick. The problem is that there is a time limit of 1 second for the next market entry.

What happens: 4,4,4,6,4 - the bot enters the market after 1 second, for example taking digit 4 and making the operation lose. I wanted the bot to hit the market immediately after the last 4, taking the number 6 in the example.

I tried to take the time limit, but the bot does not work without it.

![image](https://user-images.githubusercontent.com/43079210/54479829-13bf1300-4800-11e9-8c4f-0aea3e8c5dd1.png)

![image](https://user-images.githubusercontent.com/43079210/54479833-1d487b00-4800-11e9-8819-a60839eb1267.png)

![image](https://user-images.githubusercontent.com/43079210/54479841-2fc2b480-4800-11e9-8bd2-ae20a37a6991.png)

![image](https://user-images.githubusercontent.com/43079210/54479867-731d2300-4800-11e9-96e4-d4cf338425f6.png)

![image](https://user-images.githubusercontent.com/43079210/54479875-862ff300-4800-11e9-8662-ad0996185835.png)

![image](https://user-images.githubusercontent.com/43079210/54479880-8f20c480-4800-11e9-8eef-58a20239eca5.png)

**Comment by romeo1911** [comment]
try something like this, the problem is the time.
![Untitled](https://user-images.githubusercontent.com/44220114/54510282-42afc300-497f-11e9-946b-cfad1e3890da.png)
here have to buy the 6 that is the last tick, but I'm not sure that will do it, maybe will buy the next number after 6, that in your example is another 4.
I do not have time 4 test it because the wait for have 3 digits in sequence takes a long time

**Comment by juliosilva10** [comment]
I left only 2 equal digits, to test faster.

![image](https://user-images.githubusercontent.com/43079210/54551960-d1c3d780-498d-11e9-940c-8e697a958ecb.png)


I followed your suggestion, but the bot did not work.

**Comment by romeo1911** [comment]
ofc not work, the bot work making first block 1 , after block 2 after 3 and 4, end restart at block 1. u cannot set in block 2 dig_0 and aspect that work in block 1 without pass from block 4
[3 in serie.zip](https://github.com/binary-com/binary-bot/files/2981983/3.in.serie.zip)
maybe try set "duration ticks 2"
sometimes happens delay on the data u receive, just an idea: a man get profit using digit match instead of differs

**Comment by juliosilva10** [comment]
Thank you very much! 

Hug.

**Comment by Craziestar36** [comment]
Hello.
Juliosilva.I just had the same idea too,of creating a bot the same way you defined.
But I prefer sequencing the number only upto 2.
Maybe it can give more good results and dont put INITIAL AMOUNT--》WIN AMOUNT,because a rare occurance of 3 digits in sequence can put all your profits to zero.
And by the time you read this comment and if you already have solved the problem then could you please share me the updated version of the bot cause I am new to bot developing and i'm finding it very difficult to create one.
Thank you.

**Comment by juliosilva10** [comment]
Hello. Thanks for the suggestion. I stopped programming. I'm sick of Binary's delay. Good luck!

**Comment by Craziestar36** [comment]
Okay!! but could you give me the xml of your bot,since i wanted to learn a make changes and modifications to it if needed.could you provide me with the last updated version of your bot.PLEASE!!

**Comment by juliosilva10** [comment]
What is your email?

**Comment by Craziestar36** [comment]
craziestar36@gmail.com!!
Here you go.

**Comment by juliosilva10** [comment]
Done!

Good luck!

**Comment by erepspinos** [comment]
> What is your email?

Hi Julio Silva, I believe i got the solution to your problem.  Send the xml file to spinosbinaryoptions@gmail.com   Make the Last Digit Sequence up to 4 and Martingale on loss X 11. Send the files and I will do the rest.

**Comment by juliosilva10** [comment]
> 
> 
> > What is your email?
> 
> Hi Julio Silva, I believe i got the solution to your problem. Send the xml file to [spinosbinaryoptions@gmail.com](mailto:spinosbinaryoptions@gmail.com) Make the Last Digit Sequence up to 4 and Martingale on loss X 11. Send the files and I will do the rest.

The email has been sent.

Good luck
