### ISSUE TITLE
Why my bot it not worked???

### ISSUE THREAD

**Issue by delano24** [binary-com/binary-bot#1370]
Ive tested to higher lower +0.75 and lower.     5 tik..  hmmm

**Comment by delano24** [comment]
@[](url
![Screenshot_20190327_124739](https://user-images.githubusercontent.com/37808777/55051343-a2991e80-508f-11e9-8195-69d3d38f7b6c.jpg)
)

**Comment by delano24** [comment]
![Screenshot_20190327_124756](https://user-images.githubusercontent.com/37808777/55051366-bc3a6600-508f-11e9-8a07-f5f72c4f9f7c.jpg)

**Comment by aaron-binary** [comment]
Hi Bernando,

I’ve had a look at your strategy and it seems to be working correctly. I’ve been able to reproduce the `This contract offers no return error`. It’s happening because of the `Stake` you’re using, it may be too low (e.g. in the case of a `0.35` or `0.7` stake as suggested in your prompt).

You can confirm this by going to our SmartTrader platform and setting the same trade definitions: https://www.binary.com/en/trading.html

Let me know if you have any other questions and we’ll get back to you.

Regards,
Aaron

**Comment by delano24** [comment]
Ok i see... But can you explain this? Just 1 lost and my marti is 3. But the bot is already stop
![Screenshot_20190327_155703](https://user-images.githubusercontent.com/37808777/55059120-201d5880-50a9-11e9-872b-87943e56b86c.jpg)

**Comment by delano24** [comment]
![Screenshot_20190327_160332](https://user-images.githubusercontent.com/37808777/55059434-eef15800-50a9-11e9-82eb-fe94e7635681.jpg)

**Comment by delano24** [comment]
My bot before updated. It works perfectly

**Comment by delano24** [comment]
After update always show unknown and bot will stop
![Screenshot_20190327_160938](https://user-images.githubusercontent.com/37808777/55059809-e0577080-50aa-11e9-8b5a-db21c01be9fb.jpg)
