### ISSUE TITLE
Bot Pause and continue again

### ISSUE THREAD

**Issue by wbruwan** [binary-com/binary-bot#1395]
Hello...

i need to help 

In the 03 loss, keep the bot pause and continue again

**Comment by wilburforce83** [comment]
**This is the easiest way**, though it pauses the whole script, so if you are collecting indicator data, the data will be out of date when the `trade again` function is called after the delay.

So you need to set up a variable, let's call it `lossCount` . Then you will need to create a couple of if functions:

Under ' (4) Get you trade result and trade again` do the following:

IF `ResultIsWin` DO `SET lossCount` to `0` ELSE `CHANGE lossCount` by `1`

Under Binary > Tools > Time place an if function your after the above in the same section

IF `lossCount` >= `3` DO `Trade Again` after x seconds ELSE `Trade Again`.




**The best way;** If you want the analysis of the data to continue, you will will need to create function comparing the differences in epoch stamps:

something like these variables `EpochStamp` , `LossDelay` , `tradingOn` :

Under `Run Once at Start` SET `tradingOn` to `true` , SET `LossDelay` to `60`



Under ' (4) Get you trade result and trade again` do the following:

IF `ResultIsWin` DO `SET lossCount` to `0` ELSE `CHANGE lossCount` by `1`


Under `This Block Runs Every Tick` : 

If `lossCount` >= `3` Set `EpochStamp` to `Seconds Since Epoch` , set `tradingOn` to `false`

If (`Seconds since Epoch` - `EpochStamp`) > `LossDelay` DO SET `tradingOn` to `true`

This second method is a bit of a pain, but it means that your data remains  updated during the pause in trading.

**Comment by wbruwan** [comment]
> **This is the easiest way**, though it pauses the whole script, so if you are collecting indicator data, the data will be out of date when the `trade again` function is called after the delay.
> 
> So you need to set up a variable, let's call it `lossCount` . Then you will need to create a couple of if functions:
> 
> Under ' (4) Get you trade result and trade again` do the following:
> 
> IF `ResultIsWin` DO `SET lossCount` to `0` ELSE `CHANGE lossCount` by `1`
> 
> Under Binary > Tools > Time place an if function your after the above in the same section
> 
> IF `lossCount` >= `3` DO `Trade Again` after x seconds ELSE `Trade Again`.
> 
> **The best way;** If you want the analysis of the data to continue, you will will need to create function comparing the differences in epoch stamps:
> 
> something like these variables `EpochStamp` , `LossDelay` , `tradingOn` :
> 
> Under `Run Once at Start` SET `tradingOn` to `true` , SET `LossDelay` to `60`
> 
> Under ' (4) Get you trade result and trade again` do the following:
> 
> IF `ResultIsWin` DO `SET lossCount` to `0` ELSE `CHANGE lossCount` by `1`
> 
> Under `This Block Runs Every Tick` :
> 
> If `lossCount` >= `3` Set `EpochStamp` to `Seconds Since Epoch` , set `tradingOn` to `false`
> 
> If (`Seconds since Epoch` - `EpochStamp`) > `LossDelay` DO SET `tradingOn` to `true`
> 
> This second method is a bit of a pain, but it means that your data remains updated during the pause in trading.

Hello ...

can i get xml file

thanks..

**Comment by wilburforce83** [comment]
Not really, they go into lots of different sections, so I can't do a collection for import as it will overwrite your  xml. If you upload your xml here, I can take a look?

**Comment by artfriday** [comment]
are you there.. i need to add delay to my script
