### ISSUE TITLE
 Put the trade time to the end of the current candle

### ISSUE THREAD

**Issue by GutierrezGu** [binary-com/binary-bot#1414]
Hello Guys, I need help, I dont know how can i adjust the trade time to the end of the current candle.

For example: Default candle time: 5 Minutes
                    The bot start the trade with 3 Minutes, then the trade time should be 2 Minutes.

Can you help me please ?

**Comment by Zaxushitso** [comment]
Hi; for trading at the end of a candle act like picture attached (600 is time interval (5min) and 570 are the passed seconds after that a trade will be opened) 
you can change 570 up to your strategy and experiments you got
For 1min interval use 60 for 2min interval use 120 and so on, and keep in mind that opening a trade takes about 2 ticks which is equal to 4 seconds

for example if you want to open a trade exactly at the open of a 1min candle interval you should do: remainder of seconds since epoch /60  > 56
to open at the end of a 1min candle interval you should do:
remainder of seconds since epoch /60  > 55  or 54

**Comment by GutierrezGu** [comment]
I am using candle of 5min, Didnt work with me this, 
It does not open the trade with this setting.

![image](https://user-images.githubusercontent.com/49489502/56098364-33685a80-5ed6-11e9-8e55-9f2fbf699f65.png)

**Comment by Zaxushitso** [comment]
I told you Let the bot to open a trade (give it enough time). It takes at least 4 seconds but it's better to give it 5 to 6 seconds
Set the number to 295

**Comment by ZDEGLET** [comment]
Zaxushitso пришлите мне пожалуйста блок со временем 600>570
zdeglet@gmail.com
спасибо

**Comment by GutierrezGu** [comment]
Thank you guys

**Comment by promzy4844** [comment]
> I am using candle of 5min, Didnt work with me this, It does not open the trade with this setting.
> 
> ![image](https://user-images.githubusercontent.com/49489502/56098364-33685a80-5ed6-11e9-8e55-9f2fbf699f65.png)

Please I need this block help me please
