### ISSUE TITLE
Do i need a VPS server for Bots?

### ISSUE THREAD

**Issue by buckman1974** [binary-com/binary-bot#1456]
Do I need a vps server for some bots? Been told I do. Any benefit?

Or is this exactly the same as running from a PC?

Is a VPS needed for long running bot like overnight?

**Comment by binary-ex-machina** [comment]
If you don't have stable internet connection or a good computer that doesn't slow because of the browser on the bot page, it's a good idea have a VPS. Using bots for long run, like 24/7, it's the worst idea on binary options. There is no bot that can work on long run trading without stop. The best is to identify the possible trades on the graph and then start the bot to benefit from it's main purposes, that are doing math faster and more precise then you, analysing thousands of ticks/candles and calculate all the indicators faster then any person can do manually and placing the trades for you, collect the result and trade again.

**Comment by hotmatrixx** [comment]
> 
> 
> Do I need a vps server for some bots? Been told I do. Any benefit?
> 
> Or is this exactly the same as running from a PC?
> 
> Is a VPS needed for long running bot like overnight?

I Run my bots for around 24h at a time, on a really underpowered laptop that just chills out next to me.
Seems fine to me....

**Comment by buckman1974** [comment]
> > Do I need a vps server for some bots? Been told I do. Any benefit?
> > Or is this exactly the same as running from a PC?
> > Is a VPS needed for long running bot like overnight?
> 
> I Run my bots for around 24h at a time, on a really underpowered laptop that just chills out next to me.
> Seems fine to me....

@hotmatrixx so you run bots fine on a simple laptop on a standard normal internet connection?

Do you make money this way? with the bots like this?
