### ISSUE TITLE
Please help me create a bot using the ADX indicator just like the binary floor parameter

### ISSUE THREAD

**Issue by giaupn** [binary-com/binary-bot#1457]
Please help me create a bot using the ADX indicator just like the binary floor parameter
![image](https://user-images.githubusercontent.com/45723837/56855841-d14d3200-6978-11e9-84b8-1c68ecfe7958.png)

**Comment by giaupn** [comment]
@Fruitfella

**Comment by giaupn** [comment]
@binary-ex-machina

**Comment by giaupn** [comment]
@binary-ex-machina

**Comment by binary-ex-machina** [comment]
it's not possible to create ADX indicator with the blocks

**Comment by giaupn** [comment]
So do you have any ideas related, please

**Comment by hotmatrixx** [comment]
> 
> 
> So do you have any ideas related, please

These bots cannot draw trendlines themselves, and only support a couple of types of indicator natively.
you CAN display the ADX trendlines, here:

![image](https://user-images.githubusercontent.com/49715381/57007358-1ce33280-6c3c-11e9-86e8-4fc96071b01f.png)


but the bot cannot read/calculate off them.
You would have to make the bot calculate them, then base your bot's actions upon that information, and they are quite a complex series of calculations to get the ADX indicators.

I'm not really interested in coding them in for you, but I will give you the calculations that you need program the bot to make, every tick;

they go like this

>  The Formulas for the Average Directional Index
(ADX) Indicator are

The ADX requires a sequence of calculations due to the multiple lines in the indicator.

+DI=(Smoothed +DMATR )×100-DI=(Smoothed -DMATR )×100DX=(∣+DI−-DI∣∣+DI+-DI∣)×100ADX=(Prior ADX×13)+Current ADX14where:+DM (Directional Movement)=Current High−Previous High-DM=Previous Low−Current LowSmoothed +/-DM=∑t=114DM−((∑t=114DM)÷14)+Current DMATR=Average True Range*\begin{aligned} &\text{+DI} = \left ( \frac{ \text{Smoothed +DM} }{ \text{ATR } } \right ) \times 100 \\ &\text{-DI} = \left ( \frac{ \text{Smoothed -DM} }{ \text{ATR } } \right ) \times 100 \\ &\text{DX} = \left ( \frac{ \mid \text{+DI} - \text{-DI} \mid }{ \mid \text{+DI} + \text{-DI} \mid } \right ) \times 100 \\ &\text{ADX} = \frac{ ( \text{Prior ADX} \times 13 ) + \text{Current ADX} }{ 14 } \\ &\textbf{where:}\\ &\text{+DM (Directional Movement)} = \text{Current High} - \text{Previous High} \\ &\text{-DM} = \text{Previous Low} - \text{Current Low} \\ &\text{Smoothed +/-DM} = \textstyle{ \sum_{t=1}^{14} \text{DM} - ( ( \sum_{t=1}^{14} \text{DM} ) \div 14 ) + \text{Current DM} } \\ &\text{ATR} = \text{Average True Range*} \\ \end{aligned}​+DI=(ATR 
Smoothed +DM​)×100-DI=(ATR 
Smoothed -DM​)×100DX=(∣+DI+-DI∣
∣+DI−-DI∣​)×100ADX=14

(Prior ADX×13)+Current ADX​where:+DM (Directional Movement)=Current High−Previous High-DM=Previous Low−Current LowSmoothed +/-DM=∑t=114​DM−((∑t=114​DM)÷14)+Current DMATR=Average True Range*​﻿

*Average True Range
Calculating the Average Directional Movement Index (ADX)

    Calculate +DM, -DM, and True Range (TR) for each period. 14 periods are typically used.
    +DM = Current High - Previous High.
    -DM = Previous Low - Current Low.
    Use +DM when Current High - Previous High > Previous Low - Current Low. Use -DM when Previous Low - Current Low > Current High - Previous High.
    TR is the greater of the Current High - Current Low, Current High - Previous Close, or Current Low - Previous Close.
    Smooth the 14-period averages of +DM, -DM, and TR. The TR formula is below. Insert the -DM and +DM values to calculate the smoothed averages of those.
    First 14TR = Sum of first 14 TR readings.
    Next 14TR value = First 14TR - (Prior 14TR/14) + Current TR
    Next, divide the smoothed +DM value by the smoothed TR value to get +DI. Multiply by 100.
    Divide the smoothed -DM value by the smoothed TR value to get-DI. Multiply by 100.
    The Directional Movement Index (DX) is +DI minus -DI, divided by the sum of +DI and -DI (all absolute values). Multiply by 100.
    To get the ADX, continue to calculate DX values for at least 14 periods. Then, smoothe the results to get ADX

    First ADX = sum 14 periods of DX / 14
    After that, ADX = ((Prior ADX * 13) + Current DX) /14

> 
https://www.investopedia.com/terms/a/adx.asp

**Comment by giaupn** [comment]
@binary-ex-machina
Based on the above information, please help me
