### ISSUE TITLE
plz add martingale start after 2 loss and set max loss 8 

### ISSUE THREAD

**Issue by ashrafulcg** [binary-com/binary-bot#1475]
[bullbear8.zip](https://github.com/binary-com/binary-bot/files/3144582/bullbear8.zip)

**Comment by Rikaz1985** [comment]
I also wont to like this pls help

**Comment by romeo1911** [comment]
for test i set bear >bull on 3 ticks, for make it faster, but even like that i cannot get 8 wrong trades. i assumed that after 8 losses restart from 0. 
[bullbear82.txt](https://github.com/binary-com/binary-bot/files/3155569/bullbear82.txt)
![Untitled](https://user-images.githubusercontent.com/44220114/57350474-65dd3e80-7188-11e9-9a4c-2bf28665cf19.png)

**Comment by Rikaz1985** [comment]
Hi..
I ll try on this & i ll give you a feedback
Thank You Very Much..

**Comment by Rikaz1985** [comment]
Can You Send me a XML file Please..

**Comment by Rikaz1985** [comment]
Dear Sir / Madam,

we are dedicated company in fulfilling the customers need
in all kinds of Rubber Stamps including Embossing stamps
using the latest technology since 2004.

Why worry, when you are in a hurry.
if Rubber Stamp is your need, we are there to serve you Online.
let it be Pre-Inked stamps, Self-Inked Stamps, Polymer Stamps,
Dater Stamps, Received Stamps, Paid Stamps & Embossing Seal.
you name it and we will deliver it to your door step. for
more detail please contact.

A.R. M. Rikaz
Business Development Manager
Hot Line: 0778000222 / 0711521626
Email: realstamp@gmail.com
[image: IMG-20160202-WA0006_lowres.jpg]











*Best Regards,*
*A. R. M. Rikaz*
*Business Development Manager*

**Comment by Simo-912** [comment]
Guys how Can I set two martingle after one lose on binary bot?
