### ISSUE TITLE
just a request

### ISSUE THREAD

**Issue by romeo1911** [binary-com/binary-bot#1495]
hi @aaron-binary 
my case is this :
block1
 set var to "   "
block 2
 if var = "  "
  do set var to prompt from text "something"

at this point, on the prompt, if i click ok and i leave empty, the prompt comes out again
if i click cancel, or if i just change tab in the browser
the prompt disappear because the variable change from "   " to null
my question is: 
can u make the chart working even there is a prompt and/or not make the prompt disappear/change the variable, if i change tab?

**Comment by hotmatrixx** [comment]
> 
> 
> hi @aaron-binary
> my case is this :
> block1
> set var to " "
> block 2
> if var = " "
> do set var to prompt from text "something"
> 
> at this point, on the prompt, if i click ok and i leave empty, the prompt comes out again
> if i click cancel, or if i just change tab in the browser
> the prompt disappear and the variable change from " " to null
> my question is:
> can u make the chart working even there is a prompt and/or not make the prompt disappear if i change tab?

Hello, friend.
I'm trying to understand what' you're issue is, but it doesn't quite make sense to me. Is there any chance you could take a screenshot, and just crop the bit you're asking about?

OH I think I understand, You have a "prompt for Input", you're changing tabs to get the info needed for that prompt, and it cancels out on you.

Can't you just run that tab in a new browser window and run it side-by-side?
I love my dual screens.

Otherwise, there is a Firefox Addon called "Always On Top" that lets you pin a FF window to always show over other windows, even if they are the active window. it's great for putting a youtube clip on top of other work you're doing, or maybe an indicator window as an overloay over your bot, if that helps.

**Comment by romeo1911** [comment]
> I'm trying to understand what' you're issue is, but it doesn't quite make sense to me. Is there any chance you could take a screenshot, and just crop the bit you're asking about?

in effects is just a request :)

thanks, i will give a look for that addon, 
btw i think is ok if i click on cancel, that variable change and gimme the ability to stop and restart the bot,
but my point is that i do not think is "normal" that the bot can change the variable if i change tab in the browser.
else maybe they can create a block "stop" to stop the bot.

i "solved" changing in block 2 
if var = " " or null
