### ISSUE TITLE
Help turn this to Bot

### ISSUE THREAD

**Issue by nobleb2007** [binary-com/binary-bot#1517]
DIGIT DIFFER
If the LDP =LAST DIGIT

predict the number after 2tick.

I have been using manually for some days now. I hope it can work with both too.
@aaron-binary 
@romeo1911
@hotmatrixx
@sinung21
Please please please.

**Comment by navneetsinh** [comment]
> DIGIT DIFFER
> If the LDP =LAST DIGIT
> 
> predict the number after 2tick.
> 
> I have been using manually for some days now. I hope it can work with both too.
> @aaron-binary
> @romeo1911
> @hotmatrixx
> @sinung21
> Please please please.

what is your required trade duration ?

**Comment by nobleb2007** [comment]
@navneetsinh trade duration should be 2ticks

**Comment by nobleb2007** [comment]
Please, help turn it to bot. Please please

**Comment by nobleb2007** [comment]
The masters in the house help turn this to bot please

**Comment by nobleb2007** [comment]
Help out

**Comment by binary-ex-machina** [comment]
You can't purchase right after you set the digit differ, since it takes 1 tick to make this, so you will always enter in the next tick. The image below show how to do this.
![image](https://user-images.githubusercontent.com/34610787/58363672-770f9600-7e7e-11e9-8b53-cfb147c20c2c.png)


the best approach to buy on the tick the last digit appear, is to play with the prediction fixed. This way you will start to trade in the next tick and will not have a gap

![image](https://user-images.githubusercontent.com/34610787/58363688-ab835200-7e7e-11e9-845f-277e5ffd8750.png)

**Comment by korboat159** [comment]
the next trade will be executed once digit is replaced byanother digit as a  one for the next prediction?
