### ISSUE TITLE
Help Need !!!

### ISSUE THREAD

**Issue by ArunGowthamm** [binary-com/binary-bot#1522]
hello guys,,
           i try to run 3 bot at the  same time with same condition withe same expiry time...Every things works fine but some times the exit spot value of the 3 bots were differ ...i don' t know why this happen and this happens many times ...

does anyone know how to solve or avoid this type of error..

Here i attached 3 bots results...

![Error 1](https://user-images.githubusercontent.com/42668529/57947214-ee33b000-78fb-11e9-9343-75974071391a.png)
![Error 2](https://user-images.githubusercontent.com/42668529/57947220-f1c73700-78fb-11e9-8b46-4548eb1c0d92.png)
![Error 3](https://user-images.githubusercontent.com/42668529/57947223-f5f35480-78fb-11e9-9dbf-adceac2ad261.png)

**Comment by arpan2121** [comment]
can you tell what kind of bot is it?

**Comment by ArunGowthamm** [comment]
Strategy Does't Matter,,,As you can see
1.the entry spot of 3 bots were same 
2.expiry time of 3 bots were same 
3. All of them are in vol 100 market

then how its happen . Different Exit spot..is it a bug ???

**Comment by arpan2121** [comment]
Even if you have the tick list you can not match the entire exit point because it depends on the fluctuation of the market. I have an even and odd, but the strategy goes when the digit matches and goes 22222 it will buy even. However, still, it not guaranteed that the entry point is going to be the same as the entry point or even as we needed therefore to increase the changes you use random tick integrator from 1 tick to 5. That increase more changes. It's not a bug, I just tried to explain to use the concept behind with an example of one of my bots and you can predict the last spot with a win the of 90% with the tick list that I use it's really simple ti set up.

**Comment by aaron-binary** [comment]
Hey @ArunGowthamm 

Could you send the references for these transactions to binarybot@binary.com?

Regards,
Aaron

**Comment by ArunGowthamm** [comment]
@aaron-binary 
Bro i lost that screenshots ....sure i will take some other screenshots and will mail to binarybot@binary.com.because it happens many times for me.  

Thanks for your support.

**Comment by ArunGowthamm** [comment]
@arpan2121 

yes bro i agree that markets have high fluctuation..as you refer the above screenshots..all the 3 bots enter the market at the same entry spot..with 2 mins expiry time..2 of the exit the market at same exit spot ..but one bot exit with different exit spot...

My argument is that the bot which has different exit bot  will have the
1. 2 mins and 1 tick expiry time 
OR
2. 1 mins 59 seconds expiry Time..

which cause it happen???

**Comment by binary-ex-machina** [comment]
you can't avoid this. Sometimes one of the bots will end later and this can happen because several factors, like internet connection, instability on the internet connection, computer processor, memory, binary servers...
