### ISSUE TITLE
What are your most consistent profitable bots?

### ISSUE THREAD

**Issue by buckman1974** [binary-com/binary-bot#1561]
What are your most consistent profitable bots?

I now seem to have folders of 100's of bots that i've built and some I have downloaded and tried, and forget which are good/bad for daily use

Do you have any certain bots that stand out above others?

Which are you most consistent bots that you use the most or daily for a small (or large) profit?

Are there any out there that work over long periods of time, as the 'better' bots to use to make a profit?

Looking forward to hearing how you use them, and if needs, you can upload them here.
I will do the same, once I've finished going through my folders!

**Comment by ZDEGLET** [comment]
ЧТО ТО ТИШИНА. НИ У КОГО НИЧЕГО НЕТУ ЗА 11 ЛЕТ РАБОТЫ САЙТА:(
А ЕСЛИ ЕСТЬ ТО НИКТО НЕ ВЫЛОЖИТ ХОРОШЕГО РОБОТА.

**Comment by Hooponopono** [comment]
i know that James Harris Simons made a good bot, google him

**Comment by buckman1974** [comment]
> i know that James Harris Simons made a good bot, google him

He wrote .XML Binary bots?

**Comment by binary-ex-machina** [comment]
there is a myth that almost everyone that go into bots believe at first: running a bot 24/7 without the risk of blowing accounts. It's impossible. No one that trade binary options for living uses bot like that. If you take any bot Rise/Fall right now and hit play, the chance of winning will be 50%. No matter the strategy, since you will use ticks or 1min duration (most of the bots are in this duration range), the period of analysis is zero, so you can enter on a good or bad market moment.

In case you do some analysis before playing the bot, trying to avoid sideways or trend, depending on the bot strategy, you have a better chance. 

Let's say for example you have a bot that does CALL only, every 5 ticks and analysing the chart you see that the market is downtrend. The chances of winning are lower then 50% right? but if it's an uptrend, the chances are higher then 50%. 

A bot that analysis ticks with a lot of filters, will take longer to place trades and will be more accurate. Playing then 24/7, will reduce your winning chance to 50% again.

Those who claim that have bots with 70% win rate, that never get more then 5 martingale steps, that can run 24/7 and never blow a $100 account, are scammers. Any strategy will blow the account, if you play without stop.
