### ISSUE TITLE
How to get timestamps

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1564]
how to get spending time on running bot ?
bot start - **set** bot start time
bot stop - **set** bot stop time
**notify** bot taken time = bot stop time - bot start time

**Comment by hotmatrixx** [comment]
What I do, is I use the "seconds Since Epoch". I record it at the 'run once' block as 'StartTime' or something, then if I want to know the time in seconds I've been running for later (eg when the bot is ready to stop) it's [Seconds Since Epoch] - [StartTime]

I use it to see what my earnings per hour look like in a notification, but that should 'solve' your issue, too :)

**Comment by navneetsinh** [comment]
> What I do, is I use the "seconds Since Epoch". I record it at the 'run once' block as 'StartTime' or something, then if I want to know the time in seconds I've been running for later (eg when the bot is ready to stop) it's [Seconds Since Epoch] - [StartTime]
> 
> I use it to see what my earnings per hour look like in a notification, but that should 'solve' your issue, too :)

thanks to trying to understand me, I'll check it and also revert you thanks again

**Comment by navneetsinh** [comment]
> What I do, is I use the "seconds Since Epoch". I record it at the 'run once' block as 'StartTime' or something, then if I want to know the time in seconds I've been running for later (eg when the bot is ready to stop) it's [Seconds Since Epoch] - [StartTime]
> 
> I use it to see what my earnings per hour look like in a notification, but that should 'solve' your issue, too :)

hi, @hotmatrixx I checked your idea, it's working, but here is a query and it's that how to get that result in HH:MM:SS ????

**Comment by hotmatrixx** [comment]
yeah it's possible but kind of tricky.
a 'cheat' is to divide it by 3600.
60 seconds in a minute, x 60 minutes in an hour = 60x60=3600. Divide it by that. 
you dont get H:M:S, but you get hours, percent of an hour etc. To get it accurate, you'd have to divide it by 3600, then take the remainder and convert that from a percentage to a number of minutes. so If you had your total time as 10,000 then 10000/3600= 2.7777777777777777
so you could either extract the decimal part and just multiply that by 60. that would give you minutes.
or you could round down; ROUND DOWN [10000/3600]= 2
then use this 
![image](https://user-images.githubusercontent.com/49715381/58942530-0ba8bb00-87d2-11e9-9159-edb11308996d.png)
 to get the 'true' remainder, and divide that result by 60 to get minutes.

I havent done it because 
1. im lazy :)
2. i think you are capable of it, and will learn better by doing it than having it spoon fed to you.

Personally, I just use the 2.7 number as I tend to run my stuff for hours at a time, and I just know that it's around 2h 40 mins from seeing it a lot.

**Comment by navneetsinh** [comment]
> yeah it's possible but kind of tricky.
> a 'cheat' is to divide it by 3600.
> 60 seconds in a minute, x 60 minutes in an hour = 60x60=3600. Divide it by that.
> you dont get H:M:S, but you get hours, percent of an hour etc. To get it accurate, you'd have to divide it by 3600, then take the remainder and convert that from a percentage to a number of minutes. so If you had your total time as 10,000 then 10000/3600= 2.7777777777777777
> so you could either extract the decimal part and just multiply that by 60. that would give you minutes.
> or you could round down; ROUND DOWN [10000/3600]= 2
> then use this
> ![image](https://user-images.githubusercontent.com/49715381/58942530-0ba8bb00-87d2-11e9-9159-edb11308996d.png)
> to get the 'true' remainder, and divide that result by 60 to get minutes.
> 
> I havent done it because
> 
> 1. im lazy :)
> 2. i think you are capable of it, and will learn better by doing it than having it spoon fed to you.
> 
> Personally, I just use the 2.7 number as I tend to run my stuff for hours at a time, and I just know that it's around 2h 40 mins from seeing it a lot.

hey, @hotmatrixx thanks for a good suggestion, 
I did it,
![Opera Snapshot_2019-06-05_174720_bot binary com](https://user-images.githubusercontent.com/42480287/58955643-240cdb80-87ba-11e9-8449-288730a319be.png)

**Comment by politecruise** [comment]
> > yeah it's possible but kind of tricky.
> > a 'cheat' is to divide it by 3600.
> > 60 seconds in a minute, x 60 minutes in an hour = 60x60=3600. Divide it by that.
> > you dont get H:M:S, but you get hours, percent of an hour etc. To get it accurate, you'd have to divide it by 3600, then take the remainder and convert that from a percentage to a number of minutes. so If you had your total time as 10,000 then 10000/3600= 2.7777777777777777
> > so you could either extract the decimal part and just multiply that by 60. that would give you minutes.
> > or you could round down; ROUND DOWN [10000/3600]= 2
> > then use this
> > ![image](https://user-images.githubusercontent.com/49715381/58942530-0ba8bb00-87d2-11e9-9159-edb11308996d.png)
> > to get the 'true' remainder, and divide that result by 60 to get minutes.
> > I havent done it because
> > 
> > 1. im lazy :)
> > 2. i think you are capable of it, and will learn better by doing it than having it spoon fed to you.
> > 
> > Personally, I just use the 2.7 number as I tend to run my stuff for hours at a time, and I just know that it's around 2h 40 mins from seeing it a lot.
> 
> hey, @hotmatrixx thanks for a good suggestion,
> I did it,
> ![Opera Snapshot_2019-06-05_174720_bot binary com](https://user-images.githubusercontent.com/42480287/58955643-240cdb80-87ba-11e9-8449-288730a319be.png)

please can you help with a screenshot of the block that got this running.

**Comment by navneetsinh** [comment]
sure @politecruise ,
check,
![Opera Snapshot_2019-06-18_214822_bot binary com](https://user-images.githubusercontent.com/42480287/59701299-f476be00-9212-11e9-9bf2-e57aff060575.png)

If anyone looks any type of correction required, or have any improvement for these blocks, please let me know and give me suggestion for how to do it,

**Comment by hotmatrixx** [comment]
is this easier?
![image](https://user-images.githubusercontent.com/49715381/60718294-63c11180-9f78-11e9-80d3-d05249aff07c.png)

**Comment by hotmatrixx** [comment]
as a free bonus, this is MY setup. the nice one i just made for you is actually pretier, maybe I should format this one liek that one... nah.

![image](https://user-images.githubusercontent.com/49715381/60718572-1d1fe700-9f79-11e9-9fae-b0997c054b52.png)
