### ISSUE TITLE
Up/down equals (pute, calle) error Unknown contract proposal

### ISSUE THREAD

**Issue by nextnaro** [binary-com/binary-bot#1565]
Up/down equals (pute, calle) error Unknown contract proposal.
but same script Up/down Rise, FALL dont have error.
Bug?
![image](https://user-images.githubusercontent.com/31925501/58928981-741e7a80-8787-11e9-8c1c-6d3c05117459.png)

![image](https://user-images.githubusercontent.com/31925501/58928990-7e407900-8787-11e9-8d7b-7e30e52d3953.png)

**Comment by anton-binary** [comment]
Hey @nextnaro,

Could you please share your strategy here or email it to binarybot@binary.com?
We'll investigate the issue.

Thanks,
Anton.

**Comment by ceakuk** [comment]
Dear trader,
I can do it within 1 hour for 5$
I see so many issues that i can do in a few minutes. However it would take me forever to help everybody. So i'll charge 5$  for my time. if the strategy is sound then 5$ is nothing compared to your potential profit.

**Comment by binary-ex-machina** [comment]
@nextnaro this error appears from time to time and it's a bug. Probably because of connection from your computer with the binary server

Never pay any amount for people asking money here. This is a repository to share knowledge and help others, not a market place for desperate people.

**Comment by ceakuk** [comment]
@binary-ex-machina
calling me  desparate is very offensive. i used to respect you at the begining untill i realized all your bots are a complete fail. selling fake bots that you know in the long run will fail is desparate.

before i learnt to code i would beg people to code. now that im good at it, and i see many ask for help go unanswered, why not help and get a little compensation for my effort. if your many bots were working you would give/sell instead of wasting time with new issues. 

your strategies don't work. thats why you are still here trying new ones. but you don't tell the people buying from you that they don't work. you are a fraud. making 1$ and risking 100$ may appear to work but just 1 fail will wipe you out. Have manners

**Comment by binary-ex-machina** [comment]
@ceakuk 

> Dear trader,
I can do it within 1 hour for 5$
I see so many issues that i can do in a few minutes. However it would take me forever to help everybody. So i'll charge 5$ for my time. if the strategy is sound then 5$ is nothing compared to your potential profit.

Trying to make money in a github repository is an attitude of a desperate guy. Here we share knowledge and help each one, not ask for money. Go to a marketplace and sell your services. Not here. Be more useful for the world and help others, don't charge them.
