### ISSUE TITLE
DEAR CODERS ,COULD YOU PLEASE ADD TWO BARRIERS TO TJIS BOT ,THANKS

### ISSUE THREAD

**Issue by daredude26** [binary-com/binary-bot#1579]
[converted (1).zip](https://github.com/binary-com/binary-bot/files/3278198/converted.1.zip)
)

**Comment by daredude26** [comment]
once barrier added kindly post the zip file please, thanks a lot

**Comment by navneetsinh** [comment]
![Opera Snapshot_2019-06-11_123650_bot binary com](https://user-images.githubusercontent.com/42480287/59250708-a75c8000-8c45-11e9-9e7e-3ac0568d173c.png)
you can put some blocks like that.

**Comment by daredude26** [comment]
> ![Opera Snapshot_2019-06-11_123650_bot binary com](https://user-images.githubusercontent.com/42480287/59250708-a75c8000-8c45-11e9-9e7e-3ac0568d173c.png)
> you can put some blocks like that.

thanks

**Comment by daredude26** [comment]
[converted (1).zip](https://github.com/binary-com/binary-bot/files/3278153/converted.1.zip)
it seems to be nice bot,kindly add two barriers and post the edited zip here please ,thanks in advance

**Comment by daredude26** [comment]
> > ![Opera Snapshot_2019-06-11_123650_bot binary com](https://user-images.githubusercontent.com/42480287/59250708-a75c8000-8c45-11e9-9e7e-3ac0568d173c.png)
> > you can put some blocks like that.
> 
> thanks

navneetsinh ,i added full bot,could you  please add two barriers please thanks

**Comment by navneetsinh** [comment]
> [converted (1).zip](https://github.com/binary-com/binary-bot/files/3278153/converted.1.zip)
> it seems to be nice bot,kindly add two barriers and post the edited zip here please ,thanks in advance

this is rise fall bot 
you no need for barrier for that
![Opera Snapshot_2019-06-12_172829_bot binary com](https://user-images.githubusercontent.com/42480287/59349612-b15eab80-8d37-11e9-99d9-802119a74bd7.png)

**Comment by daredude26** [comment]
Iam going to try higher/lower

**Comment by daredude26** [comment]
When I change to higher lower,there is only one Barrier,so please add two barriers, thanks

**Comment by navneetsinh** [comment]
what barrier value do you want 
give +/- barrier value

**Comment by daredude26** [comment]
I want both barriers

**Comment by daredude26** [comment]
Please add + and - barriers

**Comment by daredude26** [comment]
**
![Screenshot_2019-06-12-07-28-09-411_com android chrome](https://user-images.githubusercontent.com/32339686/59351498-315b2600-8ce4-11e9-83ba-3e4b62752bda.png)
**

**Comment by daredude26** [comment]
Navneetsinh I want barriers like this

**Comment by daredude26** [comment]
@aaron-binary ,examachina,please help me,add two barriers to this hot to trade higher ,lower and post the sip file here thanks

**Comment by binary-ex-machina** [comment]
@daredude26 just add the blocks like the image you sent last

**Comment by daredude26** [comment]
Examachina I don't know how to add the blocks ,no experience in code,could you please add and post zip file here, thanks

**Comment by binary-ex-machina** [comment]
Invest some time learning how to use the mouse, click and drag and copying the image i sent. I can guarantee that this is the easiest part of making the strategy and anyone can do it, if they want to

**Comment by Hooponopono** [comment]
IBM field service memo 1989

If a mouse fails to operate or should it perform erratically, it may need a ball replacement. Mouse balls are now available as FRU (Field Replacement Units). Because of the delicate nature of this procedure, replacement of mouse balls should only be attempted by properly trained personnel.

Before proceeding, determine the type of mouse balls by examining the underside of the mouse. Domestic balls will be larger and harder than foreign balls. Ball removal procedures differ depending upon the manufacturer of the mouse. Foreign balls can be replaced using the pop off method. Domestic balls are replaced by using the twist off method. Mouse balls are not usually static sensitive. However, excessive handling can result in sudden discharge. Upon completion of ball replacement, the mouse may be used immediately.

It is recommended that each person have a pair of spare balls for maintaining optimum customer satisfaction. Any customer missing his balls should contact the local personnel in charge of removing and replacing these necessary items.

Please keep in mind that a customer without properly working balls is an unhappy customer.

**Comment by daredude26** [comment]
> Invest some time learning how to use the mouse, click and drag and copying the image i sent. I can guarantee that this is the easiest part of making the strategy and anyone can do it, if they want to
binary ex-machina, i have tried so many ways to add multiple barrier,i tied to drag the barrier from one bot to another bot,still i dont find the ways

**Comment by daredude26** [comment]
> what barrier value do you want
> give +/- barrier value

navneetsinh can you add +and-barriers to the bot and post zipfile here,

**Comment by navneetsinh** [comment]
> > what barrier value do you want
> > give +/- barrier value
> 
> navneetsinh can you add +and-barriers to the bot and post zipfile here,

![Opera Snapshot_2019-06-14_140254_bot binary com](https://user-images.githubusercontent.com/42480287/59495563-2dc6cb00-8ead-11e9-8e0c-6f454c082649.png)

I just set your bot, for higher lower(not tested) now what barrier you want you can set by own

**Comment by daredude26** [comment]
Thanks navneetsinh,I request you to post zip file please
