### ISSUE TITLE
get the highest/lowest point of a continuous rising/falling tick list

### ISSUE THREAD

**Issue by thainano** [binary-com/binary-bot#1601]
if for example
list 1 : tick1>t2>t3>t4<t5
list 2 : tick1>t2>t3>t4>t5<t6
how can i make a bot that returns the value of tick 4 (if use on list 1)
or if i use on list 2 returns the value of tick 5

**Comment by binary-ex-machina** [comment]
you can use the get function with the number of the tick you want to get, from end. It will depend on how you build that list, in case the most recent ticks were the last ones, you should use "#from end", otherwise use "#"

![image](https://user-images.githubusercontent.com/34610787/59556972-d48d9300-8fa3-11e9-99d1-2bbf025c33d0.png)
