### ISSUE TITLE
 bot that opens operation with expiration until the end of the candle

### ISSUE THREAD

**Issue by developmentjava** [binary-com/binary-bot#1664]
I need an expired bot until the end of the candle.
Example: 5-minute candle date 09:50
bot opens operation 09:47 and closes at 09:50 or bot opens operation 09:40 and closes at 09:45

**Comment by binary-ex-machina** [comment]
you can do like this below. This is a complex procedure, you need to put the analysis inside the While Loop, inside the Run After 1 Second. I put a simple example: Last Tick > SMA10, it will calculate the duration. In case the duration (you remove 4 seconds from the duration in order to finish the trade and start the next one in case it's sequential). The duration needs to be above the minimum duration in seconds (15s), if not if will keep in the loop and ignore the signal. Otherwise, it will break out the loop and define the trade.

This will work only in with indexes, since other markets will not accept seconds.

![image](https://user-images.githubusercontent.com/34610787/60689251-bc69af00-9e91-11e9-96aa-f20232c7ed07.png)

**Comment by developmentjava** [comment]
Yes thanks
