### ISSUE TITLE
What is it ''remainder of second epoch'' ,In SMA ?

### ISSUE THREAD

**Issue by Herotaiko** [binary-com/binary-bot#1701]
![Capture11111](https://user-images.githubusercontent.com/51996252/61032219-38f91200-a3eb-11e9-8c2b-fb20b4fb9a1a.PNG)
What is it set for? And if changing the settings, what will happen?

**Comment by binary-ex-machina** [comment]
(Remainer of Seconds since epoch / 60) / 57

This to enter on the 1st tick of a 1min candle.

**Comment by Herotaiko** [comment]
@binary-ex-machina Thank you for the answer.

If 1st tick of a 5min candle?

Please suggest settings if it takes 5 minutes.

**Comment by binary-ex-machina** [comment]
check this idea

Candle Time: 60 seconds (1min)

(Remainer of **Seconds since epoch** % **Candle Time**) > (**Candle Time**  - 3 Seconds)
this will be:
(Remainer of Seconds since epoch % 60) > 57 (in this case it will buy the contract at 58th second of a 1min candle

Now if you want 5min candle

Candle Time: 300 seconds (5min)

(Remainer of **Seconds since epoch** % **Candle Time**) > (**Candle Time**  - 3 Seconds)
this will be:
(Remainer of Seconds since epoch % 300) > 297 (in this case it will buy the contract at 298th second of a 5min candle

**Comment by Herotaiko** [comment]
@binary-ex-machina

Thank you for the advice and knowledge that is available at all times.
