### ISSUE TITLE
Turn this into an .XML bot?

### ISSUE THREAD

**Issue by buckman1974** [binary-com/binary-bot#1717]
I see this guy using this Firefox bot daily on Youtube, and even though the figures maybe fake, he is consistent with making videos!

He 'claims' that it never gets a 2nd loss due to programming and analysis?

Could this be done the same (if it works and is true), within an XML bot?
https://youtu.be/mzFCFIeAmZs

**Comment by binary-ex-machina** [comment]
@buckman1974 a lot of problems here. He claims that never gets 2nd loss, this is 100% fake. Impossible to have a strategy that never get sequential losses, he is lying strong here. Second thing is that he hides the reference number. Probably because he is trading with demo account and no one can proof that, so he wins with the doubt. If you check his account balance form 4 years ago is almost the same, always the same music and probably same video on some publications. Strategies that are played with iMacros normally doesn't suffer with the delay we find on the bot, so it will work, but not like he claims it works.

**Comment by buckman1974** [comment]
@binary-ex-machina yes thought as much, but he posts soo many videos i just wanted to see what his strategy was that he #thinks# he has to not get a second loss, and just use that small part, to program into an .xml bot

**Comment by binary-ex-machina** [comment]
What I saw in the video you sent is that he send the trades, one after another, without any analysis with 3 ticks duration, CALL - PUT - CALL - PUT and so on.

**Comment by buckman1974** [comment]
> What I saw in the video you sent is that he send the trades, one after another, without any analysis with 3 ticks duration, CALL - PUT - CALL - PUT and so on.

Yes he probably does @binary-ex-machina , So its a luck of the draw then? and its just luck that the 'video' he takes and uploads never has a 2nd loss, and nothing to do with any strategy or programming?

**Comment by binary-ex-machina** [comment]
When someone uses words like "never", "forever" or any absolutist word on trading, he is probably wrong. He can show only the best parts, as well record multiple times on a good winning streak. 

If you analyze his videos, there is no analysis, since iMacros can't analyze any past ticks/candles, just what appears on the screen, so it's pure manipulation on the videos.

**Comment by buckman1974** [comment]
I did always wonder why certain videos grayed out the 'transaction reference'?

Is this because we could check up on a certain transaction, to see if it won or if it was real/virtual account?

**Comment by binary-ex-machina** [comment]
@buckman1974 exactly. Reference ending with 8 are from demo accounts

**Comment by Hooponopono** [comment]
> @buckman1974 a lot of problems here. He claims that never gets 2nd loss, this is 100% fake. Impossible to have a strategy that never get sequential losses, he is lying strong here. Second thing is that he hides the reference number. Probably because he is trading with demo account and no one can proof that, so he wins with the doubt. If you check his account balance form 4 years ago is almost the same, always the same music and probably same video on some publications. Strategies that are played with iMacros normally doesn't suffer with the delay we find on the bot, so it will work, but not like he claims it works.
