### ISSUE TITLE
Bot not couting the candles properly

### ISSUE THREAD

**Issue by AFPEMI** [binary-com/binary-bot#1723]
Good evening,
Can you please shine some light on the attached script?
Its not properly counting the candles
Sometimes it counts green candles as red candles, and vise-versa.
Other times it doesn't count the first candle after a change in colors.
It also sometimes counts one candle as three.

[Candles Bollinger.zip](https://github.com/binary-com/binary-bot/files/3399342/Candles.Bollinger.zip)

Thank you

**Comment by Hooponopono** [comment]
the block reminder of etc >57 is used for send a buy sell contract 3 seconds before the exiry of the candle hoping to get the order in the same time the candle is new, if u calculate in that time more or less u will get the prev values because will be only 1 tick in that moment. use it when u buy or sell not for calculations.
for make it shorter it will not count any quantity of candles. 
can u tell me what u need to be counted? ( 3 4 7 13 is the number of the candle from the end or the quantity of candles red/green in a row?)

**Comment by AFPEMI** [comment]
Good afternoon
I need to count any sequence of three (3), four(4) and seven (7) candles of the same color.
If the count is three red, as an example, the Bot will open a call operation at the fourth candle.
The same with the four (4) and seven (7) counters.

Thank you.

**Comment by Hooponopono** [comment]
[cuntakinte.txt](https://github.com/binary-com/binary-bot/files/3417374/cuntakinte.txt)
this count last 3 complete candles (2,3,4).
for your strategy i dont think u willl need nothing else because the 4candles in a row is like the last 3 and the 7in a row is like have the last  3 too.

**Comment by AFPEMI** [comment]
Good afternoon Hooponopono
Thank you for your reply.
I've edited the script as you've recommended, but it still not doing what I want.
I need it to identify a sequence of three candles of the same color and open an operation contrary on the fourth candle. Like, if there is a sequence of three(3) RED candles, it will open a CALL operation on the fourth candle, and vise versa if it is a sequence of GREEN candles.
The same procedure should occur for a sequence of four(4), seven(7) and additionally thirteen(13) candles.
The way it's setup, it's opening an operation at the second candle, and keeps opening other operations until the candle changes colors.
Thank you very much!

[cuntakinte(1).zip](https://github.com/binary-com/binary-bot/files/3418662/cuntakinte.1.zip)

**Comment by Hooponopono** [comment]
[cuntakinte(2).txt](https://github.com/binary-com/binary-bot/files/3425337/cuntakinte.2.txt) the older method of start a trade on new candle can give problems on your strategy, i used another way: when the new candle is new for sure( this give a delay of 2 seconds after the candle is new, the older method can give a wrong counting because of delays) now trade only on 3 , 4 and 7. i do not have too much time 4 be sure 100% but look like that is working correctly. if work good i think u can copy and expand what i did 4 all the 13 candles.
