### ISSUE TITLE
Request comments and suggestions about trendLine Bot.

### ISSUE THREAD

**Issue by Herotaiko** [binary-com/binary-bot#1741]
It's a bot that I developed from the original. I want to know everyone's opinions and suggestions to improve to be the most effective in the work.

![3](https://user-images.githubusercontent.com/51996252/61595530-962e6800-ac22-11e9-9996-a3cb19e74eea.PNG)

BOT:
https://drive.google.com/open?id=1_q4q2gBfhwoFx7c_A4ZLaf34EtQNflHK

@binary-ex-machina
@navneetsinh
@hotmatrixx

**Comment by binary-ex-machina** [comment]
@Herotaiko i see a possible problem on the blocks. You have set the default candle interval to 1min, but you used 1 hour candles as input list on the EMA and the default on the trend lines, this could lead to a problem on the analysis. I could suggest to put everything on the same candle interval.

Now the analysis. Using last tick with trend lines will always produce fake signals, it will break the trend lines multiple times and normally will enter on wrong moment. A better approach would be check how many times it breaks the trend line or check after some time, as confirmation.

Another problem is on the contract options. You use last tick to check the trend with EMA on higher time frame. This will also produce a lot of false signals, and you face a lot of problems with sideways market. A better approach could be working only with one direction for touch options, having one signal and barrier only. This way you will not enter on the wrong way multiple times.


I could add a limitation to check all the filters one time per candle, making the full analysis on the last tick of the candle. This will reduce the fake signals and you can test on multiple pages opened at the same time because the calculations will be reduced a lot.

**Comment by Herotaiko** [comment]
Thanks for the reply @binary-ex-machina 

> '' i see a possible problem on the blocks. You have set the default candle interval to 1min, but you used 1 hour candles as input list on the EMA and the default on the trend lines, this could lead to a problem on the analysis. I could suggest to put everything on the same candle interval.''
- I will adjust the time to match every point.

> A better approach could be working only with one direction for touch options, having one signal and barrier only. This way you will not enter on the wrong way multiple times.
- I understand this part that Should I choose to use one signal and barrier only more right ?

> I could add a limitation to check all the filters one time per candle, making the full analysis on the last tick of the candle. This will reduce the fake signals and you can test on multiple pages opened at the same time because the calculations will be reduced a lot.
- How can this filter block be created?


Sorry if my English is not good

**Comment by binary-ex-machina** [comment]
@Herotaiko 

You can still use the email to get only to the direction you want, it will trigger the same way. Include the EMA filter on the block 2.

To analyse only at the last tick of the candle, you can use like this below, changing the 60 (1min) and the 57 (candle time less 3 seconds) to your duration. Example: if you use 5min duration, use 300 and 297
![image](https://user-images.githubusercontent.com/34610787/61716753-2c06e780-ad36-11e9-8dfa-f1acb0e9ecb4.png)

**Comment by Herotaiko** [comment]
@binary-ex-machina 
I really want to thank you for your help, There is another question that I still doubt.
"barrier"
![Capture](https://user-images.githubusercontent.com/51996252/61726772-699e5b80-ad9c-11e9-9b93-43700c0d3971.PNG)
What is the meaning and effect of the design?

**Comment by Herotaiko** [comment]
I try to do this. Look at the results. Not very good.
![1](https://user-images.githubusercontent.com/51996252/61769435-7363a580-ae14-11e9-9713-fee88b22bf02.PNG)

**Comment by binary-ex-machina** [comment]
@Herotaiko this strategy is not good, forget about it. Offset will be the basis of your strategy, since you need to reach that target every time. Offset + will be the price when you buy the contract, plus the barrier. Offset - will be the price when you buy the contract, minus the barrier. If you don't reach, you lose. Trend line being broke multiple times by the chaotic last tick will be rarely good

**Comment by Herotaiko** [comment]
@binary-ex-machina 
![6](https://user-images.githubusercontent.com/51996252/61803675-cd885900-ae5c-11e9-8426-60ee58541ade.PNG)
If so, what should I do?

**Comment by binary-ex-machina** [comment]
check my answer https://github.com/binary-com/binary-bot/issues/1741#issuecomment-513815831

**Comment by Herotaiko** [comment]
@binary-ex-machina 
Thank you for your help. If there are any results, I inform you.

**Comment by Herotaiko** [comment]
@binary-ex-machina 
I try to convert it into a rise/fall model, What do you think?
![Capture](https://user-images.githubusercontent.com/51996252/61855765-e6d7e680-aeea-11e9-8188-bbf9fb670670.PNG)
