### ISSUE TITLE
can i 2 perches 1 time.... ? 2 trade in same time?

### ISSUE THREAD

**Issue by dushanu** [binary-com/binary-bot#1746]
can i 2 perches 1 time.... ? 2 trade in same time? one bot

**Comment by dushanu** [comment]
only different microseconds ok
like 12.10.35.00 pm 12.10.35.01pm

**Comment by dushanu** [comment]
any help?

**Comment by lasaidhari** [comment]
1 BOT cannot open 2 positions in 1 bot. You make 2 bot tabs

**Comment by dushanu** [comment]
any software or script?

**Comment by lasaidhari** [comment]
give an example, I will make it:
1. market?
2. trade type?
3. duration?
4. what is martinggale?

**Comment by dushanu** [comment]
Volatility index 10
5 tick
4 under 6 over 
Martingale 2 x

**Comment by dushanu** [comment]
Please upload as text or xml... Thanks @lasaidhari

**Comment by lasaidhari** [comment]
![run 2 bot over 6   under 4](https://user-images.githubusercontent.com/34808023/61739595-a78f8580-ad84-11e9-919d-57f96dc4c7f1.gif)
[run 2 bot over 6 & under 4.zip](https://github.com/binary-com/binary-bot/files/3423740/run.2.bot.over.6.under.4.zip)

BOT over 6 & under 4 this version uses digit analysis. I will re-create the version using time so that it can be used only on the only down or touch no touch.

before playing bot:
1. Make sure the settings of the two bots are adjusted and the same
2. Make sure your network conditions are stable

**Comment by lasaidhari** [comment]
![run 2 bot over 6   under 4](https://user-images.githubusercontent.com/34808023/61751058-fd712700-ad9e-11e9-96b1-3f862984b061.gif)
BOT over 6 & under 4 this version uses digit analysis.
before playing bot:
1. Make sure the settings of the two bots are adjusted and the same
2. Make sure your network conditions are stable
[run 2 bot over 6 & under 4.zip](https://github.com/binary-com/binary-bot/files/3424235/run.2.bot.over.6.under.4.zip)

**Comment by dushanu** [comment]
thank you very much @lasaidhari .... your very kind... best of luck your feature... god bless u... thanks again

**Comment by lasaidhari** [comment]
try it first on virtual. look for the duration and the right analysis.
