### ISSUE TITLE
Can create a MFI and Demark strategy?

### ISSUE THREAD

**Issue by Herotaiko** [binary-com/binary-bot#1774]
Do I know if we can create a bot that contains this as the image?
![aa](https://user-images.githubusercontent.com/51996252/62006134-e9467480-b166-11e9-80b0-41f833c998b1.PNG)

**Comment by AlienFly** [comment]
1. For the calculation of  MFI used "volumes", so to implement it in the "constructor" is not possible.

2. Formula for calculating DeMarker indicator is easy find in Google and just as easily reproduced.

`_The DeMax(i) is calculated:_
If high(i) > high(i-1) , then DeMax(i) = high(i)-high(i-1), otherwise DeMax(i) = 0

_The DeMin(i) is calculated:_
If low(i) < low(i-1), then DeMin(i) = low(i-1)-low(i), otherwise DeMin(i) = 0

_The value of the DeMarker is calculated as:_
DMark(i) = SMA(DeMax, N)/(SMA(DeMax, N)+SMA(DeMin, N))`

**Comment by Herotaiko** [comment]
Thank you for your help. @AlienFly 
If possible, show me how to create a DeMarker blog in binary bot.
