### ISSUE TITLE
21 RSI With 5 EMA And 12 EMA

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1784]
**Indicators:** 5 EMA, 12 EMA, 21 RSI

**Buying :**
1. When 5 EMA crosses 12 EMA to the upside, that's an indication that the trend has changed to uptrend.
2. Next you look at the RSI Forex Indicator and If its above 50, then Buy. | suggest you buy immediately at market Price.
3. Place your stop loss at least 2-5 pips below the low of the cross-over candlestick.

**Selling :**
1. When 5 EMA crosses 12 EMA to the downside, that's an indication that the trend has changed to a downtrend.
2. Next you look at the RSI Forex Indicator and If its below 50, then Sell. | suggest you sell immediately at market Price.
3. Place your stop loss at least 2-5 pips above the high of the cross-over candlestick.

@binary-ex-machina
@lasaidhari
@aaron-binary
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost

**Comment by binary-ex-machina** [comment]
@navneetsinh this is for forex trading, not binary. Looks very copy/paste. I know you are asking and posting here for some time now and i'm very sure that you already asked about crossing moving averages or values, i though you where learning something, not just copying blindly. This is not a repository to get all strategies for free, you need to learn something and start building the bots by your own, that's why i help here.

I'll let the cross EMA here, but please, learn something, next time i'll not help (and maybe others will not help as well)

![image](https://user-images.githubusercontent.com/34610787/62218559-14a5ab00-b383-11e9-99e1-0cee203e3d4d.png)

**Comment by Rover1953** [comment]
Dear Fruitfella, I'm trying to create the bot "trend+rsi", using Your bot "trend direction" together with rsi indicator. The picture is attached. Unfortunately my bot doesn't work. Why? Thank You in advance.
![trend+rsi](https://user-images.githubusercontent.com/39854027/74967580-f3d99b80-5421-11ea-8fd7-6d6334fc2f79.png)

**Comment by Rover1953** [comment]
Dear Fruitfella, please, give me, if possible, Your FRUITFELLA's HullMA Array Indicator. Many thanks in advance.

**Comment by buckman1974** [comment]
I have slowed down using some of the many many bots on here, but after looking at the Hull MA in general, i'd like to have a look at @fruitfella Hull MA bot please if its possible?
