### ISSUE TITLE
100 EMA - SMA 28

### ISSUE THREAD

**Issue by navneetsinh** [binary-com/binary-bot#1786]
**Indicators:** 100 EMA Close, SMA 28 Close | **Time frames:** 5 Minute

**Entry :** The 100 EMA shows the trend. So if we were in a down trend as given by the 100 EMA and a candle closes above the 100 EMA, we enter a buy, you would stay in that buy until a candle closes below the 28 SMA and re-entries are made using the 28 SMA once price touches it or closes above it when it has first closed below it. The reverse is for a sell trade.

@binary-ex-machina
@lasaidhari
@aaron-binary
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost

**Comment by binary-ex-machina** [comment]
@navneetsinh again, another forex strategy, since you can't control when the trade ends on binary options, after you buy the contract

below is how to get the 1m candle closing above EMA100
![image](https://user-images.githubusercontent.com/34610787/62219597-fd67bd00-b384-11e9-881d-d13edfe51508.png)
