### ISSUE TITLE
Is it possible to set the bot change barrier offset?

### ISSUE THREAD

**Issue by thanh301** [binary-com/binary-bot#1811]
Hello, I make a bot to trade at Touch/no Touch type and try to set it change the barrier offset but it keep getting error like picture below. Is there any way to set the bot working?
![rrier trade](https://user-images.githubusercontent.com/52536345/62414268-40ef4f00-b643-11e9-9056-42010b08b1ce.png)

**Comment by lasaidhari** [comment]
![eror barrier](https://user-images.githubusercontent.com/34808023/62417374-8f9de880-b645-11e9-82cf-8f3f024e686d.gif)

**Comment by thanh301** [comment]
@lasaidhari  Sorry I not saying clearly. What I mean is to set the bot auto change the barrier offset when certain condition are met, not by manualy, as you can see from the picture when the tick cross the upper band i want to set the bot auto change barrier to -1 and make a trade

**Comment by lasaidhari** [comment]
make changes to barrier offset that can occur after you win or have lost. because the change in barrier offset only occurs after getting a win or lose trading result.
How blocks work on bot.binary.com
![work](https://user-images.githubusercontent.com/34808023/62421121-96078100-b694-11e9-97e6-96e8c550ebef.jpg)


 make a variable like this to determine the direction of the trend to use the barrier offset- or barrier of offset+ before getting the trading results
![TOUCH PART1](https://user-images.githubusercontent.com/34808023/62421123-a0c21600-b694-11e9-9516-608e952c8d5c.jpg)
or
![TOCH PART2](https://user-images.githubusercontent.com/34808023/62421127-ac154180-b694-11e9-8134-d48777174be4.jpg)
There are many other ways. basically the way the bot works is the same as game number 1

**Comment by thanh301** [comment]
Thank you! Didn't know we can set If do in Define Trade Option
