### ISSUE TITLE
Please, i need help or suggestion

### ISSUE THREAD

**Issue by eonuoha30** [binary-com/binary-bot#1815]
@binary-ex-machina
@lasaidhari
@aaron-binary
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost

Hello...!!!
Pls help me work on this...

I have a bot that changes LOSS STREAK by 1 if there's a loss or sets loss streak to 0 if there's a win.

Maximum loss streak= 3

But what I want is this.....
When the LOSS STREAK = 2 , I want the bot to run 3 trades using same stake.
If all 3 wins, it restarts from the beginning or first stake when LOSS STREAK = 0

But if any amongst the three loses, it automatically goes over to the final point where LoSS STREAK=3

For instance....

If first stake is 1$ and it loses, it switches to stake 2.

If stake 2 wins, it will repeat 3 times (consecutive wins).
But if any amongst it loses, it immediately & automatically switches to stake 3

**Comment by hotmatrixx** [comment]
hey mate, I am heppy to help you to write a bot, but i honestly feel that it's something that you need to learn how to do for yourself.

anyway. I coded it. I did a real simple version with lots of 'if' statements.
i did a simple function called 'reset' just so you can see how functions work
remember if you set the stake to something, it won't bid that stake amount until after it starts a new cycle with 'trade again' that's why I can reset the stake in stage 2 and it will still do your maximum bid.

there are more efficient ways to code this, but hopefully this is easier for you to understand how it works and will help you to start to learn how to make your very own bots from scratch.
anyway. it's doing what you wanted.

[HERE IS YOUR DOWNLOAD](https://github.com/binary-com/binary-bot/files/3471487/eon.zip)
here it ramps up, and resets on a win
![image](https://user-images.githubusercontent.com/49715381/62529498-e0565100-b892-11e9-8800-70d8ee3c7077.png)

here it ramps up and resets on a loss
![image](https://user-images.githubusercontent.com/49715381/62529575-04b22d80-b893-11e9-8b04-1df1d2781c1c.png)

it should also reset if it wins at stage 2, 3 times in a row.
