### ISSUE TITLE
Check last digit

### ISSUE THREAD

**Issue by felixhuy** [binary-com/binary-bot#183]
Hi Amin,

Can you help me!
I want check count last digit
if last digit appear < 4 times in a time. we will purchase that last digit. I tried but i cant think that
![capture](https://cloud.githubusercontent.com/assets/26194420/24086574/488113fc-0d44-11e7-8393-02ae60e51b2e.PNG)

**Comment by aminmarashi** [comment]
Hi, can you please elaborate the strategy? What do you mean by maximum  "4 times at a time"? Because if you mean per run, every last digit has appeared exactly 0 times per run, so we will buy any of them that appear?
And if that's the case, there'll be a time that all last digits are appeared more than 4 times, then we won't buy any new trade?
P.S., I don't think it might be a good idea to create your strategies based on the digits, they seem to be quite random.

**Comment by felixhuy** [comment]
If not, i can check last digit lower 4% appear and purchase ?

2017-03-20 9:01 GMT+07:00 Amin Marashi <notifications@github.com>:

**Comment by aminmarashi** [comment]
I'm sorry, but it's currently impossible to set the prediction on a purchase. You'll need to define your prediction in the 1st block and you can't go back and change it when you want to purchase the contract.
It's similar to #152. I hope we can implement that in the next version of the Bot.

**Comment by felixhuy** [comment]
ok i will think more about that problem

**Comment by okovalov** [comment]
@felixhuy the only way (not the smartest, though) is to have 10 tabs with the bot opened, and each tab would have a copy of the bot loaded, and would be configured to use one number (like first tab would have 0 as a predicted digit, second would have 1 etc)
