### ISSUE TITLE
DigitDiff Prediction Issue

### ISSUE THREAD

**Issue by XCelestialX** [binary-com/binary-bot#1841]
I have tried to use the penultimate digit of the last exit spot as prediction and even if it doesnt matches, it still loses, this doesnt makes sense. What is the problem?

**Comment by lasaidhari** [comment]
try sending the xml file. I see something might be wrong

**Comment by XCelestialX** [comment]
@lasaidhari It is just simple bot:

[botV3.txt](https://github.com/binary-com/binary-bot/files/3504259/botV3.txt)

**Comment by lasaidhari** [comment]
your bot logic is wrong

**Comment by lasaidhari** [comment]
you set the prediction in block (4) it makes 1 tick late,

**Comment by XCelestialX** [comment]
@lasaidhari So there is no solution?

**Comment by lasaidhari** [comment]
every move block is always touched 1tik. therefore every bot purchases 1 tick late.

if you want to copy functions from another bot, you can use notepat ++. this is a load from block tutorial using github. but if you want to load from disk you can also save it on disk .. https://www.youtube.com/watch?v=sqXggeByF9k&t=134s

**Comment by XCelestialX** [comment]
@lasaidhari Hey man, do you know what is this?

![image](https://user-images.githubusercontent.com/53317247/63076178-f51d8f00-bef9-11e9-922a-facefb5f232f.png)

**Comment by lasaidhari** [comment]
send you bot

**Comment by hotmatrixx** [comment]
you can fix bots buying 1 tick late.
you set them up with a prediction like this:

basically you need to 

- set the prediction,  (either do this in block 3, 4 or better, "define trade")
- make the trade definition, then in step 2, 
- wait for the tick to match your prediction, 
- THEN buy immediately.
![image](https://user-images.githubusercontent.com/49715381/63093633-265d9400-bfba-11e9-98d7-746c0a1d83c4.png)

**Comment by XCelestialX** [comment]
@hotmatrixx Are you sure about that code? This is digitdiff man.

Also this really doesnt make sense, at least to me, i dont know why it is needed to by a tick late or early, i just take the exit spot number of the last trade in Get the results and then using the penultimate digit as prediction. I dont see why is the need of speed and sync here, it just take that digit as a prediction, right?

Also what is the difference between Volatility 10, 25, 100 etc.?

**Comment by binary-ex-machina** [comment]
@XCelestialX the tick if ends not necessary is the tick the contract finished, specially in 1 tick duration

example
tick 1 - 1001.3 - you buy the contract
tick 2 - 1001.5 - you enter the trade
tick 3 - 1002.1 - your contract ends and it's calculated
tick 4 - 1002.3 - depending when you get the result, this is the exit tick it will appear

This is caused because it has a delay between your computer sending the trade request and getting the result. 1 tick duration will have these issues because it's impossible to enter and exist the same tick every trade, you need to gap between them.

**Comment by XCelestialX** [comment]
@binary-ex-machina Oh so it would be more accurate if it 2 or 3 ticks duration?

And it wouldnt be pointless to put the exit spot in the data table right? If the exit spot isnt the "real exit spot" so why?

**Comment by binary-ex-machina** [comment]
@XCelestialX this happens depending on the response of the trade. It's impossible run perfectly without any delay, on server and client side. Because of this, your trade end on a tick after and start 1 tick after. I don't know your strategy, but what makes you think using the exit value last digit as prediction will help you avoid losses? There is no correlation with that analysis and probability, since any number can come next.

**Comment by XCelestialX** [comment]
@binary-ex-machina Nothing it was just an observation, i was kinda testing if it could give better results. It was going well until it loses for no reason, even if the digits didnt match.

**Comment by baintalu** [comment]
last digit at last tick not same

![Screenshot_28](https://user-images.githubusercontent.com/16547446/63664848-3ae02e80-c7fb-11e9-9667-3ad8a1b86b2d.png)
