### ISSUE TITLE
Help Me Pls.

### ISSUE THREAD

**Issue by Adammodex** [binary-com/binary-bot#1864]
Hi,
I have a bot that is working perfectly.
But Sometimes, the bot make some dumb decisions and can't stop doing them but i can't blame him on that because it's the nature of the volatilities Indexes.
So Basically the bot is a rise/fall robot which makes analysis on his own and then he decides what type of contract he should buy. (Call - Put)
What i want to do is that if the bot buys one contract and Fail 3 Times in a row. i want to make him stop until the analysis Matches With the other Type Of Contract.

- Example:
Call 1 - Loss
Call 2 - Loss
Call 3 - Loss
Bot Stops And Wait for the analysis to match the next type of contract.
Fall 1 - Win

Thank You For Your Precious Time Dear Coders.

@binary-ex-machina
@lasaidhari
@Hooponopono
@hotmatrixx
@AlienFly
@murali139
@baruga
@ghost
@Eshhh

**Comment by lasaidhari** [comment]
send xml. I add the logic

**Comment by Adammodex** [comment]
[txt.txt](https://github.com/binary-com/binary-bot/files/3532427/txt.txt)

Here You Go Sir, Pls Change .txt to .xml

**Comment by lasaidhari** [comment]
wait

**Comment by Adammodex** [comment]
Okay Sir.

**Comment by lasaidhari** [comment]
I see some functions that are not used for Martingale

**Comment by Adammodex** [comment]
Did You Finsih Sir ?

**Comment by lasaidhari** [comment]
I can't record the creation of the analyst function because of its long duration, but you can learn with the files I added
![@ANALISYS CALL AND PUT](https://user-images.githubusercontent.com/34808023/63564875-b70a1600-c55e-11e9-9745-e34bfe9bf515.gif)


[add call put.zip](https://github.com/binary-com/binary-bot/files/3532738/add.call.put.zip)

**Comment by hotmatrixx** [comment]
try this one out:
![image](https://user-images.githubusercontent.com/49715381/63576246-e319ab80-c5df-11e9-911e-afe06c6ea405.png)

**Comment by Adammodex** [comment]
@hotmatrixx This Type File Should Be Used When I set the bot for example to trade only Call Trades.
and when i lose the bot changes to put. 

But My Bot Makes its own analysis and Trade Call - Put On His Own.
So the Question is : How Can The bot know the Type of the contract that i lost, and how can he change it.

**Comment by Adammodex** [comment]
@lasaidhari Thank You For Your Effort ! 👍

**Comment by Adammodex** [comment]
@binary-ex-machina What do you think about it ?!

**Comment by binary-ex-machina** [comment]
@Adammodex i didn't understand what you want to know. From what i read in your last post, the bot can detect the contract type on block 4 using Contract Detail block


![image](https://user-images.githubusercontent.com/34610787/63615766-79d47100-c5bc-11e9-8059-b91394d04e10.png)

**Comment by hotmatrixx** [comment]
> 
> 
> @Adammodex i didn't understand what you want to know. From what i read in your last post, the bot can detect the contract type on block 4 using Contract Detail block
> 
> ![image](https://user-images.githubusercontent.com/34610787/63615766-79d47100-c5bc-11e9-8059-b91394d04e10.png)

yep, I also have a strategy that calculates the direction on every new candle, that run in a 'run in every tick' window. it changes a variable called Trend Direction to true or false.
in my 'main' #2 block, I have this (I've disabled the HISTO part ATM because I'm bug testing)

this way I know the trade's direction before the trade is made.
![image](https://user-images.githubusercontent.com/49715381/63627813-79d87d80-c65d-11e9-8cbe-d080417d6bca.png)

**Comment by Adammodex** [comment]
@hotmatrixx Thank You, I'll try to implement that, and see how it works

**Comment by Adammodex** [comment]
@binary-ex-machina, May You Please Read My Description and My Example that i gave? Thank you 👍
