### ISSUE TITLE
Cataloging candles history

### ISSUE THREAD

**Issue by AFPEMI** [binary-com/binary-bot#1904]
Good morning,
Is there a way to catalog candle's history, lets say for the past 2 hours or so?
And how many times they appeared in sequences, like how many times in the past 2 hours I had a sequence of 3 red candles and the fourth candle was green, and vise-versa.
I tried a few things but not getting anywhere.
Thanks

**Comment by binary-ex-machina** [comment]
You didn't specified the candle time, so I will use 1min as example. Candle and ticks lists return 1000 items when you use the block. I advise use less then that, because the bot will hang and may crash your browser. The image below will show two examples, getting the number of 3 red candles that appear in sequence in the last 120 candles. The second will be almost the same, but with green candles. It's important to use Run After 6 or more seconds, because block 2 is a Loop block, it will repeat the process every 2 seconds, so it may crash fast.

![image](https://user-images.githubusercontent.com/34610787/64265873-06125c80-cf0a-11e9-8223-78a79cce2175.png)

**Comment by AFPEMI** [comment]
Thank you very much
I'll write the script and test run it to see the results and ways to evolve it.

Thank you

**Comment by AFPEMI** [comment]
Hello Binary-ex-machina
I wrote the script based on your suggestion, however I added a few blocks to fulfill my expectations:
There are two problems:
1) The bot is running too slow
2) It is not opening any operations, put/call
The strategy is: after a sequence of 3 candles of the same color the bot will open an operation on reverse, if the "probability" is above 75%

I reduced the interval from 120 to 60 and tried to move a few things around to see if it'll get better but no success.


[60 Candles(1).zip](https://github.com/binary-com/binary-bot/files/3585946/60.Candles.1.zip)

Thank you

**Comment by binary-ex-machina** [comment]
you added too much thing. Reduce what you are analysing in at least 75% and split into multiple scripts. Also, you need to reduce the analysis otherwise your browser will crash. Use your script bot to trade in one window and use multiple scripts in multiple windows to get the catalog. Increase the time for the catalog too, use 10-20 seconds

**Comment by AFPEMI** [comment]
Can you shine some light on how to wright the script in two windows?
I've never done it before.
Thanks

**Comment by AFPEMI** [comment]
Write, not wright

**Comment by AFPEMI** [comment]
If I reduce what I'm analyzing the strategy becomes inefficient. 
Looks like the loop is whats causing the problems.
Is there another way to catalog without the loop?
Thanks.
