### ISSUE TITLE
BOT Differ strategy

### ISSUE THREAD

**Issue by sandramanaka1** [binary-com/binary-bot#1966]
Hello bang @saidforex26..
can you help for created bot differ with V100, when lasting 2 digit number are Twin then take OP with 5 tick

2 digit twin red colour
![Untitled](https://user-images.githubusercontent.com/49223463/65480823-1a1ffd00-debd-11e9-97b3-dc307b2261d9.png)

and 

2 digit twin blue colour
![Untitled](https://user-images.githubusercontent.com/49223463/65480839-2906af80-debd-11e9-9e84-564d4affc294.jpg)

**Comment by wilburforce83** [comment]
Hi @sandramanaka1 I wouldn't bother really, the odds are no different. 

In order to trade digit differs, you really need to play the entropy game; if you **know** that you have a 1:10 chance of losing, you need to try and do everything you can to ensure that you get a better chance. If it must be 1 : 10, then place your trades when the digit is abnormally more prevalent i.e. entropy dictates that it must return to 1:10. But as we are looking at a market which has support and resistance points, we need to try and avoid placing a trade on a digit which is being repeated due to the market movement as well, so it is not that simple.

Feel free to play with this xml I have for trying to beat the odds on the digit game. I works most times, but with all gambles, if you play it too much you will lose!!!

This uses the mode values of digits for periods, the last close digit, and then also locks trading when a short RSI is high or low, or a longer RSI is sitting in the middle (indicating S+R or stagnation.

[Digit Loop Diff V2-0-6(Apdaptive Exit Digit).zip](https://github.com/binary-com/binary-bot/files/3648305/Digit.Loop.Diff.V2-0-6.Apdaptive.Exit.Digit.zip)

**Comment by ceakuk** [comment]
@wilburforce83 
honestly what are you saying?
of course the last digits are purely random and can never be predicted. even if  for the last 100 ticks we have  100 zeros, it doesnt make trading diff = 0 win because these are random numbers.
where does support and resistant come from?
that is only with  candle sticks in forex and probably  volatility index i doubt it.

remember  support and resistant points are determined by sellers and buyers in a real forex market
 with volatility index, the signal is artificially generated and does not rely on buyers and sellers. thats why  there is no specific trading time that is quiet. more volatility = ease of making and loosing money. binary.com does not allow trading forex within a given time because the markets are so quiet and they can easily loose money to traders. but for volatility index they have all the advantages

**Comment by wilburforce83** [comment]
@ceakuk 

Yeah agreed on a lot of this, to answer your specific questions:

1. S&R. 

Firstly S&R has nothing to do with candles, a candle is just a representation of a fixed period of ticks, filtered to show on the highest, lowest, open and close point. S&R can be seen at any scale and any time period, on any market which is affected by real people. Which leads me on to...

The VIX algorithm for the synthetic markets replicates many real market conditions. Obviously none of us **know** the algorithm, but I have literally billions of ticks of data backtested, virtual tested, and live tested and I can infer a lot from my experiences:

- The market is not purely random, I believe each one is index-linked somehow via a complex equation which uses variable scaling factors and injects random number to disguise its sources.

- I believe that the market moves partially based on contracts, but differently to how pips move. I believe that for any given epoch the algorithm calculates the overall volume of the open contracts and moves towards the nett gain, so if there is a nett positive of open contracts higher than x in 5 minutes from now, the market will slowly work it its way down UNLESS the nett gain after that given epoch is greaterin the opposite direction. This is fluid and changes based on all open contracts, contract values, and closing epoch.

**How do I know this?**  I can produce algorithms which work in backtesting over 120 days of data, which work in virtual, but fail in live. **This is not anything dodgy by binary.com**, this is just the reality of backtesting on a market which is affected by open contracts, backtesting does not work if the market changes based on your contribution to it. Therefore, I can only infer that the market is indeed effected by open contracts, therefore S&R exists.

2 . Randomness more generally

From above you can see why I believe that there is an element of being able to reduce risk through avoiding tipping points where, I believe open contracts due to win vs open contracts due to lose 
are nett neutral to binary.com, only when a larger trade is placed or open contracts close off changing the balance does the market start to move again in a given direction.

Random number generation; computers are bad at this, and generally only produce pseudorandom numbers which are prone to entropy, so viewing an abnormal number of x digits, outside the parameters of S&R, has more significance than it rightly should.

Of course,  you are totally right 1:10 **should** be 1:10 , 50:50 is 50% even if it is has returned the same number 10,000 times in a row, the odds next time are still 50:50. However, the failings of random number generation shouldn't be overlooked when looking for an edge.

I hope that makes sense, and my speculations don't get me banned!! lmao

**Comment by wilburforce83** [comment]
@ceakuk  Sorry, I think perhaps I didn't answer as to why I felt S&R is important in digit differs trades. S&R will increase the propensity of repeating digits because of the likelihood of falling back to an index value, which is the opposite of the concept of entropy within random number generation, therefore it has a negative effect on the idea of using higher frequency digits as a basis for choosing the digit differ integer.

Cheers!

**Comment by saidforex26** [comment]
> 
> 
> Hello bang @saidforex26..
> can you help for created bot differ with V100, when lasting 2 digit number are Twin then take OP with 5 tick
> 
> 2 digit twin red colour
> ![Untitled](https://user-images.githubusercontent.com/49223463/65480823-1a1ffd00-debd-11e9-97b3-dc307b2261d9.png)
> 
> and
> 
> 2 digit twin blue colour
> ![Untitled](https://user-images.githubusercontent.com/49223463/65480839-2906af80-debd-11e9-9e84-564d4affc294.jpg)
@sandramanaka1 hopefully can help
[differ 66 77.zip](https://github.com/binary-com/binary-bot/files/3649990/differ.66.77.zip)
![differ 77 66](https://user-images.githubusercontent.com/54820719/65559961-ac171c80-df34-11e9-862e-669b7a71ac07.gif)

**Comment by sandramanaka1** [comment]
@wilburforce83 and @ceakuk , thanks for reverting, and both of your ideas and strategy are good,
@saidforex26 , thanks so much your effort

**Comment by martinrf79** [comment]
Hello how are you wilburforce83 or dijoforeforex26
![cantidad velas digitos](https://user-images.githubusercontent.com/52263754/65821197-afe2c180-e208-11e9-9025-7da8cf66e4dc.png)
  , I would like to know if it is possible to create a script like the one I send attached with digits in volatility indices 100
What I need is to know how many times each repeated digit comes out in x amount of ticks or digits in the history.
Example with digit 8 twice repeated x number of times, 3 times repeated x number of times 4 times repeated x number of times etc. and so with each digit from 0 to 9.

**Comment by vipclubsi** [comment]
@wilburforce83 I found your vision quite interesting!

Could you make this tick repository available for the purposes of probability analysis?

Thank you very much in advance! :)

**Comment by wilburforce83** [comment]
> @wilburforce83 I found your vision quite interesting!
> 
> Could you make this tick repository available for the purposes of probability analysis?
> 
> Thank you very much in advance! :)

Hi there, I've been asked a few times, actually. I need to clean the code a bit, but I do plan to release the backtesting app under MIT soon. It's just a CLI nodejs app. But the strategy files are simple to script and I've templated them; it's basically similar to the binary bot CLI, but on steroids, bug fixed, and with lots of analysis :)

**Comment by mdtazmir1** [comment]
@saidforex26
help me pls bro help me pls i need one digit differs bot
like only last digit 0 and 0 end after trad not before fast time 0 coming not trad two times 0 coming after tradneed- help me
![dg](https://user-images.githubusercontent.com/67690709/105673535-3c81ba80-5ef7-11eb-8394-b636b7af4c6b.png)

**Comment by bobmeg** [comment]
Hello...i have a digits bot ive been testing for almost a month now...recently its been freezing in the middle of the tests...yet on the bot it still shows that the bot is running..every time it does this i have to stop the bot and press play again..its so frustrating especially when there has been a loss...ive tried to clear my browser history but nothing has changed...can anyone help out here
