### ISSUE TITLE
volatility Indexes

### ISSUE THREAD

**Issue by pauloceia** [binary-com/binary-bot#1970]
Can anyone tell me if trading with bots on volatility indexes is legit because 
of binary.com can make us lose trades ?

Is there any sites where we can look at the value of indices in real time to check if binary
is not changing therm ?

**Comment by wilburforce83** [comment]
Binary.com **are** the indexes, they generate them, they are synthetic markets. So by definition, they change them. Does that make them fraudulent? no. They are legit forms of trading.

No one but binary.com know the algorithm they use, but my guess is that they move the market on the nett benefit to themselves. Again this doesn't mean they are cheating anyone, for any given epoch (point in time) they will have winning and losing trades. It just means that if you place a **big** trade which is effecting the market, it is more likely to have an adverse effect on the index movement. In that sense, it is my opinion that negative progression systems, such as martingale, will ultimately fail on the platform.

You can still make good money on the platform though. For example, a strong trend may be as a result of someone placing a large trade, or could be predetermined market movement, who knows!!? but let us assume it is as a result of market volume pushing binary.com to move to point of profit, in this case, you can fairly safely place small trades in the direction, as you are not likely to affect momentum with your trade.

Of course, this is speculation, none of us can know how their algorithm works.

Regarding if bots are legit. 100% All transactions with binary.com use their binary-live-api which is opensource, many of us use it for our own node.js bots and 3rd party platforms. **binary.com do not move the markets to effect individual trades** that much is clear, it would be logistically implausible, and very easy for us coders to spot and start kicking and screaming.

I hope this helps and provides you with the answers you are after :)

**Comment by eonuoha30** [comment]
@wilburforce83  , how can I be a coder like you?

What do I need to read and where do I start from?

**Comment by wilburforce83** [comment]
@eonuoha30 I only started learning Node.js and JS about 6 months ago - So I am pretty new, to be honest - I am no expert that's for sure! Any experienced coder would probably look at my source codes and cry lmao - But it works, and a friend said to me that you can always go back and clean up older code as you get better, it shouldn't stop you building great ideas. It is, I guess like building prototypes, they don't need to be the quickest, fastest and most efficient, they need to prove the idea, then get refined.

Although I got into JS about 6 months ago, I have been a mechanical engineer for the best part of 15 years, where I have experience in other languages (CNC coding, MATLAB etc), advanced maths and statistics etc, so I definitely have a step up from knowing nothing at all.

Languages like Javascript are really simple, but the learning curve is steep. If you have any maths experience, any programming language will come very quickly to you, they are just programmatically following logic, once you understand **how** they do it, the rest is just limited to your ideas i.e. limitless.

I just followed some youtube tutorials in order to get a grasp of the main concepts, then when I have a specific problem is tend to just use https://www.w3schools.com and https://stackexchange.com/

I found tutorials on things I was interested in and built a few demo scripts and worked from there. I'd just hit up Youtube and play about in https://code.visualstudio.com

**Comment by pauloceia** [comment]
I aprecciate the help , but i have a question .... ho pays the profit trades ? Binary.com ?
So if we earn a lot they lose a lot ?

**Comment by wilburforce83** [comment]
@pauloceia  Hi, it's all on their website. The payouts are exactly like a Casino. binary.com take the risk, they have the edge 94% return on 50:50.

If you look at their page binary in number; https://www.binary.com/en/binary-in-numbers.html they state:
circa $1 billion in turnover per annum, with client payouts of $150 million, some of the payouts will be from nett losses i.e. deposit 5k, lose 2k, withdraw 3k. so you can see how it makes sense financially to them.

Most people trading are degenerate gamblers who want a fix all switch on and leave robot lmao - there is a lot of turnover but there are a few people who take it seriously can make good money.
