### ISSUE TITLE
Estimated duration

### ISSUE THREAD

**Issue by radon222dose** [binary-com/binary-bot#1976]
Dear friends! Help me please!

For my semi-automatic trading of volatility indices, it is necessary that the bot set the estimated duration when making a contract purchase.

For example, when the price reaches a certain value, a contract is bought RISE or PUT with a certain duration (seconds until the candle closes).

In my bot, what happens is that the duration of the contract is calculated from the moment the bot itself is launched, and not the duration from the moment of the event (when the price reaches the set value).

Sorry for my English

**Comment by wilburforce83** [comment]
This is actually quite tough (may not even possible) in the blockly bot as the whole duration thing is part of the `trade definition` block which is run from the `trade again` block which only runs after the last rade is completed (i believe - it's been a while since I did the blockly stuff).

So if you make duration a variable it will only update each time the `trade again` block is called, even is the variable you use is being updated per tick.

I hope that helps

**Comment by radon222dose** [comment]
Thank you, I will wait for other comments
