### ISSUE TITLE
Seconds between trade open/close

### ISSUE THREAD

**Issue by Ashlep95** [binary-com/binary-bot#1980]
Hi guys,

First of all massive thanks to those who have helped me this pass week, I finally have exactly what Im looking for, muchly appreciated so HUGE shoutout to @ceakuk for all your help.

Juat curious does anyone else run into this issue (see below image) trades open / close few seconds later and later each tradr which ends up accumulating quite fast and throwing it off, any ways around this ? Cheers

![Screenshot_20190926-231159](https://user-images.githubusercontent.com/55533641/65700638-90d21b80-e0b2-11e9-9783-fe612076731e.png)

**Comment by Ashlep95** [comment]
P.s. these are obviously 5 minute trades

**Comment by ceakuk** [comment]
@Ashlep95 
looks to me like you are taking trades every 5 minutes like your bot wanted to.
as for when it closes, I can't see from the screenshot. the only way trades can close early is if you are using sell
![Unbenannt](https://user-images.githubusercontent.com/43122491/65701987-8861ec80-e082-11e9-9c3e-3eb00f267d28.PNG)

**Comment by Ashlep95** [comment]
Oh yes the bot is doing every correctly, however see the "seconds" they are going up by incremments of about 5 seconds or so, so the last trade it took was actually about 45 seconds off from when the ca dle actually closed, if that makes sense

**Comment by wilburforce83** [comment]
@Ashlep95 This the authentication / contract audit time, so it'll take a tick or two each side of a trade in order to open and close contracts.

If you are trying to trade on exactly the close/ open of a candle, you will need to place a trade on ` epoch % 300 === true` I think. This will ensure it only places a trade if the remainder of the epoch is equal to 5 minutes.

Of course, this will only place a trade on every other candle, as you correctly say, as it is shifting a few seconds each trade.

**Comment by wilburforce83** [comment]
Am on my phone atm. But I think with blockly there is a math block for remainder. @ceakuk might be able check for you as I can't check atm. @fruitfella has some blocks for candle analysis which I believe includes new candles

**Comment by ceakuk** [comment]
here it is from  @Fruitfella 
[binary-bot - 2019-10-02T093715.867.xml.zip](https://github.com/binary-com/binary-bot/files/3681345/binary-bot.-.2019-10-02T093715.867.xml.zip)

**Comment by ceakuk** [comment]
but still there is a 2 seconds delay
if you are trading 1 minutes candles, he is using 2 minutes or 2X so that there is a brake between trades.
when you said there was a prograssive increase in time, is not very true. its just that it takes some seconds to take a trade
say you want to trade at 07:00:00 but it takes a trade at 07:00:02, the trade will run for 1 minute meaning the next trade will start at 07:1:02 so it passes that delay  to next trades.
some of the   subsequent trades also loose like a second which is passed to the opening time of the subsequent   trades and so on.

trading at 2 times the  time you need therefore gives you  the one minute  breake so that any delay is not passed to the coming trades.
thats what fruitfella's code does. i hope it helps

**Comment by lucky4911** [comment]
I need help please create 30 sencad new candle

**Comment by lucky4911** [comment]
Please

**Comment by lucky4911** [comment]
![Screenshot_20220327-111757](https://user-images.githubusercontent.com/101167009/160268553-82540410-7644-4f57-8b6e-51b92b05c22f.png)
Like this type new candle 30 second
