### ISSUE TITLE
I want when max level martingal to stop trading, Please help me.

### ISSUE THREAD

**Issue by Herotaiko** [binary-com/binary-bot#2008]
I want when max level martingal to stop trading.
![Capture](https://user-images.githubusercontent.com/51996252/66266846-bbf80000-e854-11e9-8381-25128e651e0c.JPG)

**Comment by Eshhh** [comment]
![image](https://user-images.githubusercontent.com/33750313/66268596-953dc780-e85c-11e9-920c-2071d5a496a6.png)




You can do something like this.

**Comment by ceakuk** [comment]
at the begining you could create a variable called TRADE_AGAIN = TRUE;
then when the martingale level  max is hit  set it to
TRADE_AGAIN = false

use AND so that ontop of your current 
if(TOTAL_PROFIT<TAKE_PROFIT)
  TRADE_AGAIN
you now have

if(TADE_AGAIN and TOTAL_PROFIT<TAKE_PROFIT)
  TRADE_AGAIN

Does it make sence ?
