### ISSUE TITLE
How can i trade binary options on binary.com?

### ISSUE THREAD

**Issue by eonuoha30** [binary-com/binary-bot#2013]
I've been trading binary options on iqoption but I can't find it on binary.com. 

What I saw on binary.com is forex, volatility index, etc

Please how can I find binary options? It usually has a 'call or put' or 'buy and sell' trade option

**Comment by saidforex26** [comment]
iqoption vs binary.com are different brokers.

**Comment by eonuoha30** [comment]
I know.

But does that mean that binary options trading is not avalaible on binary.com

**Comment by ceakuk** [comment]
are you able to find this?
Since the platform never allow you to trade volatility in EU and USA,  you would see those instruments  but not be able to click purchase.

I guess with the platform upgrade they might have even made volatility index completely hidden. From which countr yare you signing from?
![Unbenannt](https://user-images.githubusercontent.com/43122491/66386205-18c4f900-e9c2-11e9-8c44-52d11c22d726.PNG)

**Comment by eonuoha30** [comment]
Nigeria

Volatility index is 100% tradeable here.

But what I seek is binary options

**Comment by Juniorpalmer83** [comment]
Binary Options is in Forex Market, get inside "Forex" and you will operate binary options.
