### ISSUE TITLE
Differ 

### ISSUE THREAD

**Issue by alexssadro** [binary-com/binary-bot#2038]
Help me !!! I would like to select the following strategy: Robo will enter when percentage has been 0% to 4% for Different number. Is it possible to make this Robo ???
![DIFFFER](https://user-images.githubusercontent.com/56750140/67138132-946e4380-f215-11e9-8af5-6ec12a4c85e2.jpg)

**Comment by ceakuk** [comment]
@alexssadro 
I hope someone helps you with this but if in 2 days nobody  has helped you then i will do it. unfortunately right now im not motivated about it because im 100% sure it cant work. i have done it so many times before but i don't have the codes right now

from mathematical reasoning, you can't predict random numbers. even if you trade digit =0 if last 10digits hae been all zeros. these numbers can repeate themselves indefinately (random)

**Comment by alexssadro** [comment]
If you can do ... Thank you.

**Comment by FlavianoFlavio** [comment]
[Digito entrada no zero%.zip](https://github.com/binary-com/binary-bot/files/3747114/Digito.entrada.no.zero.zip)

Tente este !

**Comment by navneetsinh** [comment]
@alexssadro 
check this one, 

[Digito entrada no zero% (EDITED).zip](https://github.com/binary-com/binary-bot/files/3747843/Digito.entrada.no.zero.EDITED.zip)

this is the same file of @FlavianoFlavio , just edited and removed unnecessary blocks

**Comment by alexssadro** [comment]
> @alexssadro
> check this one,
> 
> [Digito entrada no zero% (EDITED).zip](https://github.com/binary-com/binary-bot/files/3747843/Digito.entrada.no.zero.EDITED.zip)
> 
> this is the same file of @FlavianoFlavio , just edited and removed unnecessary blocks

Very good Robo. Thanks, but can you run it according to the green option too ???? Matches ???
![Verde](https://user-images.githubusercontent.com/56750140/67210171-fdf57a00-f3ee-11e9-984d-25979f610ba7.PNG)
