### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by jose895** [binary-com/binary-bot#2057]
I want to create a bot in binary that sells the contracts that are going to be losers and that lets run those that are going to be winners, please help.

**Comment by ceakuk** [comment]
@jose895 
there is no such thing
you can use **sell at profit** to close a trade which is at profit or at loss say 10%.......80% etc or loss -10%.......-80%
but it doesnt mean they were going to win or loose. atrade can go upto 90% loss and tun around to be 100% profit

**Comment by ceakuk** [comment]
be aware that binary.com greately exaggerate this almost in a criminal way.
when trade goes your way the ruturns are so small when you close early and the returns are so large negative when it goes the opposite.

NOTE:
only works with volatility index ajd time of minutes or larger. larger is better so that individual ticks do not change that ratio significantly. say your take is at -0.5 and its  hits -0.6 (should close) but then instantly  hit -0.3 (should not close). the trade will close at undesirable -0.3. so use larger minutes like 2,3, 5,10 etc
![Unbenannt](https://user-images.githubusercontent.com/43122491/67851105-fa0dda00-fb09-11e9-9b33-f3e08fcd2b86.PNG)
[binary-bot(20).zip](https://github.com/binary-com/binary-bot/files/3788292/binary-bot.20.zip)

**Comment by jose895** [comment]
apparently only works with investments of $ 1 probe with other amounts and does not work well

**Comment by jose895** [comment]
apparently it only works with investments of $ 1 try with other amounts and it doesn't work well, I don't understand why

**Comment by jose895** [comment]
apparently it only works with investments of $ 1 try with other amounts and it doesn't work well, I don't understand why
