### ISSUE TITLE
set the amount of martingale steps. For Match or Differ

### ISSUE THREAD

**Issue by chibuenyim** [binary-com/binary-bot#2067]
Hello,
Please, I need help to set the number of martingale steps.
Example
step   amount
1         1
2         3
3         5
4         9
5         1 or restart

After $25 loss stop trade, After $30 gain stop trade.

[Set precise martingale steps.zip](https://github.com/binary-com/binary-bot/files/3787557/Set.precise.martingale.steps.zip)

**Comment by binary-ex-machina** [comment]
you can work with a stake list, it will reset every 4 steps to the initial value on the list. Since you are using Digit Match, your stop loss needs to be a lot higher then 25, as well you need to lower your stakes, you can lose 50 times in a row on digit match

![image](https://user-images.githubusercontent.com/34610787/68075958-a3183700-fd8d-11e9-8f0e-037527ebe5d1.png)
