### ISSUE TITLE
Help me with a piece of code

### ISSUE THREAD

**Issue by lxxneonxxl** [binary-com/binary-bot#2076]
I need to real deal bot opened after a certain number of cons. sorry about my English

**Comment by binary-ex-machina** [comment]
Explain better what is cons. Real deal bot is what? a bot that works? a bot that never lose and can be profitable and making money while you sleep? (this is a sarcasm, of course you know that this kind of bot doesn't exist)

**Comment by lxxneonxxl** [comment]
I mean that the robot does not buy the contract immediately according to the rules of the strategy, but first it counts the number of lost contracts and after a certain series already buys for the present ...
The point is that we are as if waiting for a certain drawdown and only then buy. You can use 2 bots, one on a virtual account, the other on a real account with one strategy .. when on a virtual one, for example, 6 losses in a row, go to the real one and trade on it, but this is terribly inconvenient ... once again, I apologize for using my English translator

**Comment by binary-ex-machina** [comment]
You can have 2 bots interacting with each other. Have a bot running on demo account, waiting it to lose 6 times then play on real will not make the results better, since you can still lose 4-6 times more on real. Also you would have to wait a lot of time for that to happen, will have the same risk and the strategy will fail again.

Try to start using martingale after the 3rd loss, it will be better

**Comment by lxxneonxxl** [comment]
you can of course use 2 robots, but I need the logic of building this algorithm in one robot.. thanks for the help

**Comment by alanvito1** [comment]
Try it guys!

https://github.com/alanvito1/superfree-binary-bot

Best Regards and blesses!
