### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by Tebu1429** [binary-com/binary-bot#2077]
Hello ,good people .hope y'all are Ohk ,

Is there any profitable bot that you can share ?

Some of us trade manually cos we can't put our strategy on a bot .even if we try explain ,it's like we not making any sense .

So could you please share just a simple bot that can make at least $5 an hour .
Please and thank you

**Comment by binary-ex-machina** [comment]
@Tebu1429 a bot to make $5 every hour? sure here is one

![image](https://user-images.githubusercontent.com/34610787/68124268-b6421880-feed-11e9-8473-5f3a02fd9b90.png)

How to use it

Open the graph **[here](https://tradingview.binary.com/v1.3.12/main.html)** the market to R_100 and timeframe to 1min
![image](https://user-images.githubusercontent.com/34610787/68124151-695e4200-feed-11e9-90b6-177160c28087.png)

Put the indicator Hull MA with period of 50. When the candle cross over the HMA, you hit play. Wait for the bot to reach $5, it will stop automatically. Repeat the process every hour. Have at least $400 as balance and you are good to go. At some point you will need $800 as balance and later $1600. In some days or maybe a week you will need $3200 to keep making $5 per hour and recover from the losses. 

the more you play, higher are the chances of you entering in a bad market moment and lose more, so your analysis of the entry point is very important

the arrows represent where you need to place the trades (at the end of the candle)
![image](https://user-images.githubusercontent.com/34610787/68124497-50a25c00-feee-11e9-9ce8-0bdc068c09ed.png)

If you want to automate this strategy, you will always lose, because the bot will enter on all possible entries, that will make you lose everything. I recommend doing this for 2-3 hours a day, making $15 per day and stop. Come back next day and do again.

**Comment by Tebu1429** [comment]
@Binary ex

Thank you!

**Comment by alanvito1** [comment]
Hello,
Look here.
https://github.com/alanvito1/superfree-binary-bot
