### ISSUE TITLE
Somebody help me ??

### ISSUE THREAD

**Issue by alansilva1** [binary-com/binary-bot#2102]
By the image, does anyone know how does this robot ???     
![BOTTTT](https://user-images.githubusercontent.com/36489138/68437727-81112100-01a0-11ea-9ee6-b024c79ea6e7.jpeg)

**Comment by binary-ex-machina** [comment]
Judging by the image, it places only put, it trades with very small duration, 3-5 ticks, 100 Index, sell at market on loss (looks like 70% of the profit at one trade). It's applying martingale on factor 2,06. Analyzing the entry ticks, it's following the trend direction most of the time. Its using a demo account (reference number ending in 8). On trade result is missing, that can happen when the user hit stops and hit play again fast (probably because if changed some settings. It's reducing the base stake to a lower number when a loss occur and then it doesn't reset. 

Result: very confusing, probably starting and stopping the bot and with a money management that has more complex management of the stake, impossible to get it form just 11 trades showing in a cut image

**Comment by alanvito1** [comment]
There are a lot of robots for your pleasure.

https://github.com/alanvito1/superfree-binary-bot
