### ISSUE TITLE
Help! - How can I use the option is candle black?

### ISSUE THREAD

**Issue by unzer** [binary-com/binary-bot#214]
Hello!
Someone could help me to develop a bot that use the option "is candle black"?
I am trying to run a bot that analyse the last candle and purchase in the same direcion of then.
Best regards
Unzer
Can be in the 1 minute time frame or other.

**Comment by Fruitfella** [comment]
@unzer "is candle black" (actually it should be red lol) is bearish candle.
so if u want to purchase FALL when current candle is down and vice versa. make it like this

_if_ [is candle black? ][in candle list get# from end [] ]
_do_ [Purchase Fall]
_else_ [Purchase Rise]

like that. sorry i cant give u pics or exmple right now :p

**Comment by unzer** [comment]
Hi @Fruitfella 
Tks a lot for the help.
I will try it at home and return.
Regards
Unzer

**Comment by unzer** [comment]
Hi @Fruitfella ,
Take a look in my script, probably I did something wrong... :o(
![is_candle_black](https://cloud.githubusercontent.com/assets/26580460/25944106/7d6a05d6-3618-11e7-9725-14759399e613.jpg)

**Comment by Fruitfella** [comment]
change that [list] with [candle list] from Binary>Tick Analysis>Advance.
or u can change that [in list [] get # from end [] ] with [in candle list get# from end [] ] from the same place.

**Comment by unzer** [comment]
Hi @Fruitfella ,
Tks so much for the help!!! You are so good!
How can I learn more about this? Are there any course? Are there any tutorial? Or a specific community?
I know that I am a begginer, but I would like to be an expert advisor!

**Comment by Fruitfella** [comment]
hi @unzer,
actually im a beginner too, but i find it easy to build my own bot in bot.binary.com.
i just use some logic and a dictionary (my english is terrible). theres also many blocks that i dont know how to use it yet.
i still cant find a good strategy though, i keep building bots with different strategies that i got from somewhere, but still not satisfied with the result. thats how i come to know how to use some blocks and get better at that.
theres no course and tutorial yet as far as know. as for community, i also hope theres one that we could ask and share some knowledges about binary bot. some people that came here seems never return again after their problem solved (or not). 
if u r experienced or have some knowledge about online community, why dont u make one? ill join for sure, and i think theres many others.
about building bot, u should just try those blocks that u havent know how to use yet and dont worry about making some mistakes and errors (i did a lot). since u can ask here when u get errors.

btw, im glad i can be a help.

**Comment by unzer** [comment]
Hi @Fruitfella !
Believe, I am a really begginer...
What I am trying to do is if the last one minute candle fall, purchase fall... if the last one minute candle rise, purchase rise.... So, in my strategy, I always analayse the last candle and bid in the same direction...
![good-profit](https://cloud.githubusercontent.com/assets/26580460/25980579/dd95f59a-36a5-11e7-9912-e6bdfd60fc01.jpg)
The function "is candle black" occurered in the recent candle, but what I want is analyse the last candle closed.
Do you know if is it easy or possible?

**Comment by Fruitfella** [comment]
@unzer ive made that kind of bot before, its good on trending market but sucks on flat or choppy. its not that bad if u have big capital and use martingale management. but with small capital, the martingale burn all ur money out.
back to topic, yes, its possible.
see that empty hole on **[**in candle list get# from end **[**_this empty hole_**] ]** ?
fill it with 2 for prev candle and 3 for candle before it and so on. leave it empty or fill it with 1 for the current candle.

i think u might want to do purchase right when the new candle is open, u can use this block for that purpose 
[is candle new.zip](https://github.com/binary-com/binary-bot/files/995004/is.candle.new.zip)

**Comment by unzer** [comment]
Hi @Fruitfella 
Perfect, lets continuos there...
