### ISSUE TITLE
Uncommon 2019 profit bot

### ISSUE THREAD

**Issue by ABDULAHI24HRS** [binary-com/binary-bot#2180]
I need block if lose,  continue trade immaterially,  if profit scan again

**Comment by ceakuk** [comment]
@ABDULAHI24HRS your assumption for trading immediate you loose is that if you loose then you have higher chance of winning the next. that assumption is 1,000,000% false

**Comment by eonuoha30** [comment]
Lol....!!!

The headline got my attention.

But the logic content is trash.

A lot of persons are yet to understand the logic behind 'random or pseudorandom numbers'

**Comment by ABDULAHI24HRS** [comment]
> Lol....!!!
> 
> The headline got my attention.
> 
> But the logic content is trash.
> 
> A lot of persons are yet to understand the logic behind 'random or pseudorandom numbers'

You really funny,  have add it to my bot and is now working perfect,  instead of you ask why I want to add it,  you keep shooting

**Comment by Eshhh** [comment]
This idea could work if you are looking to avoid the same last digits occurring consecutively, but the problem is, once the bot opens and closes a loosing trade it does not immediately take a trade on the next tick, instead it skips a tick or two which makes it possible for the same digit to occur again. But its a good idea though.
