### ISSUE TITLE
CCI Binary BOT

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2199]
Kindly help me preparing Binary bot withe below Strategy.

CCI 10 ticks avg

CCI Above 100 Call and above 4 SMA BUY Call

CCI Below -100 Below 4 SAM Buy PUT

SMA 10 ticks avg 1

SMA 10 ticks avg 4

Need smart martingale for this strategy

**Comment by binary-ex-machina** [comment]
A lot of complexity here and lack of information

First thing is that for a good measure, CCI needs candles (Open, High, Close and Low values) to determine the signal. 

CCI 10 ticks avg - this is not possible because of the ticks, also average of the last 10 periods, really?

CCI above 100 CALL and above 4 SMA BUY CALL? what that means? it will purchase 2 times? it will take the signal of the CCI and the confirm with SMA?  what is above SMA? the same problem for the inverted signal

You want a SMA 10 ticks average from how much values? all of them? like 1000 ticks?

Smart martingale is another issue, how many smart martingales are out there? a hundred at least.

If i can send you a tip on how to ask for help, here it is

CALL signal - candles: CCI > 100 and price above SMA4
PUT signal - candles: CCI < -100 and price below SMA4
Money management: Martingale
Duration: 1min

**Comment by muroyal** [comment]
Is it possible to convert candle in 15 seconds ?

**Comment by binary-ex-machina** [comment]
You can do by analysing the ticks and making a complex analysis to convert them to 15 seconds candles. It's not worth it

**Comment by muroyal** [comment]
Thanks for your suggestions ...
