### ISSUE TITLE
BLOCK 3: watch and sell contract

### ISSUE THREAD

**Issue by eonuoha30** [binary-com/binary-bot#2255]
Can BLOCK 3:watch and sell contract be used in DIGITS trading?

If Yes, how ?

If No, why?

Thanks for your response

**Comment by gayya** [comment]
Answer is simple,in digit trading all contract less than 15 Seconds.any kind of trade not offer for early sale less than 15 seconds.Other thing is digits changing cannot calculate contract early value.it is predefined you loose as certain criteria fulfilled.

**Comment by ceakuk** [comment]
@eonuoha30 @gayya 
actually thats not the right answer because i can also trade digits after every 1 hour.
the answer lies in understanding what is digits?
i predict that after a given time, the last digit will be over/under  mat/differ, odd/even
say i trade after ever 5 ticks, how does closing after 2 ticks tell me if the trade  is in my direction(close wining) or  not in my direction(close loosing)

digits have no direction. so you can not say compared to last digit, the new digit is close to my prediction (continuity)
