### ISSUE TITLE
I need help with this strategy

### ISSUE THREAD

**Issue by Arionfox** [binary-com/binary-bot#2259]
I would like a robot that works with the return of RSI analysing candles!

Explaining better:

When the RSI crosses the Level 70 from bottom to top it will do nothing, however, when crossing the Level from Top to Bottom making a return (leaving overbought zone), it will open a fall operation, the same thing for level 30.

Can someone help me?

**Comment by xremmy** [comment]
![Git help1](https://user-images.githubusercontent.com/25975068/71315332-b4f78b80-245a-11ea-952f-bc23dba87f13.jpg)
Enjoy

**Comment by ceakuk** [comment]
@Arionfox @xremmy 
please understand the method before coding it.
in a normal market like forex, the buyers against sellers drive the market. so we can say overbought or oversold because we can see when they are getting exhausted. of course  the big boys/banks or market makers  periodically spoil that party.

with synthetic indicies like volatility index there is no such a thing as overbought/oversold. the algorithm is always at liberty to rise or fall endlessly
