### ISSUE TITLE
How to create a serial number or something like this?

### ISSUE THREAD

**Issue by Wevertonh** [binary-com/binary-bot#2262]
I want to create a serial number to my bot, so only people that i give the bot can use it, if the person tries to give to someone else it won't work, it is possible?

**Comment by anton-binary** [comment]
Hi @Wevertonh ,

That's not possible with Binary Bot. You might want to explore binary API instead. With API you can create a trading robot protected by the password or serial number.

https://developers.binary.com/

**Comment by ceakuk** [comment]
@anton-binary 
its a shame you don't have that. binary.com has been there since 1990 or there about. isn't it among the first things they should have implemented. most traders don't know how to create bot and those who know how to create bot would  either want to sell it.

if i sell good bot for 30$ that makes you 3000$ then i must be stupid. what stops you from selling my bot on top of profiting with it?

im so disappointed by you people at binary.com for not seeing the need  for that. i suspect its intentional

**Comment by saidforex26** [comment]
making a serial number and the bot's expiration time can be applied to the block, but the weakness can be randomized to those who know how to shuffle it. I think bot.binary has provided a webhook, maybe by sending a serial number from another website and applying it in the bot as a new variable it could.

**Comment by ForexJapao** [comment]
@saidforex26 Voc~e poderia mostrar uma forma simples de colocar tempo de expiração no bot ?

**Comment by ABDULAHI24HRS** [comment]
Where is the bot let me help you

**Comment by ForexJapao** [comment]
[Accura digit auto trader.zip](https://github.com/binary-com/binary-bot/files/4006415/Accura.digit.auto.trader.zip)

**Comment by ForexJapao** [comment]
Este acima !
