### ISSUE TITLE
Dont trust binary.com....

### ISSUE THREAD

**Issue by laveni** [binary-com/binary-bot#2277]
Just mt4 recommended

**Comment by hotmatrixx** [comment]
binary.com uses the MT4 platform.
also, if you pull up the MT5 and the binary.com feeds, they are well synchronized.
binary.com is a registered broker everywhere except basically the US where all BO are banned.

They are as legit as it gets.

Stay away from Synthetic options. If you lost your money, I believe it's because

- Your system isn't as good as you thought
- your bot was bugged
- you didn't trust your system.

**Comment by binary-ex-machina** [comment]
@laveni another post blaming the broker and the instrument. OMG, when these guys will just go back to the cave and stop blaming others for their own losses. You can't connect on a binary forex server with MT4 software.
