### ISSUE TITLE
Help! How to make a function block?

### ISSUE THREAD

**Issue by DepressiveCloud** [binary-com/binary-bot#2297]
Hello everyone, i'm a new in using a binary bot platform, and i have a question.
How to make a function block? I was seeing in other bots that they have a single block with various functions, for example the functions available by Fruit Fellas.
How do I make a block like that, only with my modifications?

**Comment by hotmatrixx** [comment]
happy to help. I gotta go out for a couple of hours then I'll be back to show you a BASIC function block or 2.

**Comment by hotmatrixx** [comment]
functions can serve 2 major purposes
1. they can act as "Remarks" helping to break your code up into smaller chunks - making reading your code and debugging much simpler
2. You can use them to reduce / tidy up your code. If you have an identical 'chunk' of code that you repeat then you make them a function that you 'call' instead of repeating the same lines over and over.
Here is an example from one of my bots. Don't worry about what I'm doing, just focus on how it works. Basically, this is an example of #1: I'm breaking big lchunks of code into smaller groups of code to make it easier and more manageable to keep track

This is my 4th block.
I've opened up my first function 'pausebot on win' 
so that you can see there is a lot going on inside that function. The rest (pause on lose, set stake, notification functions) are closed or 'collapsed' to make it wasier to navigate around my bot. Each of those functions has a lot going on inside it,k just as the pause on win one does.

as you can see, each function is 'called' from my 4th (rusult) block. once it's finished, it returns to the point it was called from and carries on.

I've done this to make debugging and following my code simpler, as without those functions, my 4th block would have around 150 code snippets inside it!!!


The other thing functions are good for is repeating the same lines of code many times, like this:
now the code makes no sense!! its just for the example!!!

the point it that the function can be called from many places, which saves me from rewriting lots and lots of lines of code over and over again.

![Capture](https://user-images.githubusercontent.com/49715381/71794023-7a216480-30a4-11ea-8ebc-58b7a653278b.PNG)


![Capture](https://user-images.githubusercontent.com/49715381/71793830-72ad8b80-30a3-11ea-97e7-24e17afac8aa.PNG)

**Comment by hotmatrixx** [comment]
further there is one other type of function which requires a 'return'

you'll notice I use it to set the Stake in the trade definition. it makes some calculation, then returns a value that is plugged straight into the code at the point that the funciton is called.

hope that helps a bit.
![Capture](https://user-images.githubusercontent.com/49715381/71794215-64f90580-30a5-11ea-8de1-9d718f515bc6.PNG)

**Comment by DepressiveCloud** [comment]
I understand this part.
But, let's start with something basic so I can see the full picture. Example:
After reading what you told me, I tried to do the following function block. but every time I try to start the bot with it, it keeps giving me an error saying "Value must be a positive number".
![image](https://user-images.githubusercontent.com/59505639/71811032-7f55c380-3052-11ea-971b-cdfc9731dd71.png)

**Comment by hotmatrixx** [comment]
I don't speak ?french? so this is an easy one:

in the "runonce" you are telling the fucntion to use those variables, then you are defining them inside the function

the problem is that they need to be defined before they are first called, calling them at this point they have no value, they have a value of "null" on their first run, so you'd have to define them all first, before calling them into the function

**Comment by DepressiveCloud** [comment]
Could you help me organize this in a functional way?
The language is Portuguese but in English would be:
Value I will get:
Earnings Goal:
As far as I can lose:
Value after winning:

These are the variables that I put in the function, help me make them work please.

**Comment by DepressiveCloud** [comment]
Closing this topic because my question has already been resolved, grateful.

**Comment by DepressiveCloud** [comment]
Closing this topic because my question has already been resolved, grateful.
