### ISSUE TITLE
Need Most popular indicator ADX. 

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2304]
Can anyone provide me ADX indicator.

**Comment by hotmatrixx** [comment]
Although I'm happy to help people overcome programming challenges in their code, and the bots' limitations, coding from scratch for someone isn't in my interests.

The ADX is a complex indicator, using SMA's, and smoothed SMA's averaged out over time. Although it's not a bad indicator, it's not one I'd use anyway.

The indicator doesn't exsist in the bot naturally, you'd have to build it using an array or 3.

If you'd made an honest attempt at it, I might be interested in helping you bugfix it if it didn't work - but I'm not doing it all for you.

For reference, here are the calculations that you need.:

> 

 The Formulas for the Average Directional Index
(ADX) Indicator are

The ADX requires a sequence of calculations due to the multiple lines in the indicator.

+DI=(Smoothed +DMATR )×100-DI=(Smoothed -DMATR )×100DX=(∣+DI−-DI∣∣+DI+-DI∣)×100ADX=(Prior ADX×13)+Current ADX14where:+DM (Directional Movement)=Current High−PHPH=Previous High-DM=Previous Low−Current LowSmoothed +/-DM=∑t=114DM−(∑t=114DM14)+CDMCDM=Current DMATR=Average True Range\begin{aligned} &\text{+DI} = \left ( \frac{ \text{Smoothed +DM} }{ \text{ATR } } \right ) \times 100 \\ &\text{-DI} = \left ( \frac{ \text{Smoothed -DM} }{ \text{ATR } } \right ) \times 100 \\ &\text{DX} = \left ( \frac{ \mid \text{+DI} - \text{-DI} \mid }{ \mid \text{+DI} + \text{-DI} \mid } \right ) \times 100 \\ &\text{ADX} = \frac{ ( \text{Prior ADX} \times 13 ) + \text{Current ADX} }{ 14 } \\ &\textbf{where:}\\ &\text{+DM (Directional Movement)} = \text{Current High} - \text{PH} \\ &\text{PH} = \text{Previous High} \\ &\text{-DM} = \text{Previous Low} - \text{Current Low} \\ &\text{Smoothed +/-DM} = \textstyle{ \sum_{t=1}^{14} \text{DM} - \left ( \frac{ \sum_{t=1}^{14} \text{DM} }{ 14 } \right ) + \text{CDM} } \\ &\text{CDM} = \text{Current DM} \\ &\text{ATR} = \text{Average True Range} \\ \end{aligned}​+DI=(ATR 
Smoothed +DM​)×100-DI=(ATR 
Smoothed -DM​)×100DX=(∣+DI+-DI∣
∣+DI−-DI∣​)×100ADX=14
(Prior ADX×13)+Current ADX​where:+DM (Directional Movement)=Current High−PHPH=Previous High-DM=Previous Low−Current LowSmoothed +/-DM=∑t=114​DM−(14

∑t=114​DM​)+CDMCDM=Current DMATR=Average True Range​﻿
Calculating the Average Directional Movement Index (ADX)

    Calculate +DM, -DM, and True Range (TR) for each period. 14 periods are typically used.
    +DM = Current High - Previous High.
    -DM = Previous Low - Current Low.
    Use +DM when Current High - Previous High > Previous Low - Current Low. Use -DM when Previous Low - Current Low > Current High - Previous High.
    TR is the greater of the Current High - Current Low, Current High - Previous Close, or Current Low - Previous Close.
    Smooth the 14-period averages of +DM, -DM, and TR. The TR formula is below. Insert the -DM and +DM values to calculate the smoothed averages of those.
    First 14TR = Sum of first 14 TR readings.
    Next 14TR value = First 14TR - (Prior 14TR/14) + Current TR
    Next, divide the smoothed +DM value by the smoothed TR value to get +DI. Multiply by 100.
    Divide the smoothed -DM value by the smoothed TR value to get-DI. Multiply by 100.
    The Directional Movement Index (DX) is +DI minus -DI, divided by the sum of +DI and -DI (all absolute values). Multiply by 100.
    To get the ADX, continue to calculate DX values for at least 14 periods. Then, smoothe the results to get ADX
    First ADX = sum 14 periods of DX / 14
    After that, ADX = ((Prior ADX * 13) + Current DX) /14

**Comment by muroyal** [comment]
Hello @hotmatrixx 

I have got ADX indicator from one of our forum person, But i am unable to load it. kindly have look into it it may help you .. I the blocks are not opening in existing bot. 

[@indikator.adx.zip](https://github.com/binary-com/binary-bot/files/4028238/%40indikator.adx.zip)
