### ISSUE TITLE
very nice strategy, tested,

### ISSUE THREAD

**Issue by sohailsb** [binary-com/binary-bot#2305]
Difgit Differ Strategy, for Even digits
tick1= 0 Tick2= 0 Differ=0
tick1=2 tick2=2    Differ=2
tick1=4 tick2=4   Differ=4
Tick1=6 Tick2= 6 Differ=6
Tick1=8 Tick2=8 Differ=8
can any body develope bot?

**Comment by ZDEGLET** [comment]
ПРОВЕРЯЛ СТРАТЕГИЮ ВРУЧНУЮ?

**Comment by hotmatrixx** [comment]
This coding platform isn't capable of implementing this strategy; it places the prediction FIRST, and then that is fixed until it trades.

You can't wait for ticks, place prediction then buy instantly. (there is a workaround that kind of lets you do that but it only works in minutes, not ticks)

**Comment by Kosta92** [comment]
Gambling by trading Digits Differ is the easiest way to lose all of your money, because this trade type doesn't earn you almost nothing with small stakes, but it sure as hell can wipe your account really quick. As with any bot that deals with digits, there can be no strategy, no matter how smart you think you are. Digits are completely random, and any "strategy" one might think is good, is simply based on pure luck and nothing more.

Speaking of your strategy, it's been already talked about and I recommend against it. Here is the link to an older post if you want to check it out: [https://github.com/binary-com/binary-bot/issues/1443](url)

**Comment by sohailsb** [comment]
i developed my self and i got good result
one thing always remember, nothing is impossible,
Good bye

**Comment by kjsanjeewa** [comment]
Set the Last Digit Prediction 0 and Price Bar count the  - - - - -.0  -  then Open Purchase Digit Differs Order with the this same setting.

After 2 trades profit chage automatically LDP(Last Digit Prediction) 0 to 1 and after two trade change the LDP 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0  rotation numbers every profit two trades like this.

Martingle add the 11.1
Take Profit, Stop Loss
![Screenshot 2020-11-27 21 10 17](https://user-images.githubusercontent.com/74783297/100549143-34aaee80-3297-11eb-830a-af5e23c19ce3.png)

**Comment by arehmanyounis** [comment]
> i developed my self and i got good result one thing always remember, nothing is impossible, Good bye

A.A how are you sohail sb please email me this above strategy bot i shall be very thankful to you

arehmanyounis@gmail.com
