### ISSUE TITLE
Hourly 1$ enough :) 

### ISSUE THREAD

**Issue by muroyal** [binary-com/binary-bot#2351]
Sorry let me explain details. @hotmatrixx 

My bot hourly target is 1$ right now in real account it is working fine. It won't take more than 5 runs to get 1$ hourly. Some time the trades are extending more runs for 1$ Due to martigle factor what is use for safety. hence i would like to restrict my houry runs to 20 as well within 20 runs my 1$ has achieve or not it should stop and make my hourly profit to total profit+1$ and stop for 1 hour.

I am facing issue how to process if my balance is went to - negative how to add +1$ when my profit stop with negative value.  the bot should recover 1$ per hour even after my negative balance.. 

@binary-ex-machina
 
I have prepared logic as per my experience in bot development can you provide a better solution for it ?

![image](https://user-images.githubusercontent.com/32416314/72856195-d6f55f80-3cdf-11ea-8165-0362aa187237.png)

Thanks
evaroyal84@gmail.com

**Comment by hotmatrixx** [comment]
so I'm about to go out but I had a quick look at this;
an immediate issue that I see is using that yellow timeing block; the entire bot will stop and won't place any trades at all while it is counting that 5000 seconds (*also, there are 3600 seconds in an hour)

You can set that as a variable, and what you can do is take a time using the epoch, then later subtract taht from the epoch to find how many seconds have expired

ie "set StartTime" to [Epoch]
then later when you win/lose:
Set "NumberOfSecondsSinceIStarted" to [Epoch] - "StartTime"

You could use that information, (3600 - "NumberOfSecondsSinceIStarted") instead of blindly using a fixed number of 3600 or 5000

Once you've won your first $1, [TotalProfit] will always be more than HourlyProfit, so that logic is also faulty.

Sorry, GTG I might take another look at this later.

**Comment by hotmatrixx** [comment]
also, yeas this explanation is SO GOOD
thanks, now that I understand what you're trying to do, I might be able to help you.

**Comment by hotmatrixx** [comment]
your script is really complex. I'll write up somethign that will do waht you want pretty easily when I get back, if I remember to

**Comment by hotmatrixx** [comment]
[muroyal 1dollarmartingale.zip](https://github.com/binary-com/binary-bot/files/4101208/muroyal.1dollarmartingale.zip)
![Capture](https://user-images.githubusercontent.com/49715381/72955980-f5a04700-3e02-11ea-8f4f-043258f8caab.PNG)

**Comment by hotmatrixx** [comment]
oh I forgot to add the 20 runs thing.
um. you'll figure it out?

**Comment by muroyal** [comment]
@hotmatrixx  I am facing **issue periods longer than data length** dont know where i have missed data length. 

It is winding up my profits while doing martigle. Kindly provide me your email id.. I would like to send my bot to you Kindly help me on it.
