### ISSUE TITLE
How can I count the colors of the last 5 candles,?

### ISSUE THREAD

**Issue by ForexJapao** [binary-com/binary-bot#2374]
How can I count the colors of the last 5 candles, and enter the sixth candle according to the color that came out in the greatest quantity? Example; Green. Green, Red, Green, Red = Call

Can someone help me? I'm trying this way but the bot is counting the same candle color several times.
![image](https://user-images.githubusercontent.com/56320282/73229390-6d9aa400-4158-11ea-9d03-6ee1794d6598.png)

**Comment by hotmatrixx** [comment]
Hi, I really want to help you with this because 
1. you asked in an easy to understand way and;
2. you actually tried to code it beofre coming here and asking someone to do it for you.

Here's youre answers;
First "Candle #1" is the current candle, so you want cantles 2 - to - 6.
The main reason this doesn't work, is that you need to count the last 5 candles, and you're continually counting the same candle '1'. What you want is a loop counter to process the same operation many times while changing the count variable - pretty simple to do.

I wrote one that does somethign similar to yours, but I made mine a 'single' counter that can process positive numbers as 'more greens', negative numbers as 'more reds', and zero as 'evenly spread'. 

My loop uses a defined variable called 'Ticker' that is defined in the 'run once' block, so you can change that variable there. Importantly my loop uses candles from #2 through to "Ticker + 1" so that it is reading previous candles' values, not the current candle.

I moved all this into the #2 block as it doesn't need to be in the 'every tick block' and so also won't keep counting while a trade is being placed - which it would do needlessly if it was in the 'on every tick' block.

Here is the code block

[ForexJapao - red_green counter.zip](https://github.com/binary-com/binary-bot/files/4120489/ForexJapao.-.red_green.counter.zip)


Here;


![Capture](https://user-images.githubusercontent.com/49715381/73232748-290b1900-41e9-11ea-9032-dea49d81540f.PNG)

**Comment by hotmatrixx** [comment]
I just realized after looking at the blocks closely, that black=red, so you may wish to reverse those blocks in my bot as i set them for black=green.

**Comment by ForexJapao** [comment]
@hotmatrixx  Thank you very much friend, I will develop here ...

**Comment by hotmatrixx** [comment]
I'm awesome. This was a fun little challenge;
ExMachina is still the boss diddy tho.

[atrloop(1).zip](https://github.com/binary-com/binary-bot/files/4125940/atrloop.1.zip)


![Capture](https://user-images.githubusercontent.com/49715381/73323867-bca61d80-42ad-11ea-8f8a-bee3f1f4ac67.PNG)

**Comment by hotmatrixx** [comment]
sorry comment onthe wrong thread...
deleted/updated.

and you're welcome @ForexJapao

**Comment by ForexJapao** [comment]
@hotmatrixx I could not understand the way you explained, in fact I need to count the last 5 candles and open the sixth candle according to the color that came out the most.
