### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by alansilva1** [binary-com/binary-bot#2380]
Please help me !!! I would like to add this strategy to the robot. After 5 odd numbers in a row, the bot goes even. If you win, come back to review again. If you lose, enter ZigZag mode.

**Comment by hotmatrixx** [comment]
That's an incredbily simple thing to make up. You've been contributing to theis github for the last 4 months, yet it appears you haven't learned how to make a basic bot?

How about you make an attempt at writing it, post that so that we can see an effort being made, then I can help you fill in the bits you don't understand?

Best way to learn is by trying something first.

**Comment by alansilva1** [comment]
> That's an incredbily simple thing to make up. You've been contributing to theis github for the last 4 months, yet it appears you haven't learned how to make a basic bot?
> 
> How about you make an attempt at writing it, post that so that we can see an effort being made, then I can help you fill in the bits you don't understand?
> 
> Best way to learn is by trying something first.

Friend, put images of the block there, which I do myself.

**Comment by hotmatrixx** [comment]
so you don't "do" zigzag mode, it's an indicator that isn't readily available on the bot.
This is the basic counter. instead of zgzag i made a super simple martingale. it all works perfectly. don't go broke!
![Capture](https://user-images.githubusercontent.com/49715381/73360295-7a112f00-4307-11ea-8043-48e68896c210.PNG)

I don't understand how zigzag could possibly help in a randomized, synthetic market where you care abou tthe last digit, not the trend direction, so thus the martingale instead.

Have fun.
oh. I uploaded the xml to my repository. But I think you should definitly cop this from the image, it will help you a LOT with learning how to do this.

REMEMBER to also copy the stuff under "**Run Once At Start**" and "**Define Trade Options**"

**Comment by hotmatrixx** [comment]
just so you know, I've been running it for about 15 minutes and it risked $1700 before it recovered it.

**Comment by alansilva1** [comment]
Thank you very much ... I made Robo now

**Comment by hotmatrixx** [comment]
> 
> 
> Thank you very much ... I made Robo now

good. working as expected? does it help you understand how bots are put together a bit better?
