### ISSUE TITLE
U WONT MAKE ANY MONEY WITH BOTS

### ISSUE THREAD

**Issue by willyzkibe** [binary-com/binary-bot#2381]
its time you share your manual strategies  research shows only 0.005% succeed with bot stop living in fantasy world binary manipulates your trades with bot thats why demo will work live wont work coz they manipulate price weve created polls on telegram facebook and instagram over 99.8 voted bots dont work

**Comment by ZDEGLET** [comment]
24\7 работать не будут, а если сделать 1-3% от суммы в день то можно:)

**Comment by hotmatrixx** [comment]
> 
> 
> its time you share your manual strategies research shows only 0.005% succeed with bot stop living in fantasy world binary manipulates your trades with bot thats why demo will work live wont work coz they manipulate price weve created polls on telegram facebook and instagram over 99.8 voted bots dont work

Correct. Less than %1 make a successful living on the stock market in general, despite what the marketing says.

Less than 30% of them are Technical / Day Traders.

Less than 10% of the technical group are _profitable_ algo (bot) traders.

HOWEVER. There are profitable algo traders out there. I'm one of them. I currently don't make enough for a full time living from it, but I have been working daily on learning this particular trading system for around 3 years, and dicovered bot.binary.com a little over a year ago.

I'm currently writing 3 bots side by side in their final stages of development. I just reset one of them today, but the other two - running on VTR accounts during the final stages of testing
![Capture](https://user-images.githubusercontent.com/49715381/73345273-b08b8180-42e8-11ea-984c-f667058b0d93.PNG)
![Capture](https://user-images.githubusercontent.com/49715381/73345365-d0bb4080-42e8-11ea-8562-ef1e8132a2a3.PNG)

My real accounts are up around $30 this week. not enough to make a living. yet.

**Comment by hotmatrixx** [comment]
notice these are up over hundreds of trades, not 20 'just to look good'.

They also have more losses than wins and are still in steady profit.

**Comment by ZDEGLET** [comment]
@hotmatrixx 
Ты делаешь реинвест для получения большей прибыли?
если что пиши на почту c пометой "hotmatrixx" чтоб я не перепутал. мне очень много пишут по форексу  zdeglet@gmail.com

**Comment by hotmatrixx** [comment]
Yes, I'm reinvesting it, then bumping the stakes each week until I can afford to live off it.
That's the plan, we will see if it works or if I lose everything, very shortly.

**Comment by phoenix-pk** [comment]
I don't think there would be any issue if the Broker is a reliable one. You will notice if anything is up by simply checking the ticks data/historical data that each Broker provides. 

Any strategy, esp. with Binary options has 50% chance of win. If you intend to do 10 trades a day, some days, you will have 9 losses, others you will have 2. So it further plays with your win ratio and your brain. Options are statistics. I had a month on real account where my account saw 500% growth in one month. Then the same account wiped out the next month.

Why? Because I got confident or you can say greedy and went with bigger stakes after losses. Combine that with its psychological effect and my account was blown. This is where BOTs comes in and I intend to test it out now. 

First so I don't miss any chances while I am away from computer. Secondly so the psychological aspect is removed. The bot will do what you tell it to do. It does not have a brain which will impair its judgement when there are consecutive losses.

**Comment by ZDEGLET** [comment]
@hotmatrixx 
спасибо за ответ. удачи тебе и профита.

**Comment by hotmatrixx** [comment]
> 
> 
> I don't think there would be any issue if the Broker is a reliable one. You will notice if anything is up by simply checking the ticks data/historical data that each Broker provides.
> 
> Any strategy, esp. with Binary options has 50% chance of win. If you intend to do 10 trades a day, some days, you will have 9 losses, others you will have 2. So it further plays with your win ratio and your brain. Options are statistics. I had a month on real account where my account saw 500% growth in one month. Then the same account wiped out the next month.
> 
> Why? Because I got confident or you can say greedy and went with bigger stakes after losses. Combine that with its psychological effect and my account was blown. This is where BOTs comes in and I intend to test it out now.
> 
> First so I don't miss any chances while I am away from computer. Secondly so the psychological aspect is removed. The bot will do what you tell it to do. It does not have a brain which will impair its judgement when there are consecutive losses.

it sounds like you've got your head in the right place, and you've come in with a good attitude. I'm pleased to see you here. Your answer here was balanced and neutral, and your request on coding started with you learning to code, rather than asking for us to code for you.

I've gotta start making these coding tutorials, I think. I'll start posting links to them when I start making em, but I'll start soon.

_Be aware that I think the OP was trolling for working bots for free - he's demanding that we post working bots in the forum for him to check out as proof._

**Comment by hotmatrixx** [comment]
> 
> 
> @hotmatrixx
> спасибо за ответ. удачи тебе и профита.

You're welcome. And I must say that I do like you're attitude lately too. Not that I'm a moderator, or important, or anything.

**Comment by gayya** [comment]
I have traded with real account with many bots.it initially make profit.sometimes it is 200% in real account.but unfortunately next day when you start bot nonstop 7 ,8,9 losses wiped off all profit and deposit as well.Using bot safely you can earn 1% per day.you should know when to exit and when to start.i try online platforms free offering as well,but same result.safely i can say using bot 1% is possible everyday.if you star with 25$ and making 1% you will be end up after 2years account balance of 26216$,at that time your daily earning is 262$.
see excel sheet.Need huge patience.
<img width="960" alt="2020-02-03" src="https://user-images.githubusercontent.com/57481410/73659230-d1265380-46bb-11ea-91a8-f37bdeadf07e.png">

**Comment by gayya** [comment]
these are real account losses,i have lost different platform 600$ from bots.but if i strictly follow 1% rule it wont happened.Some how one thing is correct for sure if you trading manually with good strategy in forex market easily you can get 3-5% profit everyday.Now i am doing that.
![2020-01-02](https://user-images.githubusercontent.com/57481410/73660003-552d0b00-46bd-11ea-9ec5-bc948a4788fd.png)

**Comment by muroyal** [comment]
https://github.com/binary-com/binary-bot/issues/617. 3% profit money management system

**Comment by umar277** [comment]
Share bot'y hu ke oemars277@gmail.com
