### ISSUE TITLE
Diggit Differ Strategy

### ISSUE THREAD

**Issue by sohailsb** [binary-com/binary-bot#2410]
Please Create bot
Volatility 100 index
for example 
if    1503.00   Differ 0
if     1509.11   Differ 1
if     1545.22   Differ 2
same as after Dot   appear Double digit then differ last digit
with best regards

**Comment by Kosta92** [comment]
Digits are randomly generated numbers and aren't based on anything that you can make a trading strategy for. All those strategies that you and others can think of or come by, seemingly daily, are completely useless, to say the least, and are based solely on luck and nothing more.

Other than that, trading digits is widely considered unsafe because it's the easiest way to empty your balance, so no one recommends trading them.

**Comment by sohailsb** [comment]
> Digits are randomly generated numbers and aren't based on anything that you can make a trading strategy for. All those strategies that you and others can think of or come by, seemingly daily, are completely useless, to say the least, and are based solely on luck and nothing more.
> 
> Other than that, trading digits is widely considered unsafe because it's the easiest way to empty your balance, so no one experienced enough recommends trading them.
i am not agree with you, if this is math then we compete with math.
