### ISSUE TITLE
how to convert XML to Exe? and protect script 

### ISSUE THREAD

**Issue by virtusasys** [binary-com/binary-bot#2476]
ths is 3rd time 
how to convert XML to Exe? or remote protect location and protect script 
please help///  just want hire or licence ad my bot

**Comment by Kosta92** [comment]
You can't convert XML to EXE, but what you can do is to find a programmer/coder and pay him to build a trading software based on your strategy.

**Comment by virtusasys** [comment]
yes i can spend some money.. maximum 2500 usd. but iwant protect my script. i want license it or rent it.. with protect my script.. i attached picture with pretct data
![87386287_502619480355800_2920183367318110208_n](https://user-images.githubusercontent.com/59830499/74919573-c7f1f200-53f0-11ea-90f7-39920396614b.jpg)

**Comment by virtusasys** [comment]
![87158291_489225138652902_4774576793476661248_n](https://user-images.githubusercontent.com/59830499/74928085-d0e9c000-53fe-11ea-90e4-d9b357086724.jpg)
how to find programmer/ i can spend monoy.. but i want protect script. just me// because i want rent or serial number one person by one person// or remote location  file///

**Comment by Kosta92** [comment]
Find someone who makes software bots and ask him to collaborate or pay him. The bad part is that he can steal your strategy and make it his own, but I'm sure you are aware of that.

The fist guy who comes to my mind is the legendary bot maker called [Binary Ex Machina](https://github.com/binary-ex-machina). He has his own online trading system on [Binary Auto Trading](https://www.binarybot.online/) and also has an EXE version of the same software which seems like is no longer supported because it redirects to an online version on login. There is also a team of coders called [WisyB Solutions](http://www.wisyb.xyz/) that could build that bot for you. Other guy(s) who can help you are called [Binary Options Copy Trading Club](http://binaryoptionscopytrading.club/). I'm not affiliated with any one of them or anything, I've just used their bots in the past.

**Comment by virtusasys** [comment]
Thanks @Kosta92

**Comment by virtusasys** [comment]
what is binary copy treading?

**Comment by ZDEGLET** [comment]
НИЧЕГО БРАТАН У ТЕБЯ НЕ ПОЛУЧИТСЯ. РАЗГОНЯЙ ДЕПОЗИТ С РЕИНВЕСТОМ И НЕ ПАРЬ МОЗГИ. С ТАКИМ РОБОТОМ Я БЫ УЖЕ ЖИЛ НА КИПРЕ.

**Comment by virtusasys** [comment]
???

**Comment by ZDEGLET** [comment]
@virtusasys
YOU WILL NOT GET ANYTHING BROTHER. DISCOVER DEPOSIT WITH REINVEST.
WITH SUCH A ROBOT I WILL ALREADY LIVE IN CYPRUS.
WRITE ME AN MAIL WITH THE LABEL "virtusasys" I WILL RECOMMEND WHAT TO DO.
zdeglet@gmail.com

**Comment by virtusasys** [comment]
Watch your inbox @ZDEGLET

**Comment by virtusasys** [comment]
there is no email

**Comment by virtusasys** [comment]
Does anyone have any ideas on this?

**Comment by eonuoha30** [comment]
> Does anyone have any ideas on this?

Please, can you help me with the money management aspect of your bot ? Or just an explanation of how the next stake is decided after a loss?

**Comment by virtusasys** [comment]
If lost 7 th step recover 50% lost amount. Because bot winning percentage is higher.

**Comment by virtusasys** [comment]
if you trust your bot dont use martingale ..

**Comment by virtusasys** [comment]
no one knows create program ?

**Comment by virtusasys** [comment]
![gut](https://user-images.githubusercontent.com/59830499/75186351-c1a3a300-576d-11ea-8489-a3ab55387cce.JPG)
@eonuoha30  if you trust your bot dont go recovery always.. try to make wining trade... automatically recover well and no risk %

**Comment by virtusasys** [comment]
nobody has any idea... just wanted quick money... i ll find another method.. thanks all... good luck
