### ISSUE TITLE
Want to sale Low budget bot .. please advice

### ISSUE THREAD

**Issue by virtusasys** [binary-com/binary-bot#2528]
https://youtu.be/9C1BXDwiRZk 
please dont copyright my video
dushanuyt@gmail.com

this is 3 hour result with real account and recorded today
total bot budget 23 Usd
i want sale my bot.. please advice
i just wanted quick money
please help that.. 
thank you

**Comment by thommmaz** [comment]
I call your 3 hours pure luck. Beginning of your video balance is about $67 and profit was $42. Which means you started like $25 balance. Now comes the most scary part - 4 losses in a row! You got lucky that these 4 consecutive losses didn't come up when your balance was at $25 because as you see these 4 losses in a row has taken about $23 from your balance. 
4 losses in a row doesn't mean that 4 is max, there could come 5, 6, 7..... even 10 can come up.  

Let your bot run(on demo) few thousand runs and then you can make conclusions about selling it.

Sooner or later this kind of martingale trading will blow up any account!

**Comment by ZDEGLET** [comment]
This robot will then merge the balance :(

**Comment by ZDEGLET** [comment]
At small percentages there will be a bad result !!!

**Comment by virtusasys** [comment]
Sorry... Try your luck.. thanks... Good luck..

**Comment by ZDEGLET** [comment]
The best robot if it works without Martingale. Then you can pay attention.

**Comment by virtusasys** [comment]
This is real account recording 1 st time in got hub. Last time I posted in virtual account and these stupidi called posted in real account . Now these stupid called it's luck. Dear GitHub kick that asshole

**Comment by virtusasys** [comment]
Thanks .. go to hell

**Comment by virtusasys** [comment]
@thommmaz  go to preschll

**Comment by virtusasys** [comment]
@thommmaz please go to pre-school 1st

**Comment by virtusasys** [comment]
If someone like post like those bot I'll free give all... Good luck..

**Comment by virtusasys** [comment]
Thanks
