### ISSUE TITLE
"This block is called on every tick" combined with "Run After X Second(s)" break the bot

### ISSUE THREAD

**Issue by Kosta92** [binary-com/binary-bot#2607]
Whenever I add a simple text notifier combined with **Run After X Second(s)** inside **This block is called on every tick** field  it breaks the bot, forcing it to run after those seconds run out.
Why does that happen?
Since the text notifier doesn't interfere with the bot's functionality I assume that it shouldn't break it in any way. It should just display a looping text message after X seconds.

Can you fix this issue?

I have attached a simple bot that has this problem. You can notice that it trades again only after a random number of seconds, not immediately when the previous trade ends.

[Broken bot.zip](https://github.com/binary-com/binary-bot/files/4383419/Broken.bot.zip)

**Comment by aaron-binary** [comment]
Hey @Kosta92,

This is happening due to the strategy being executed synchronously, there are no asynchronous operations available for Binary Bot at this time. Even when some asynchronous logic is executed, the underlying JavaScript interpreter will wait until that logic is done before moving on to the next instructions.

What's happening here is that once a tick comes in, the entire bot thread is waiting for 3 seconds, after which it will execute the notify block. While the bot is waiting there are new ticks coming in from the API and for each of these ticks the bot will execute the sleep and notify logic again, e.g. if there are 3 ticks coming in, the bot will wait roughly 9 secs before moving on to the next bit of logic.

Regards,
Aaron

**Comment by Kosta92** [comment]
Thank you for answering.
