### ISSUE TITLE
Facebook login stopped working

### ISSUE THREAD

**Issue by Kosta92** [binary-com/binary-bot#2635]
I was logged out of Binary Bot sometime in the last couple of hours while I was sleeping and now when I tried to log in via Facebook it gave me an error, stating:

"App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions."

Binary.com login isn't working either.

Please solve this issue.

**Comment by harshalkharose** [comment]
I got same issue may be but I login via Gmail try to clear cache data and try

**Comment by harshalkharose** [comment]
I try from other phone it works and one with error I got bu it fixed later try to clear unnecessary %temp

**Comment by harshalkharose** [comment]
Which error showing any number

**Comment by Kosta92** [comment]
It's this error:
![Screenshot_20200405_213609](https://user-images.githubusercontent.com/11698414/78508251-9b6a1d80-7785-11ea-811f-fcbcba88a09a.jpg)

**Comment by harshalkharose** [comment]
App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions."

This error is caused by a configuration issue in your Facebook Developer Application. This means your Facebook app is not live.
Article Number: 114853

Products:

Blackbaud Luminate Online
Email a link to this articleShare Article on FacebookTweet ArticlePrint Article
This error could point to the following issues:
Go to Settings > Basic and make sure there is a Contact Email populated.
Go to App Review and make sure your app is live (Your app is currently live and available to the public).
On App Review, scroll down to make sure publish_actions is not included (As of August 1, 2018, Facebook no longer allows the publish_actions permission. If it is included, resubmit the app for review.).

**Comment by harshalkharose** [comment]
Try this

**Comment by Kosta92** [comment]
Only the developers behind Binary platform can fix this.

**Comment by harshalkharose** [comment]
If you login to your normal fb account still getting this error find out in your machine first in setting

**Comment by harshalkharose** [comment]
Uninstall app go to your phone developer mode wich you will find in setting if don't then tap 6times built number of devices it will enable then download fb and try

**Comment by Kosta92** [comment]
It doesn't have anything to do with my phone or my PC. The problem lays in the Facebook Developers options for which they have control over and not us, the users.

**Comment by harshalkharose** [comment]
Make request to fb developer to make account live if worked let me know also

**Comment by harshalkharose** [comment]
What your fb id

**Comment by aaron-binary** [comment]
Hey @Kosta92,

Thank you for reporting this.

We're looking into this.

Regards,
Aaron
