### ISSUE TITLE
Pan 11 days

### ISSUE THREAD

**Issue by saarsalu** [binary-com/binary-bot#2645]
![Screenshot_20200407-112223_Chrome](https://user-images.githubusercontent.com/30391002/78646680-16385300-78c2-11ea-94a1-7b2c948daa78.jpg)
be warned if you step on the toe of binary.com then you will get a pan

**Comment by josward1** [comment]
what does this mean?

**Comment by aaron-binary** [comment]
Hey @saarsalu,

I closed the issue due to profanity in the posts, you're more than welcome to discuss these kinds of things as long as the discussion is kept civil. I do however suggest to take this discussion to our forums as these GitHub issues pages are meant for Binary Bot related topics.

Regards,
Aaron
