### ISSUE TITLE
 More profitable binary bot

### ISSUE THREAD

**Issue by islamrefaey2019** [binary-com/binary-bot#2689]
first I am apologize for my weak English language
I have bot is very More profitable but I need it Safer
the firs stake is 2.1 but I need it 0.35
and make martingale is 0.35,0.39,0.84,1.68,3.46,7.14
![1](https://user-images.githubusercontent.com/51350288/79468169-e34b3900-7ffe-11ea-8b5d-f38294ca3bee.png)
![2](https://user-images.githubusercontent.com/51350288/79468187-e8a88380-7ffe-11ea-856d-931032c9b8be.png)
![3](https://user-images.githubusercontent.com/51350288/79468207-ed6d3780-7ffe-11ea-866f-3b991b82d465.png)
![4](https://user-images.githubusercontent.com/51350288/79468215-ef36fb00-7ffe-11ea-9222-020d762f24c2.png)

this is the bot
[candle analysis_put-call.txt](https://github.com/binary-com/binary-bot/files/4487748/candle.analysis_put-call.txt)

and I want add target and stoop lose
please I want any friend help me
thanks

**Comment by freedayz04** [comment]
[candle.analysis_put-call + SL TP.zip](https://github.com/binary-com/binary-bot/files/4488535/candle.analysis_put-call.%2B.SL.TP.zip)

Don't mind to use english language like this because if you use another language 
many people can't understand what you want . So I'm weak English language too haha

I added Stop Loss and Take profit for you and you can change it what you want 
and I changed First stake and you can change to stake that you want too.

Hope it will help you and you be happy .

**Comment by islamrefaey2019** [comment]
> [candle.analysis_put-call + SL TP fix.zip](https://github.com/binary-com/binary-bot/files/4488594/candle.analysis_put-call.%2B.SL.TP.fix.zip)
> 
> Don't mind to use english language like this because if you use another language
> many people can't understand what you want . So I'm weak English language too haha
> 
> I added Stop Loss and Take profit for you and you can change it what you want
> and I changed First stake and you can change to stake that you want too.
> 
> Hope it will help you and you be happy .

@freedayz04

**Comment by rubenspina** [comment]
estes bot e igual ao céu azul durante o dia e cem noção nenhuma num dia de tempestade e a noite nao sabe nem se desviar das estrelas
