### ISSUE TITLE
Can anyone plz explain how this [direction] bloc works ? 

### ISSUE THREAD

**Issue by GreenB0t** [binary-com/binary-bot#2743]
How does it identify the direction of the ticks ?? 
![Screenshot_20200502_174758](https://user-images.githubusercontent.com/58006778/80871728-79d55680-8c9d-11ea-833c-47a2af148d72.jpg)

**Comment by Kosta92** [comment]
This block is used to determine if the market price moves in the selected direction or not. It gives you a value of **True** or **False**.

Examples:

1. If the selected direction is **Rise**, and the previous tick value is less than the current tick value, the output will be **True**. Otherwise, the output will be an empty string.

2. If the selected direction is **Fall**, and the previous tick value is more than the current tick value, the output will be **True**. Otherwise, the output will be an empty string.

![Tick Direction](https://user-images.githubusercontent.com/11698414/80872324-75b33400-8cb1-11ea-85cb-8a0823615a11.png)

**Comment by GreenB0t** [comment]
Ok thanks 👍
