### ISSUE TITLE
 Change in payout

### ISSUE THREAD

**Issue by BotBrazil** [binary-com/binary-bot#276]
How do I get the bot to accept the payout change that exists in the currencies and does not stop working because of that change. I realized that volatily we do not have this problem, but in forex currency pairs we have. please help me. Tks

**Comment by Fruitfella** [comment]
U cant amigo.
I think when the bot propose a contract to server, there r these
contract details (including price) and they make sure that the
contract details match the data on the server before they approve it.
That because conflicts might occur due to the differences in the
contract u proposed with the contract they approved. U know that any
contract must be the exact same on both side right?

Like if u propose when the payout was 78% but when the contract was
received by the server the payout changed to 80%, if they approved
this contract, there might be some  conflicts after the contract
closed. Perhaps u might want to sue them (would u? lol) cuz that is
not the payout u proposed.

**Comment by aminmarashi** [comment]
@Fruitfella yes, you're right. But with the new design, we can make this happen by jumping from the second block directly to the first block without purchasing a contract. I'll check the possibilities to implement this feature.

**Comment by aminmarashi** [comment]
@BotBrazil In order to change the payout you need to change the stake in Binary Bot. How are you going to achieve this?
Let's say your stake is 1 USD, and payout is 1.75 USD and your desired payout is 2 USD
How are you going to achieve this?
You have two choices here:

1. change the stake (by jumping to the first block (trade definition))
2. wait until the payout reaches 2 USD automatically

The problem with the first approach is that you possibly won't reach your desired payout after the stake is changed (you may be a little off again e.g. 2.10 USD or 1.90 USD).

The first solution requires to change the core functionality of Binary Bot, so let's clarify which approach do you prefer.

**Comment by Fruitfella** [comment]
I think the 1st solution is better. The 2nd can be out of strategy, i mean the indicator (or price direction) might change and out of the conditions for purchase before it reach the desired payout.

Or perhaps its better to just cancel the purchase, so the bot will make purchase in the next 'right conditions' and 'right payout'? but this mean it will be the opposite of what @BotBrazil asked 😝

**Comment by aminmarashi** [comment]
Good point @Fruitfella. However, I'm trying to guess what @BotBrazil is trying to achieve by changing the payout.
What seems most reasonable to me is that he's trying to earn a certain amount of profit (`payout - stake`) which also means he needs to change the stake which in turn can change the payout amount.
@BotBrazil It's best if you can demonstrate what you're trying to do by doing it manually on our trading platforms or an example of what you're trying to do.

@Fruitfella as you mentioned before, to get a new price for a contract we need to ask for a new contract from binary.com servers. This may take some time during which you may miss the ideal position to purchase a contract.

**Comment by BotBrazil** [comment]
Gentlemen, @Fruitfella @aminmarashi 
I ask for forgiveness if I express myself badly and with that I have made you lose your precious times. What happens is that other than the payout is fixed (94%), the Forex is variable, which causes the interruption of the work of the bot, when the payout drastically changes the bot simply to. I want a solution just for that.
And again thank you!

**Comment by elyyyes** [comment]
Hi everybody,

someone can help me in this please ?

https://github.com/binary-com/binary-bot/issues/776

thank you in advance for cooperate
Regards
