### ISSUE TITLE
BEST 2020EVEN BOT

### ISSUE THREAD

**Issue by abdulahi24hrs4u** [binary-com/binary-bot#2787]
I NEED SOMEONE TO HELP ME BUILD A BOT

WHEN THE PREVIOUS 3 ARE ODD, IT SHOULD TRADE EVEN 1 TICK

EXAMPLE

1.23259
1.26547
1.23531

SINCE THE LAST DIGIT OF THOSE PREVIOUS ARE ODD, OPEN EVEN TRADE 1 TICK

![photo_2020-05-16_17-25-20](https://user-images.githubusercontent.com/65455501/82124917-4b29a680-979a-11ea-920b-1f0a202f4ade.jpg)

**Comment by sinung21** [comment]
[BOT EVEN.zip](https://github.com/binary-com/binary-bot/files/4645617/BOT.EVEN.zip)

**Comment by abdulahi24hrs4u** [comment]
> [BOT EVEN.zip](https://github.com/binary-com/binary-bot/files/4645617/BOT.EVEN.zip)

can you please make it 5 for me instead of 3

WHEN THE PREVIOUS 5 ARE ODD, IT SHOULD TRADE EVEN 1 TICK

EXAMPLE

1.23259
1.26547
1.23531
1.25235
1.63259

SINCE THE LAST DIGIT OF THOSE PREVIOUS ARE ODD, OPEN EVEN TRADE 1 TICK

**Comment by sinung21** [comment]
[5ODD IS EVEN 1THICK V75.zip](https://github.com/binary-com/binary-bot/files/4652966/5ODD.IS.EVEN.1THICK.V75.zip)

**Comment by Geanfranco39** [comment]
I have such a bot. I'll save you the hard time and disappointment: It doesn't work.

**Comment by camaropeti** [comment]
I Use a very profitable stargegy since a month what good for make profit every day. Not insane profits, but on 500 dollar account easy to make daily 40-50 dollar profit. That's an even-odd strategy. Here is what I do:
First I use this digit pad site:
https://tradeonline.herokuapp.com/digitPad/

I see on markets the even and odd numbers. sometimes go down around 34-33. If it happens I use this site:
https://tradeonline.herokuapp.com/sniper/#
I set up the strategy: Even Odd roll cake -> I set the market where the number is very low, and I set 1 tick on three menu
I think, my strategy is minimise the risk to get lot of loss trade in a row.
![Jegyzet 2020-06-02 191632](https://user-images.githubusercontent.com/66323430/83549559-c82c7e00-a505-11ea-9878-7d46d18c2b01.png)
![Jegyzet 2020-06-02 191627](https://user-images.githubusercontent.com/66323430/83549565-cbc00500-a505-11ea-9599-0484558a5f60.png)
It better if wait for lower number, but under 40 is low the chance to lose more than 5-6 times.
I use low trading amount, and martingale 2,25 multiplier.
Best result is if wait on digitpad number 35 or lower and stop the sniper bot if the digitpad number reach the 40. In this case you have high chance to make winning trades, of course you will got some losing trade, but the martingale will kick the loss.

So I need help to automatize my strategy. I know it not possible to make a bot what see every volatility market, just only one. Maybe the best is vol75.
The method my strategy:
if last 100 tick there was only 35 Odd start trade Odd until last 100 tick Odd number counter reach 40 AND last trade is winning
if last 100 tick there was 35 Even start trade Even until last 100 tick Even number reach 40 AND last trade is winning.
If the last trade was lose use multiplier 2,25 on last trade amount If win set back the trade amount to initial.

Another good series of trade:
![Jegyzet 2020-06-02 193811](https://user-images.githubusercontent.com/66323430/83552738-8b16ba80-a50a-11ea-81e2-9bd1ae006210.png)

![Jegyzet 2020-06-02 193817](https://user-images.githubusercontent.com/66323430/83551530-bdbfb380-a508-11ea-9401-24ce54ab3f8a.png)

**Comment by trident2005** [comment]
You are wasting your time

**Comment by camaropeti** [comment]
> You are wasting your time

Have you better strategy? Easy to say to something that's not good, but have you better? Please help and share with us if you are so smart. We are just try make some money with strategy what we think probably will be good. I know every strategy works well on different conditions, and not all day long of course, but if you can catch the favorable case, you can make some profit.
I know that the even odd strategy is not good for "start the bot, and go away from computer". But if calculate the probability of good chances you can be good for some trade.

**Comment by trident2005** [comment]
To tell them not to waste their time is to help them, EVEN / ODD is one of the most deceptive contracts, there is no efficient strategy with EVEN / ODD, it is 100% casino rules, even more than OVER / UNDER, you can base your count on more than 100 Historical data ticks and that will not make a difference in your trading quality.

**Comment by camaropeti** [comment]
thanks to your warning. You are say true. Sometimes got 12-14 same result. Sometimes better the rise/fall strategy on tick chart.

**Comment by syed18** [comment]
@sinung21 can you please send me your email, i have good strategy to make bot

**Comment by overwatch873** [comment]
> I have such a bot. I'll save you the hard time and disappointment: It doesn't work.

😂😂😂Aaah cmon bro you should  have let him have his moment...before breaking it to him

**Comment by Johnex7** [comment]
> [5ODD IS EVEN 1THICK V75.zip](https://github.com/binary-com/binary-bot/files/4652966/5ODD.IS.EVEN.1THICK.V75.zip)



SINCE THE LAST DIGIT OF THOSE PREVIOUS ARE ODD, OPEN EVEN TRADE 1 TICK AND KEEP ON OPENING EVEN TRADES ON 1 TICK CONSECUTIVELY FOR MARTINGALE LEVEL OF 5.

THANKS.

**Comment by rubenspina** [comment]
este bot e muito ruim para de perder tempo com isto nunca vai ganhar so perder.
[cid:53befce6-e4bc-4ef9-8f90-e1c0ded58a98]

________________________________
De: Johnex7 <notifications@github.com>
Enviado: sábado, 27 de junho de 2020 16:19
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] BEST 2020EVEN BOT (#2787)


5ODD IS EVEN 1THICK V75.zip<https://github.com/binary-com/binary-bot/files/4652966/5ODD.IS.EVEN.1THICK.V75.zip>

SINCE THE LAST DIGIT OF THOSE PREVIOUS ARE ODD, OPEN EVEN TRADE 1 TICK AND KEEP ON OPENING EVEN TRADES ON 1 TICK CONSECUTIVELY FOR MARTINGALE LEVEL OF 5.

THANKS.

**Comment by rubenspina** [comment]
tip for this $ 50 strategy which will receive a print of the Chart and a short video of the correct entry of 22 seconds

If I do the operations, I want half the profit 50% of the profit transferred to my account. If I suspect, do not contact me to do business.

[https://2.bp.blogspot.com/-3AoDOzW1gV8/XvQK1dJa7uI/AAAAAAAAAh8/WbMqNuNadCM5MguQ-eLUyGbF0EwAvkD9ACK4BGAYYCw/w905-h976/image.png]<https://www.blogger.com/blog/post/edit/4259436675958339601/1875271679465581324#>
<https://www.blogger.com/blog/post/edit/4259436675958339601/1875271679465581324#>[https://2.bp.blogspot.com/-gSw7olIc7W8/XvQK3nwJevI/AAAAAAAAAiE/RaxI59sAOlsHF76H6LNBDAkHF_88Q3sPACK4BGAYYCw/w916-h976/image%2B%25281%2529.png]<https://www.blogger.com/blog/post/edit/4259436675958339601/1875271679465581324#>



________________________________
De: Johnex7 <notifications@github.com>
Enviado: sábado, 27 de junho de 2020 16:19
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] BEST 2020EVEN BOT (#2787)


5ODD IS EVEN 1THICK V75.zip<https://github.com/binary-com/binary-bot/files/4652966/5ODD.IS.EVEN.1THICK.V75.zip>

SINCE THE LAST DIGIT OF THOSE PREVIOUS ARE ODD, OPEN EVEN TRADE 1 TICK AND KEEP ON OPENING EVEN TRADES ON 1 TICK CONSECUTIVELY FOR MARTINGALE LEVEL OF 5.

THANKS.

**Comment by kjsanjeewa** [comment]
> [BOT EVEN.zip](https://github.com/binary-com/binary-bot/files/4645617/BOT.EVEN.zip)

Set the Last Digit Prediction 0 and Price Bar count the  - - - - -.0  -   then Open Purchase Digit Differs Order with the this same setting.

automatically change LDP and open trade with the  ----.0- this no. 
Ex. LDP 0   price bar ----.0-   open differ
LDP 1   price bar ----.1-  open differ
LDP 2   price bar ----.2-  open differ
LDP 3   price bar ----.3-  open differ
LDP 4   price bar ----.4-  open differ
LDP 5   price bar ----.5-  open differ
LDP 6   price bar ----.6-  open differ
LDP 7   price bar ----.7-  open differ
LDP 8   price bar ----.8-  open differ
LDP 9   price bar ----.9-  open differ

Stake 1.1
Martingle add the 11
Take Profit, Stop Loss
![Screenshot 2020-11-27 21 10 17 - Copy](https://user-images.githubusercontent.com/74783297/100886864-52b46100-34da-11eb-8637-8985fe782db8.png)

**Comment by Tarikulislamakash** [comment]
@sinung21  I have a Strategy, can you make the bot, please

If the last digit is 0 or 1 then it will trade for over if i lose then it will set martingale 5, and trade immediately not wait for 0 or 1 to appear

**Comment by Gfxbyboss** [comment]
> [BOT EVEN.zip](https://github.com/binary-com/binary-bot/files/4645617/BOT.EVEN.zip)

Hello please... Can you help me put this strategy this way ...cause I've been trying it manually and it's been working fine for me ....but I need it in bot form ...v75 trade even if the bot spots digit 8 or 9 on the last digit followed with an odd number then it trades for even ...
Example
163838.789
177484.78(odd on last digit )
Then it takes trade and also 
682638.788
688387.67(odd on last digit)
Then it takes trade

**Comment by kadenoo** [comment]
Hey ... assist me in creating a bot that starts at a specific time on which I set and if it gets digit 5 or 4 on digit over or under, martingale should start .I should be able to change the martingale
