### ISSUE TITLE
HOW DO I CHANGE THE BOT DEFAULT CURRENCY FROM USD TO GBP

### ISSUE THREAD

**Issue by Greatefe** [binary-com/binary-bot#2854]
Hello
I cant trade on binary bot that i purchased because the bot reject my GBP real account. The bot is set by default to trade only on USD. Please how can i trade the bot using my fiat GBP currency. Or can you convert my fiat currency from GBP to USED? Ive been practicing with demo and now to trade real money. My Token name and number is Greatefe fUjnfYQPXTNH2EX
Thanks

**Comment by Greatefe** [comment]
Hello
I have solution to my issue reported. Please dont bother changing my fiat currency GBP . I have found the area in the bot where i can easily adjust the currency setup according to ones specification.
Thanks

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/
[https://1.bp.blogspot.com/-RFfOP3JWnIY/XvPeALQnl9I/AAAAAAAAAhg/110DQ6gLa8grFWQRWFl7r2dDbS8c2h1YQCNcBGAsYHQ/w1200-h630-p-k-no-nu/bot.png]<https://ongdetraders.blogspot.com/>
traders<https://ongdetraders.blogspot.com/>
ongdetraders.blogspot.com


________________________________
De: Greatefe <notifications@github.com>
Enviado: sexta-feira, 12 de junho de 2020 12:53
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] HOW DO I CHANGE THE BOT DEFAULT CURRENCY FROM USD TO GBP (#2854)


Hello
I have solution to my issue reported. Please dont bother changing my fiat currency GBP . I have found the area in the bot where i can easily adjust the currency setup according to ones specification.
Thanks

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/

________________________________
De: Greatefe <notifications@github.com>
Enviado: sexta-feira, 12 de junho de 2020 10:29
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [binary-com/binary-bot] HOW DO I CHANGE THE BOT DEFAULT CURRENCY FROM USD TO GBP (#2854)


Hello
I cant trade on binary bot that i purchased because the bot reject my GBP real account. The bot is set by default to trade only on USD. Please how can i trade the bot using my fiat GBP currency. Or can you convert my fiat currency from GBP to USED? Ive been practicing with demo and now to trade real money. My Token name and number is Greatefe fUjnfYQPXTNH2EX
Thanks
