### ISSUE TITLE
Extracting element from list

### ISSUE THREAD

**Issue by PHKiNG** [binary-com/binary-bot#2884]
Hi I would extract numbers form my list. I have a list of Numbers I want to extract all the 1s, 2s, 3s, etc and see how many there are how can I do this??

**Comment by sam-binary** [comment]
Hi @PHKiNG ,

to get a specific item from a list, you can use this block
<img width="480" alt="Screenshot 2020-06-26 at 1 40 19 PM" src="https://user-images.githubusercontent.com/51310435/85824596-c7100900-b7b2-11ea-8ed6-9e164196bf2d.png">

to get the length of a list, you can use this block
<img width="475" alt="Screenshot 2020-06-26 at 1 41 12 PM" src="https://user-images.githubusercontent.com/51310435/85824665-e870f500-b7b2-11ea-88b8-92e26c3038ee.png">

Regards,
Sam

**Comment by PHKiNG** [comment]
Yeah this is how I'm doing it now I'm looking at each position of the list then I decide what number it is with a if statement. Do you think there is a way to make a find function?? 

Because I have a list of only 10 numbers but looking at each position and the deciding what number it is and I have a giant wall of blocks lol so I was just wondering if there is a more efficient way of do it?? 

What im trying to create is something like this:

Count how many 1s are there in this list.

Thanks
PH

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/
[https://1.bp.blogspot.com/-RFfOP3JWnIY/XvPeALQnl9I/AAAAAAAAAhg/110DQ6gLa8grFWQRWFl7r2dDbS8c2h1YQCNcBGAsYHQ/w1200-h630-p-k-no-nu/bot.png]<https://ongdetraders.blogspot.com/>
traders<https://ongdetraders.blogspot.com/>
ongdetraders.blogspot.com


________________________________
De: PHKiNG <notifications@github.com>
Enviado: sexta-feira, 26 de junho de 2020 09:34
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] Extracting element from list (#2884)


Yeah this is how I'm doing it now I'm looking at each position of the list then I decide what number it is with a if statement. Do you think there is a way to make a find function??

Because I have a list of only 10 numbers but looking at each position and the deciding what number it is and I have a giant wall of blocks lol so I was just wondering if there is a more efficient way of do it??

What im trying to create is something like this:

Count how many 1s are there in this list.

Thanks
PH

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/
[https://1.bp.blogspot.com/-RFfOP3JWnIY/XvPeALQnl9I/AAAAAAAAAhg/110DQ6gLa8grFWQRWFl7r2dDbS8c2h1YQCNcBGAsYHQ/w1200-h630-p-k-no-nu/bot.png]<https://ongdetraders.blogspot.com/>
traders<https://ongdetraders.blogspot.com/>
ongdetraders.blogspot.com


________________________________
De: sam-binary <notifications@github.com>
Enviado: sexta-feira, 26 de junho de 2020 05:43
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] Extracting element from list (#2884)


Hi @PHKiNG<https://github.com/PHKiNG> ,

to get a specific item from a list, you can use this block
[Screenshot 2020-06-26 at 1 40 19 PM]<https://user-images.githubusercontent.com/51310435/85824596-c7100900-b7b2-11ea-8ed6-9e164196bf2d.png>

to get the length of a list, you can use this block
[Screenshot 2020-06-26 at 1 41 12 PM]<https://user-images.githubusercontent.com/51310435/85824665-e870f500-b7b2-11ea-88b8-92e26c3038ee.png>

Regards,
Sam

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/

________________________________
De: PHKiNG <notifications@github.com>
Enviado: quinta-feira, 25 de junho de 2020 16:37
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [binary-com/binary-bot] Extracting element form list (#2884)


Hi I would extract numbers form my list. I have a list of Numbers I want to extract all the 1s, 2s, 3s, etc and see how many there are how can I do this??

**Comment by PHKiNG** [comment]
what in the hell

**Comment by rubenspina** [comment]
https://ongdetraders.blogspot.com/
https://ongdetraders.blogspot.com/
https://ongdetraders.blogspot.com/
https://ongdetraders.blogspot.com/
https://ongdetraders.blogspot.com/

________________________________
De: PHKiNG <notifications@github.com>
Enviado: sábado, 27 de junho de 2020 11:36
Para: binary-com/binary-bot <binary-bot@noreply.github.com>
Cc: rubenspina <projetos_10@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [binary-com/binary-bot] Extracting element from list (#2884)


what in the hell
