### ISSUE TITLE
Digit match prediction analysing bot

### ISSUE THREAD

**Issue by sajeeshbinary** [binary-com/binary-bot#2896]
Sajeesh:
I want an analyzing prediction digit match bot ,the trade only when prediction digit comes,otherwise don't trade 

If prediction is 4 the bot must trade ,another 4 comes the trade will win ,otherwise the bot will not trade, more more same same dual digits comes ,it's sure it's an good profitable bot

Any one to make this type of bot

**Comment by Kosta92** [comment]
_It's sure it's a good bot_ ... to empty your account balance, because digits are completely randomized numbers and no one can build any strategy around them. By trading digits you are basically playing roulette, and as with roulette, the only thing that counts is luck.

Your "strategy" has beed done many times before, all without any success.

**Comment by sajeeshbinary** [comment]
Thanks

**Comment by channa2020** [comment]
what is name for volatility ( Ex. 10, 25,50,75,100 ).your strategy work only last digits stats only 4 Green 25%.Good Luck

**Comment by ananA2** [comment]
> Sajeesh: I want an analyzing prediction digit match bot ,the trade only when prediction digit comes,otherwise don't trade
> 
> If prediction is 4 the bot must trade ,another 4 comes the trade will win ,otherwise the bot will not trade, more more same same dual digits comes ,it's sure it's an good profitable bot
> 
> Any one to make this type of bot

Kindly share xml with us .. mnnaslam@gmail.com
