### ISSUE TITLE
Some bot that works in forex market?

### ISSUE THREAD

**Issue by chidotaku** [binary-com/binary-bot#2927]
Im looking for  a bot that works with forex markets, not  synthethic indixes. I have bots that works in synthethics but when i change to a forex market i get a error.

"the underlying market has moved too much since you priced the contract. the contract payour has changed from usd 1.07 to usd1.05"

**Comment by aaron-binary** [comment]
Hey @chidotaku,

This sometimes happens when the payout has changed from our side. You can check the **Restart last trade on error** option to let the bot automatically continue if such error occurs.

<img width="474" alt="Screenshot 2020-07-23 at 10 26 00" src="https://user-images.githubusercontent.com/44427668/88247035-e9704600-ccce-11ea-9f32-3ce17f0aeedb.png">

**Comment by chidotaku** [comment]
thanks for the answer!!
