### ISSUE TITLE
How to create the functions on the bot

### ISSUE THREAD

**Issue by Eymard-08** [binary-com/binary-bot#2973]
Hi, I wanted to program my bot I don't know how I can create the functions I wanted help with.

**Comment by hotmatrixx** [comment]
I made a small tutorial series on how to use the bot a few months ago.
Here is a link to the first tutorial, I hope it helps you begin your journey.

I will likely get back into the bot and start making tut's on the newer, DERIV. 
I've learned a lot since making these ones so these are not perfect but they should help you undertand the syntax better
https://www.youtube.com/watch?v=rzXYoF0v5_s
