### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by overwatch873** [binary-com/binary-bot#3009]
@aaron-binary @anton-binary @aminmarashi-binary @carol-binary @jy-binary @ashkanx ....guys i have a request....why did you make the new dbot platform a lilttle bit complicated than the old binarybot platform....the old binarybot interface was simple and and more easy to navigate your way around....i have heard many bot traders talk about this issue....we love the upgrade you made but perhaps you could have kept the new dbot platform just the same as the old binary platform....Thanks

**Comment by carol-binary** [comment]
Hey @overwatch873,

Thank you for your feedback! 
Can you be a little more specific about what about the DBot interface seems complicated to you? If we have more details, we can discuss these issues internally and see what can be done about this.

Regards,
Carol

**Comment by overwatch873** [comment]
> Hey @overwatch873,
> 
> Thank you for your feedback!
> Can you be a little more specific about what about the DBot interface seems complicated to you? If we have more details, we can discuss these issues internally and see what can be done about this.
> 
> Regards,
> Carol

The  dbot  interface particularly...... which shows a summary of on going trades......i like the old binarybot interface which just shows you everything on a single tab....making it easier to see and manage your trades.... rather than the dbot interface which is little sophisticated

**Comment by aaron-binary** [comment]
Hey @overwatch873,

Thank you for your feedback, this is very valuable to us. 

If we would provide some Transactions and Journal messages on the Summary tab, do you think that would that improve the experience?

Let us know if you have any ideas or suggestions, we're more than happy to hear them. 👍 

Regards,
Aaron

**Comment by contatodeanet** [comment]
também acho complicado de montar o robô, quando transfiro um bot para o dbot e caso ele tenha alguma aba desativada o robô não executa, sem contar que ainda não existe linguagem brasileira na plataforma. tem previsão quando vão colocar pra o idioma brasileiro?

**Comment by aaron-binary** [comment]
@contatodeanet,

Obrigado pelo seu feedback! 🙏

Não tenho muita certeza do que você quer dizer com "estado desativado", poderia explicar? Quanto à IU, estamos em processo de revisão, o que tornará mais fácil encontrar os blocos. E para o idioma, devemos ter o português disponível nas próximas semanas.

Regards,
Aaron

**Comment by deny-titan** [comment]
Hi @aaron-binary 

I have an idea. How if you make a new Tab called "Summary" beside Workspace and Chart? So in below we can see "Workspace", "Chart" and "Summary" to be selected. This Summary tab is old style "Summary" window from Binary Bot. I also think, if the area of screen become larger than old Summary window in Binary Bot, you can add other information in that area, like "Profit Table" or "Statement" that change our Balance. Because our Balance can be affected by other trade instead of running bot. So this information maybe more use full for trader that running more than 1 bot on one account, for example running an hedging strategy with 2 bot or more.

Now I'm talking about new Deriv style "Summary", "Transaction" and "Journal". I think Summary tab here can give us a very large display. Now it only displaying "Won" or "Loss". How if you add "Profit" or "Loss" amount below Won/Loss. And if we put mouse over, please give more detailed information about last transaction in graphical illustration. You already made beautiful illustration, like on Trade Contract Detail (in Trade mode, not DBot). But the size of available display here is limited. So, I think you can make it more simple, like I found it on www.binarybot.online. (Autotrader Web Binary & Deriv).

Thank you 👍

**Comment by contatodeanet** [comment]
> @ aaron-binary @ anton-binary @ aminmarashi-binary @ carol-binary @ jy-binary @ashkanx .... caras, eu tenho um pedido .... por que você fez a nova plataforma dbot um pouco mais complicada do que a antiga plataforma binarybot .... a antiga interface binarybot era simples e mais fácil de navegar .... ouvi muitos bot traders falarem sobre este assunto .... nós amamos a atualização que você fez, mas talvez você pudesse ter manteve a nova plataforma dbot igual à antiga plataforma binária .... Obrigado

Eu tive uma ideia sobre isso!! teria como colocar alguma opção onde poderíamos escolher em usar a versão nova do Dbot ou a antiga do Bot dentro da Deriv.com!!!! Seria fantástico!!!
