### ISSUE TITLE
I want to create this type of odd even strategy

### ISSUE THREAD

**Issue by sasikumar0186** [binary-com/binary-bot#3056]
First analyse the tick chart 100 index if the chart shows even number are higher percentage then 2(starting odd num is must blue) odd number comes purchase even. If the trade lose then analyse the market even or odd then purchase. Same as the odd number but starting even num in red help me for this

**Comment by sasikumar0186** [comment]
Analyse the chart and the same number show in display

**Comment by sasikumar0186** [comment]
Sorry I don't know how to explain

**Comment by wyu001** [comment]
dude .. your strategy and observations it would not works to implemented on bot - especially for odd/even ..try to make more dynamic strategy for the bot - due to binary has hundred or maybe thousand of pattern to roll their odd/even .. which we don't know when they change their patterns .. it could be every minutes , hours .. etc... I have been create hundreds of bot for this  ha ha ha .. still I can't follow their patterns, so far my best odd/even bot .. can follow the pattern up to 200 runs after got 8 consecutives loss .. well still need to do repair on it .. its wasting time .. but fun to do it .. ha ha ha .. good luck. cheers.

**Comment by VIPER12th** [comment]
> dude .. your strategy and observations it would not works to implemented on bot - especially for odd/even ..try to make more dynamic strategy for the bot - due to binary has hundred or maybe thousand of pattern to roll their odd/even .. which we don't know when they change their patterns .. it could be every minutes , hours .. etc... I have been create hundreds of bot for this ha ha ha .. still I can't follow their patterns, so far my best odd/even bot .. can follow the pattern up to 200 runs after got 8 consecutives loss .. well still need to do repair on it .. its wasting time .. but fun to do it .. ha ha ha .. good luck. cheers.

Share us your best odd even bot pls

**Comment by wyu001** [comment]
> Share us your best odd even bot pls

@VIPER12th I am sorry not able to share it for this moment bro...due to my bot is not perfect yet plus , if sharing in here , there is a risk
that the bot would be failed soon due binary IT also monitoring our bot ..am I right ? my suspicious thinking ( with all respect to Binary IT team that helping us a lot how to use / making the bot ) .. any bot that mentioned here would be inserted into binary computer system that easy for them to counter back our strategy he he he .. CMIIW.

anyway - this is general method for making Odd/Even bot.
1. Made one side only - do not run your bot for both side ( Odd or Even only ) , this to lesser your risk for loss.
2. Never read only the last digit ( which is Odd or even number ) but you have to read the last 3 digits of the ticks number to get the trigger entering buy odd or even. 
3. Think this way , the number odd and even is NOT randoms , but they have patterns ( it must be hundreds pattern or thousands ) , it is looks like random , yes it is random by purposes. 
4. made your bot as dynamic as possible to follow number pattern. examples : e,o,o,e,e,,o,o ,e,o this is only linear pattern that most of bot creator here making - it would be failed after several runs. 
5. do trial of your bot and take a note the result - try on virtual and real money ( this is what I did ) . 

I did trial of my bot - result is : more than 700 runs - got 100 bucks with stake 0.5 got 6 consecutive loss three times on that runs. So , you can made some profit for sure, but you have to do some hard work to coding it. I guess my bot would be fail someday, means binary making another pattern or they have various pattern that not release everyday ha ha ha ...

cheers, 
wyu 
Note : jancuk arek2 nang endi kabeh iki .. wis pada pensiun tah  ?
