### ISSUE TITLE
Strategy with max and low ticks

### ISSUE THREAD

**Issue by ekozhin** [binary-com/binary-bot#3076]
Hello everyone!

I would like to try trading using a strategy, with the following condition: if a tick on the chart reaches a maximum, then a sale occurs, and if a tick reaches a minimum, then a buy accordingly.

on a tick chart it looks like this
![chart](https://user-images.githubusercontent.com/24454432/97491165-d7a7da00-1972-11eb-8df6-b05758120722.png)

In binary bot, I didn't find how to do it with ticks, I only found how to do it with candles. 
![conditions](https://user-images.githubusercontent.com/24454432/97491433-35d4bd00-1973-11eb-9935-ee45235695c5.png)

Tell me how to do this? thanks

**Comment by wyu001** [comment]
@ekozhin - you have to use fruitfella candle / chart indicator rsi , ema's etc for your strategy - use your search engine to find fruitfella tools. btw , myself no longer using method to read candles .. a bit tricky using this tricks if you were trading on volatility markets , which is "not-real"markets , it is created by Binary market, the house always 99% wins , you have only a little 1% , it is still a good chance anyway , if you know which way to get that tiny 1% chance .. pls discover more bro...

**Comment by wyu001** [comment]
The Pictures below is the result of what found and I would love to share all I know to this community - but I have limitation
that i can't give it all the strategy due to limitation that we got from Binary as well :) ... 
but this is the clue that I believe all senior trader on this github would be laugh on me ..:)
1. making a bot that could stand still for 24 hrs - the answer is NO and YES ..no is 99% persen , Yes is 1% , lets figure out this 1% - why , because binary computer system - whatever complex it is , still made by human , there is no 100% human made is perfect , it is always defect even only 1% , but still defect. 
2. Since we are play on volatility market ( Digits , RF etc ) it is steer by binary system right ? , so then stick on it , follow their way to get's that 1 %. 
3. Use their digits ( ticks numbers ) into your bot's ..yes true use that to predict next 1 or 5 ticks outcome using their numbers, using candles and all other tools - it may help , but not much .. only 30% i guess those tools could help prediction the future 
whether it is up or down, odd or even :) ..then why we are not stick on one side only - then our bot and strategy not working so hard to guess both sides ???  
4. Lastly , this is my personal tricks and tips ( as shown below ) - use only one side , for digits I use 2 digits from ticks number 
for triggering buy one side. For rise and fall , I use 3 or 4 digits to triggering buy one side.. that's all. no indicator , no digits analyzer use for triggering buy/sell , why ??  I will explained on next chance.. cheers. 

![image](https://user-images.githubusercontent.com/37494697/97551535-acba9600-1a05-11eb-8f05-ddc2f41cd70b.png)

![image](https://user-images.githubusercontent.com/37494697/97550259-03bf6b80-1a04-11eb-9904-6744df00320e.png)

**Comment by VIPER12th** [comment]
> The Pictures below is the result of what found and I would love to share all I know to this community - but I have limitation
> that i can't give it all the strategy due to limitation that we got from Binary as well :) ...
> but this is the clue that I believe all senior trader on this github would be laugh on me ..:)
> 
> 1. making a bot that could stand still for 24 hrs - the answer is NO and YES ..no is 99% persen , Yes is 1% , lets figure out this 1% - why , because binary computer system - whatever complex it is , still made by human , there is no 100% human made is perfect , it is always defect even only 1% , but still defect.
> 2. Since we are play on volatility market ( Digits , RF etc ) it is steer by binary system right ? , so then stick on it , follow their way to get's that 1 %.
> 3. Use their digits ( ticks numbers ) into your bot's ..yes true use that to predict next 1 or 5 ticks outcome using their numbers, using candles and all other tools - it may help , but not much .. only 30% i guess those tools could help prediction the future
>    whether it is up or down, odd or even :) ..then why we are not stick on one side only - then our bot and strategy not working so hard to guess both sides ???
> 4. Lastly , this is my personal tricks and tips ( as shown below ) - use only one side , for digits I use 2 digits from ticks number
>    for triggering buy one side. For rise and fall , I use 3 or 4 digits to triggering buy one side.. that's all. no indicator , no digits analyzer use for triggering buy/sell , why ??  I will explained on next chance.. cheers.
> 
> ![image](https://user-images.githubusercontent.com/37494697/97551535-acba9600-1a05-11eb-8f05-ddc2f41cd70b.png)
> 
> ![image](https://user-images.githubusercontent.com/37494697/97550259-03bf6b80-1a04-11eb-9904-6744df00320e.png)

Pls kindly share this your bot with us

**Comment by deny-titan** [comment]
> Hello everyone!
> 
> I would like to try trading using a strategy, with the following condition: if a tick on the chart reaches a maximum, then a sale occurs, and if a tick reaches a minimum, then a buy accordingly.
> 
> on a tick chart it looks like this
> ![chart](https://user-images.githubusercontent.com/24454432/97491165-d7a7da00-1972-11eb-8df6-b05758120722.png)
..
> Tell me how to do this? thanks

@ekozhin This is the way to capture Maximum and Minimum tick on specific time period :

![SharedScreenshot21](https://user-images.githubusercontent.com/71332443/97893754-48c90200-1d64-11eb-85cf-52e9978b0b97.jpg)

**Comment by ekozhin** [comment]
I assembled a bot, 
![bot](https://user-images.githubusercontent.com/24454432/97955767-04ffe800-1db8-11eb-8069-4585f9906593.jpg)
but nothing happens. What am I doing wrong?

**Comment by deny-titan** [comment]
This caused by your Last Tick become member of Data Set, then you can not use ">" or "<" operation, but you can use equal (=) in operation. OR, if you want to make sure that your last tick is slightly higher than Highest point in Data Set, please separate Data Set with your Last Tick with this correction : 

Set Data Set to in List "Tick List" get sub list **# from end (Tick_data + 1)** to **# from end ( 2 )**.

So, Last Tick is not included in your Data Set, and you can compare it with Highest point in Data Set by "greater" operator (>) as shown on your Purchase Block.

**Comment by vnxz** [comment]
> 
> 
> The Pictures below is the result of what found and I would love to share all I know to this community - but I have limitation
> that i can't give it all the strategy due to limitation that we got from Binary as well :) ...
> but this is the clue that I believe all senior trader on this github would be laugh on me ..:)
> 
>     1. making a bot that could stand still for 24 hrs - the answer is NO and YES ..no is 99% persen , Yes is 1% , lets figure out this 1% - why , because binary computer system - whatever complex it is , still made by human , there is no 100% human made is perfect , it is always defect even only 1% , but still defect.
> 
>     2. Since we are play on volatility market ( Digits , RF etc ) it is steer by binary system right ? , so then stick on it , follow their way to get's that 1 %.
> 
>     3. Use their digits ( ticks numbers ) into your bot's ..yes true use that to predict next 1 or 5 ticks outcome using their numbers, using candles and all other tools - it may help , but not much .. only 30% i guess those tools could help prediction the future
>        whether it is up or down, odd or even :) ..then why we are not stick on one side only - then our bot and strategy not working so hard to guess both sides ???
> 
>     4. Lastly , this is my personal tricks and tips ( as shown below ) - use only one side , for digits I use 2 digits from ticks number
>        for triggering buy one side. For rise and fall , I use 3 or 4 digits to triggering buy one side.. that's all. no indicator , no digits analyzer use for triggering buy/sell , why ??  I will explained on next chance.. cheers.
> 
> 
> ![image](https://user-images.githubusercontent.com/37494697/97551535-acba9600-1a05-11eb-8f05-ddc2f41cd70b.png)
> 
> ![image](https://user-images.githubusercontent.com/37494697/97550259-03bf6b80-1a04-11eb-9904-6744df00320e.png)

what strategy use for fall and rise by taking digit from 4 back counting from last digit
use odd even up and down or number interrupt strategy?

**Comment by keymdedan9** [comment]
Someone share the bot kimdedan95@gmail.com
