### ISSUE TITLE
Martingale on loss and wins

### ISSUE THREAD

**Issue by Omoka101** [binary-com/binary-bot#3087]
Hello anyone with a bot that I.e when trading odd even or rise fall does:
     1)martingales to recover stake plus some profits
      2)when in profits it trades using both the initial stake and winnings I.e compounds twice or thrice after which stake goes back to initial

**Comment by deny-titan** [comment]
Hey @Omoka101 ,

1. Yes. Almost all bot use Martingale like this to recover amount of previous lost. Some profit added is benefit to give a shorter time duration to reach a target profit. But consider if the next trade is lost again, then we must recover with more money for stake rather than we use a martingale to recover a lost just in adequate amount of stake, without adding some profit. 
2. This strategy is effective only on market that have a higher win probability; i.e Over/Under bot or Digit Differs bot. Consider if you compounding 100% profit from previous trade, and have trade loss now, your balance is not increased and you must prepare fresh money for next stake. Better is not 100% of profit is compounding for next trade. I think about 40%-60% is good enough.

**Comment by woletm** [comment]
@deny-titan please help me attend to my issue too please. its a new one tagged "money management system needed please"

**Comment by Omoka101** [comment]
I was of this opinion because 
1.in a market with equal chances of coming like odd even it's always a race between successive winning and losing streaks and whether your bank roll can survive the exposure
2.i am more comfortable with losing a $9 trade consisting of an initial stake of $5 +$4 from my first win which if correct means I'm working with a bigger risk to reward I.e $5 for $17 

With the above in mind I can now protect my capital even further by using a martingale of as low as *1.4 on a losing trade

**Comment by Omoka101** [comment]
Thanks for replying...
