### ISSUE TITLE
Anyone have a CALL PUT strategy that loses up to 5 orders? Let me create a bot 

### ISSUE THREAD

**Issue by MiithRanDir** [binary-com/binary-bot#3115]
Anyone have a CALL PUT strategy that loses up to 5 orders? Let me create a bot.

**Comment by doehlma** [comment]
Hello MiithRanDir,

can you please look to my following reuuest Boolinger Band Strategy concept need support #3113,
an support me ?

Best regards

**Comment by MiithRanDir** [comment]
> Hello MiithRanDir,
> 
> can you please look to my following reuuest Boolinger Band Strategy concept need support #3113,
> an support me ?
> 
> Best regards

Candle Bollinger Band
[Candle-BB.zip](https://github.com/binary-com/binary-bot/files/5635715/Candle-BB.zip)

**Comment by doehlma** [comment]
Thanks a lot .. Gesendet mit der WEB.DE iPad AppAm 03.12.20 um 12:22 schrieb MiithRanDir
                
            
            
                
                    Von: "MiithRanDir" <notifications@github.com>Datum: 3. Dezember 2020An: "binary-com/binary-bot" <binary-bot@noreply.github.com>Cc: "Comment" <comment@noreply.github.com>,"doehlma" <postandoehler@web.de>Betreff: Re: [binary-com/binary-bot] Anyone have a CALL PUT strategy that loses up to 5 orders? Let me create a bot  (#3115)
                
                

Hello MiithRanDir,
can you please look to my following reuuest Boolinger Band Strategy concept need support #3113,
an support me ?
Best regards

Candle Bollinger Band
Candle-BB.zip

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/binary-com/binary-bot/issues/3115#issuecomment-737879593",
"url": "https://github.com/binary-com/binary-bot/issues/3115#issuecomment-737879593",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by doehlma** [comment]
Hello thansk,

 

but there is 2 times RISE inside.. have to be RISE or FALL


 

Is it possible to correct ?

 

Gesendet: Donnerstag, 03. Dezember 2020 um 12:22 Uhr
Von: "MiithRanDir" <notifications@github.com>
An: "binary-com/binary-bot" <binary-bot@noreply.github.com>
Cc: "doehlma" <postandoehler@web.de>, "Comment" <comment@noreply.github.com>
Betreff: Re: [binary-com/binary-bot] Anyone have a CALL PUT strategy that loses up to 5 orders? Let me create a bot (#3115)


 


Hello MiithRanDir,

can you please look to my following reuuest Boolinger Band Strategy concept need support #3113,
an support me ?

Best regards


Candle Bollinger Band
Candle-BB.zip

**Comment by MiithRanDir** [comment]
@doehlma 
Try the steps in order of 1 - 2 - 3 see. Solve new one.

**Comment by doehlma** [comment]
Sorry I not understood what you mentioned ??Gesendet mit der WEB.DE iPad AppAm 04.12.20 um 05:15 schrieb MiithRanDir
                
            
            
                
                    Von: "MiithRanDir" <notifications@github.com>Datum: 4. Dezember 2020An: "binary-com/binary-bot" <binary-bot@noreply.github.com>Cc: "Mention" <mention@noreply.github.com>,"doehlma" <postandoehler@web.de>Betreff: Re: [binary-com/binary-bot] Anyone have a CALL PUT strategy that loses up to 5 orders? Let me create a bot  (#3115)
                
                
@doehlma
Try the steps in order of 1 - 2 - 3 see. Solve new one.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/binary-com/binary-bot/issues/3115#issuecomment-738553870",
"url": "https://github.com/binary-com/binary-bot/issues/3115#issuecomment-738553870",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by viniciusctt** [comment]
> Anyone have a CALL PUT strategy that loses up to 5 orders? Let me create a bot.

Hello friend, if you can take a look at # 3202 I am hopefully in need of help
