### ISSUE TITLE
Time filter

### ISSUE THREAD

**Issue by zomuzco** [binary-com/binary-bot#312]
Hello, is there a way to put in pause the bot for a fixed time? I mean for example: the bot works from 1.am to 11.30 a.m then pause from 11.31 to 14.30 and then restart  automatically from... to.... Is there a way to make a thing like this?

**Comment by aminmarashi** [comment]
Yes, take a look at https://github.com/binary-com/binary-bot/issues/158#issuecomment-309320455

**Comment by Fruitfella** [comment]
There is, @zomusco
it just a bit complicated..
---------------------
You can use "seconds since epoch" block to compare the time you want
to trade with the current time. To compare certain times of the day
you can calculate the remainder of epoch by 86400 (which is the number
of seconds in 24 hours).
To learn more about epoch go to https://www.epochconverter.com/.

In ur case : bot will pause at 11.31-14.30 (GMT)

- Convert 11.31 (GMT) of any day to epoch, i use this day and get : 1499772660
- Above value (1499772660) % 86400 = 41460
- Do the same thing for 14.30 and i get : 52200
- Check if "seconds since epoch" % 86400 is between 28800 and 36000,
if not do purchase.

p.s. u need to be careful about your timezone. or u could just use GMT lol.
