### ISSUE TITLE
Do you have a GOOD STRATEGY? Pay little and it'd be worked on IMMEDIATELY.

### ISSUE THREAD

**Issue by eonuoha30** [binary-com/binary-bot#3134]
Hello....

This forum aims at helping you with your strategies and clarifying tough issues regarding binary trading.

It might take hours, days or weeks to get a response.

If responded to, you might still have lots of ideas/strategies you'd love to try out (but not willing to wait again).

Anyway....

You can have all your strategies and ideas worked on 'immediately' for just a little token.

Send me an email now through:

eonuoha30@gmail.com

**Comment by Fahed-umar** [comment]
Hi eonuoha30

**Comment by Fahed-umar** [comment]
> مرحبا eonuoha30

Can you help me find out how the bot is linked to the account balance? A condition. If the account balance drops in order to complete Martingale, it is not a requirement that you lose the deal in order to complete Martingale.

> Hi eonuoha30
Can you help me find out how the bot is linked to the account balance? A condition. If the account balance drops in order to complete Martingale, it is not a requirement that you lose the deal in order to complete Martingale.

**Comment by Fahed-umar** [comment]
> > مرحبا eonuoha30
> 
> Can you help me find out how the bot is linked to the account balance? A condition. If the account balance drops in order to complete Martingale, it is not a requirement that you lose the deal in order to complete Martingale.
> 
> > Hi eonuoha30
> > Can you help me find out how the bot is linked to the account balance? A condition. If the account balance drops in order to complete Martingale, it is not a requirement that you lose the deal in order to complete Martingale.

Sorry, because my English is weak

**Comment by eonuoha30** [comment]
> Hi eonuoha30

Hello, 

I apologize for not being able to respond to your messages.

Send me a mail via eonuoha30@gmail.com

(For quicker response)
