### ISSUE TITLE
I have a good rise/fall MA cross strategy but need some help

### ISSUE THREAD

**Issue by moshika18471** [binary-com/binary-bot#3162]
hey i have a good rise/fall strategy

_strategy is:_- **if MA 6 and MA 14 crossing while MA8 is above MA6-----------PUT
                          if MA 6 and MA 14 crossing while MA8 is below MA6-----------CALL**

but i need a BOT for this strategy. please can somebody develop a BOT for that

(STRATEGY WORKS ON ANY PAIR AND HAS 99.9% SUCCESS RATE)

**Comment by Jonni81** [comment]
отправьте скрин пожалуйста. как все должно происходить 22.01.2021, 14:13, "moshika18471" <notifications@github.com>: hey i have a good rise/fall strategystrategy is:- if MA 6 and MA 14 crossing while MA8 is above MA6-----------PUTif MA 6 and MA 14 crossing while MA8 is below MA6-----------CALLbut i need a BOT for this strategy. please can somebody develop a BOT for that(STRATEGY WORKS ON ANY PAIR AND HAS 99.9% SUCCESS RATE)—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Cannie37** [comment]
Hie, I'm testing your strategy on auto trader web, it seems to be working, Link: binarybot.online 
email me for assistance at neotechs11@gmail.com

**Comment by overwatch873** [comment]
> отправьте скрин пожалуйста. как все должно происходить 22.01.2021, 14:13, "moshika18471" <notifications@github.com>: hey i have a good rise/fall strategystrategy is:- if MA 6 and MA 14 crossing while MA8 is above MA6-----------PUTif MA 6 and MA 14 crossing while MA8 is below MA6-----------CALLbut i need a BOT for this strategy. please can somebody develop a BOT for that(STRATEGY WORKS ON ANY PAIR AND HAS 99.9% SUCCESS RATE)—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Hi....is it for ticks or candlesticks

**Comment by oramaster** [comment]
> hey i have a good rise/fall strategy
> 
> _strategy is:_- **if MA 6 and MA 14 crossing while MA8 is above MA6-----------PUT if MA 6 and MA 14 crossing while MA8 is below MA6-----------CALL**
> 
> but i need a BOT for this strategy. please can somebody develop a BOT for that
> 
> (STRATEGY WORKS ON ANY PAIR AND HAS 99.9% SUCCESS RATE)

This is a possible solution to your requested BOT.

Link to BOT: https://bit.ly/2Ofg7N5

![SMA 6 8 14 B2 v1](https://user-images.githubusercontent.com/63653432/107130873-1e8e5f80-68d2-11eb-9e8b-31b1c288e6a2.gif)
![SMA 6 8 14 Results v1](https://user-images.githubusercontent.com/63653432/107130877-24844080-68d2-11eb-9562-7f9d7809a39d.gif)

The results are horrible after 100 runs

Link to BOT: https://bit.ly/2Ofg7N5
