### ISSUE TITLE
Stochastic binary bot

### ISSUE THREAD

**Issue by bronchez** [binary-com/binary-bot#3203]
I need someone to develop stochastic bot or show me how to add stochastic in binary bot like we do for RSI and MA

**Comment by HOANGDUYTR** [comment]
>

**Comment by Peacefull-Mind** [comment]
Hi Bronchez di you manage to get Stochastic on your bot ?

**Comment by bronchez** [comment]
Hi, have not yet got it

**Comment by carol-binary** [comment]
Hi @bronchez,

I've reopened this issue. 

Regards,
Carol

**Comment by binary-ex-machina** [comment]
@bronchez and @Peacefull-Mind, check my script for this indicator

https://github.com/binary-ex-machina/binary.com-bot/wiki/Indicators#stochastic

**Comment by vickkyss** [comment]
Please  @ex-machina I wud really a nid ur stochastic indicator download becos I wud like to use it in strategy am working on thanks.

**Comment by Peacefull-Mind** [comment]
i need help developing a bot no touch.
anyone here that can help ?

**Comment by bronchez** [comment]
I can develop it for you

**Comment by binary-ex-machina** [comment]
@Peacefull-Mind send the strategy here and we can help

**Comment by Peacefull-Mind** [comment]
@bronchez the idea is as follow ...

identify a strong trend, idealy using ADX, stochastic and RSI...  purchase a no touch position against the trend with a high pay-out for example 800 to 1000 % and then close trade at Profit
 when profit is between 150 to 250% of your stake  what can happen most of the time within the first few ticks if you chose an expiration time of 6 minutes as an example.
this will give you a 2/1 profit what means you don't need to use martingale as you will win enough times to cover you losses. even if you only win half of the times what is very unlikely you will still be on 0. so the lag with opening and closing a position will sometimes makes you lose however the times will make you win will cover for those aswell.
I've been doing this manually and works extremely well however after a wile you start seeing things when they don't exist and start doing trades all the time without paying attention to the trend. :p

[NO touch strategy description(1).pdf](https://github.com/binary-com/binary-bot/files/7475137/NO.touch.strategy.description.1.pdf)

**Comment by Peacefull-Mind** [comment]
@binary-ex-machina big fan 💯  ... been trying to do it myself with your indicators script however i dont know how to set them up

**Comment by Peacefull-Mind** [comment]
idealy would have to barriers both on no touch :)

**Comment by Peacefull-Mind** [comment]
Will this be possible to create ?

**Comment by binary-ex-machina** [comment]
I want to propose a modification to your strategy. The detrended oscillator is complex to create in the blocks, and it doesn't work with extremes (it has a central line only)

RSI, Stochastic, and Williams %R all have extremes levels (CCI can be one option too) MACD has a central line, so I believe it doesn't suit well for this strategy of counter-trend.

Check the image below and tell me if it is still valid for your strategy. 

The first arrow will represent a No touch strategy with a negative barrier, assuming the market price will go up. First, the Stoch and W%R crossed over the bottom level. Then, after less than 5 candles, RSI crossed over the bottom level too, so the trade would still be valid. With more than 5 candles for all the indicator crosses, the signal becomes invalid.

The second arrow will be for no-touch positive barriers, assuming the market will go down. Stoch, RSI, and W%R crossed down the upper level almost simultaneously, which would represent a good signal. 

All of this uses a 1min time frame with 6 minutes expiration. The market on the image is EURUSD.

What do you think?

![image](https://user-images.githubusercontent.com/34610787/140327801-e702ede7-c2b6-49e6-870a-8d823d088ec1.png)

**Comment by Peacefull-Mind** [comment]
@binary-ex-machina I haven't tried with a 1 minute time frame so not sure if that would work because the barrier to get 1000% payout is very small but it looks promising.
I have been doing on ticks and i know the results are good but i guess if you think that will get the results lets do it :)

**Comment by Peacefull-Mind** [comment]
@binary-ex-machina i can see your on this for a wile, do you think if we would put the bot running on a server would improve the lag on the positions ?

**Comment by binary-ex-machina** [comment]
@Peacefull-Mind on the blocks, it doesn't have a 4min time frame. The close ones are 3 or 5 minutes. If you use 3 minutes time frame, it may work, but it will take a lot of time to trade. Since it's simple to change, I believe it's suitable for testing both without too much modification.

On a VPS, it will work well if you have a nice setup for the site of the block. However, it will consume the RAM after trading, and the page may become unresponsive and reload. If you can create code using their API, it will work better. A cloud server will reduce the delays and lags and better options.

I will create the idea and post it here so you can test it.

**Comment by binary-ex-machina** [comment]
Here is an idea of how to do it. First, it runs a loop before defining the contract parameters, like a stake, duration, and trade type. 
After any cross (under or over), it sets a variable of each indicator to true. After all of them are true, it defines the direction. Then, based on the direction of the reversal, it changes the barrier signal. For example, I put a barrier to getting 200% profit but change the number since your idea is to use one that gives 800%. 

At block 3, it will sell the contract based on the sellAtProfit% you set. I didn't add money management. In case you change the candle interval, change the timeframe in minutes as well. The testing will take several minutes to be triggered, and it will be challenging to validate fast. There would be some errors since I didn't test, but so far, my custom indicators (Stochastic and Williams% R) are calculating right.

![image](https://user-images.githubusercontent.com/34610787/140379956-0604bc00-b251-48ee-993e-c950836b3ec1.png)

[test mind.xml.zip](https://github.com/binary-com/binary-bot/files/7476514/test.mind.xml.zip)

**Comment by Peacefull-Mind** [comment]
@binary-ex-machina thanks a lot i will test it and see how we get on, will post results in here to keep you updated as well.

**Comment by Peacefull-Mind** [comment]
the bot doesnt seems to be starting

**Comment by Peacefull-Mind** [comment]
and I've just noticed that I've done a mistake on the description.
The time frame should be ticks and the expiration time 4 minutes or 6 minutes.

**Comment by Peacefull-Mind** [comment]
however i think i can change this, i just need to change "in candle list" to "tick list" in all indicators right ?

**Comment by Peacefull-Mind** [comment]
is coming up with an error saying given candle is not valid.

**Comment by binary-ex-machina** [comment]
it needs to be candle list, I am playing here and I don't have any errors

**Comment by Peacefull-Mind** [comment]
hi @binary-ex-machina ....defenetly not working i tried to leave it all night and is not even starting could you post blocks here to see if is something missing please

**Comment by Peacefull-Mind** [comment]
Something is definitely not right or I'm missing something because its definitely not working i even tried to put notification to see if is running and notification are not coming up either
