### ISSUE TITLE
Digit are waste of time really

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3261]
I made a lot of differ bot in last one week.
So many strategies 
last 3 digit same 2 digit same 
least frequent digit most frequent digit %
But I still not get good one .
although only one level loss in a row is not gurantee for differ bot
really good differ bot need only one loss in 50 win.
One time I get bot that in 110 and loss 5 .
But it need to wait long time
Do you know any good winning strategy for differ with prove.
If proven strategy has, let me know , I will convert to bot.

**Comment by Xbrmachine** [comment]
Olá @vnxz, não há alguém que pudesse comprovar que ganha dinheiro com esta modalidade de bot com frequência, ainda que de algum retorno por algum tempo, em algum momento levará todo seu dinheiro.

Por esta razão estou desenvolvendo um projeto onde juntos possamos desenvolver uma estratégia vencedora e converte-la em um bot.

Gostaria de contribuir? através dos seus questionamentos e ideias que ja desenvolvel tenho certeza que somará para criarmos um bot realmente vencedor.

basta acessar este problema #3262

**Comment by dritonbytyqi** [comment]
@vnxz I did test a lot of strategies before and there are just a few that works but needs a lots of time to run for each run and conditions are not so complicated but I don't know if anyoje can make it work in that way.
It can work but need a lot of investment I mean you need at least 420 usd balance to use that bot properly with 3 recovery steps
First investment. 0.35
Recover 1 : 3.50
Recover 2:  37.85
Recover 3:  380.00 
Rules are simple but complicated when it needs to be a functional bot. 
Counting last 1000 ticks and get the bot into trade only when the 1000 last ticks/digits number for example nr 6 percentage in last 1000 digits is over 13% then bot gets in action if it is lower than 13% then stops trading and wait for conditions to met. 
I am experienced trader in backtesting and I know some strategies that really works but to make it work in bots it's really hard because you need to combine all elements to make it consistent profitable in longterm. @vnxz if you are good and creating bots and make it for free for this community I can share some strategies with fulldetails how to work propery but beng profitable :)

**Comment by dritonbytyqi** [comment]
I posted a strategy with 50% of details needed with trending 2 or 3 SMA and stochastic it works and is profitable but has no mant singlas during an hour you can get 2 or 3 signals candles in 1 mintf and expiry 5 minutes this is a working ans tested strategy but to make it a bot to work properly it's very hard @vnxz @Xbrmachine

**Comment by Xbrmachine** [comment]
@dritonbytyqi é exatamente como comentou, exige muito foco no que se esta fazendo.

Estou criando um e muito empenhado nele para que possamos ter uma soluçao real.

Pode posyar seu bot para testarmos e implementar algo novo se necessário?

**Comment by dritonbytyqi** [comment]
@Xbrmachine Yes I can, but you want for Digits or for Trending markets strategy ?
If it is for digits is not so easy because you have to find the right conditions 
For example in last 100 ticks  in the number for ex no.3 
0 = 7% 
1 = 9%
2 = 8%
3 = 18% (take action when conditions are met 18% or over 18% one of 10 numbers in this case nr.3
4 = 12%
5 = 10%
6 = 8%
7 = 11%
8 = 10%
9 = 7%
This is tested and works but are just a few signals per hour and if we have a balance of 400 usd we could be profitable in longterm if we let at least 10 hours per day 1 index works ex Inicie 100 from 08:00 to 18:00 there would be a around 100 to 200 signals per day in one index, and we need a balance of around 400 usd to make it work with martingale strategy
1 Tick trading 
1 step 0.35 usd
2 step 3.50 usd
3 step 38.50 usd
4 step 423.00 usd
After we make profit we can make it work with higher capital depends on earning events.
As for that Exponential moving averages combined with Stochastic it is very realisitic and tested strategy but to make it a properly working bot is a bit of problem...

**Comment by binary-ex-machina** [comment]
Digits are randomly generated, any digit can come next and the chance is 10% of this to happen. You can try to work with a sequence of digits, waiting for some sequence to happen, but after a lot of trades, it will be the same as no analysis. Rise/Fall strategies that run non-stop have a 50% chance of winning, no matter the strategy. Even/Odd strategies are the same. Any strategy that has a payout of 94% (6% is the fee from the broker) has a 50% chance of winning. Less payout, more win rate, more payout, less win rate.

You can run an Even-Odd bot 24/7 for 30 days and never hit 12 losses in a row, but you can hit 16 losses in a row with 1-hour playing the same bot, no matter the analysis. That's how digits works, it's random, its chaos.

Rise fall will fall in the same idea, on 100 trades it may have 70 wins and 30 losses, 70% win rate, but on 10.000 trades it will never have 7.000 wins. It's in the nature of the instrument and the math laws.

**Comment by dritonbytyqi** [comment]
Digit bot differ works based on algorithmic number generator rules and that has nothing to do with the odds appeared upper in this issue.
If you understand permutations and combinations then you understand how the digit differ really works because I understood it but to create a bot as I request is not easy becuse most of people missunderstand that, and I tested it in many different way but only true positive results I got when I used the number generator methodology as comparison analyse.
For example for last 100 digits : 
0 appeared 8 times, 1 appeared 11 times, 2 appeared 20 times, 3 appeared 12 times, 4 appeared 6 times, 5 appeared 10 times, 6 appeared 12 times, 7 appeared 8 times, 9 appeared 13 times : THEN : 
The number with the highest appearing percentage will not show in next 100 ticks , respectively not as much as 10% of times 1 of 10 chance, and this gives us chance to use martingale and trade digit differ but it is really complicated because when it comes to enter the trade and cover losess there are some missunderstood issues for exampl;e 
you trade digit differ afer no.2 appeared 20 times and you enter a trader digit differ with 1 tick expiry 0.35usd and you lost, and then you go with first step of recovery 3.5usd and then you win, but do you keep trading with reset 0.35 usd untill the percentage goes lower than 20% or last 20 times appeared number 2 ? or go in next 100 ticks in same direction with trading digit differ in 100 next ticks that means around 3 minutes ?

**Comment by binary-ex-machina** [comment]
> Digit bot differ works based on algorithmic number generator rules and that has nothing to do with the odds appeared upper in this issue.
> If you understand permutations and combinations then you understand how the digit differ really works because I understood it but to create a bot as I request is not easy becuse most of people missunderstand that, and I tested it in many different way but only true positive results I got when I used the number generator methodology as comparison analyse.
> For example for last 100 digits :
> 0 appeared 8 times, 1 appeared 11 times, 2 appeared 20 times, 3 appeared 12 times, 4 appeared 6 times, 5 appeared 10 times, 6 appeared 12 times, 7 appeared 8 times, 9 appeared 13 times : THEN :
> The number with the highest appearing percentage will not show in next 100 ticks , respectively not as much as 10% of times 1 of 10 chance, and this gives us chance to use martingale and trade digit differ but it is really complicated because when it comes to enter the trade and cover losess there are some missunderstood issues for exampl;e
> you trade digit differ afer no.2 appeared 20 times and you enter a trader digit differ with 1 tick expiry 0.35usd and you lost, and then you go with first step of recovery 3.5usd and then you win, but do you keep trading with reset 0.35 usd untill the percentage goes lower than 20% or last 20 times appeared number 2 ? or go in next 100 ticks in same direction with trading digit differ in 100 next ticks that means around 3 minutes ?

to get the answer to any digits related questions, just let a bot with "some analysis" trading for 10.000 trades. Then put a bot without any analysis to trade 10.000 times. Compare the results and you will see that it doesn't matter.

**Comment by uhmlex** [comment]
> I made a lot of differ bot in last one week. So many strategies last 3 digit same 2 digit same least frequent digit most frequent digit % But I still not get good one . although only one level loss in a row is not gurantee for differ bot really good differ bot need only one loss in 50 win. One time I get bot that in 110 and loss 5 . But it need to wait long time Do you know any good winning strategy for differ with prove. If proven strategy has, let me know , I will convert to bot.

conact me by my email uhmlex7@gmail.com to give you a working one
