### ISSUE TITLE
How can get fix max value of candle high from last candles

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3290]
I want to get last highest candle value as show in picture
![Screenshot_1](https://user-images.githubusercontent.com/76085185/119848479-dacb6e80-bf31-11eb-9362-e7f0a33deaf3.png)

If I use this block code ,highest max value is not fix .it always change value 
![Screenshot_2](https://user-images.githubusercontent.com/76085185/119848210-a3f55880-bf31-11eb-890e-f10330bc60d2.png)

How can get fix max highest value of last candles.

@saidforex26
@ex-machina

**Comment by saidforex26** [comment]
get sub-list from # from end 5,
to # from end 1

**Comment by vnxz** [comment]
> 
> 
> get sub-list from # from end 5,
> to # from end 1

Hi bro, this value is not static.
how can get static value
because from end 5 from end 1 vary with new candle
if new candle appear , it will count new candle .so 5 to 1 value change in every candle

**Comment by saidforex26** [comment]
if you want to get a high value from the list of candles, that's how.

**Comment by binary-ex-machina** [comment]
@vnxz, the way to get the highest candle is like you did. If the new candle has a higher high value, it will be the highest value on the selected period. If you want to avoid the latest candle, use "from end 2" as you did.  using 2 to 5 is too short, increase to 20-30 and it will change less, since the length is bigger
