### ISSUE TITLE
4 consecutive LDP and MM Strat

### ISSUE THREAD

**Issue by Pabzev** [binary-com/binary-bot#3318]
I have tested  a strategy which consists in 4 consecutive LDP and then open Digit Differs. This strategy provided me good profits but up to a point.  The traditional martingale risks too much and it is not so viable for small accounts. I tested the MM system (attached as template.xml and showed in this picture)  I'd like to use this MM in combination of 4 consecutive LDP strategy.
Could anyone help me incorporate  this strategy on the bot I got here? Thank you.

@myuzio
@binary-ex-machina
[template.zip](https://github.com/binary-com/binary-bot/files/6660176/template.zip)
[DBot.-.4.Consecutive.LDP.Then.Buy.Digit.Differs.from.Last.Digit.with.notify.per.tick.1.zip](https://github.com/binary-com/binary-bot/files/6660178/DBot.-.4.Consecutive.LDP.Then.Buy.Digit.Differs.from.Last.Digit.with.notify.per.tick.1.zip)

![image](https://user-images.githubusercontent.com/85974815/122155620-b6cac100-ce3d-11eb-9fcf-ffbb0639b167.png)

**Comment by vnxz** [comment]
> 
> 
> I have tested a strategy which consists in 4 consecutive LDP and then open Digit Differs. This strategy provided me good profits but up to a point. The traditional martingale risks too much and it is not so viable for small accounts. I tested the MM system (attached as template.xml and showed in this picture) I'd like to use this MM in combination of 4 consecutive LDP strategy.
> Could anyone help me incorporate this strategy on the bot I got here? Thank you.
> 
> @myuzio
> @binary-ex-machina
> [template.zip](https://github.com/binary-com/binary-bot/files/6660176/template.zip)
> [DBot.-.4.Consecutive.LDP.Then.Buy.Digit.Differs.from.Last.Digit.with.notify.per.tick.1.zip](https://github.com/binary-com/binary-bot/files/6660178/DBot.-.4.Consecutive.LDP.Then.Buy.Digit.Differs.from.Last.Digit.with.notify.per.tick.1.zip)
> 
> ![image](https://user-images.githubusercontent.com/85974815/122155620-b6cac100-ce3d-11eb-9fcf-ffbb0639b167.png)

do you have binary bot xml file , Dbot file cannot load in binary bot
I not prefer Dbot

**Comment by Pabzev** [comment]
Try opening in my repository click in raw and save as xml.

https://github.com/Pabzev/binary.com

![image](https://user-images.githubusercontent.com/85974815/122217800-26639f00-ce84-11eb-8150-2372acd76eac.png)

Change the extention to .xml and ALL TYPES (*.*)

![image](https://user-images.githubusercontent.com/85974815/122218330-ba356b00-ce84-11eb-980a-a44d3ce03bfc.png)

Let me know is it works. Are you trying to apply the MM above? Could you please share later? Thank you.

**Comment by Pabzev** [comment]
I guess it may not worl for you. Please see the image. Don't have this one just this bad picture but you it can be read.

![image](https://user-images.githubusercontent.com/85974815/122221251-7b54e480-ce87-11eb-8e33-d99f957eefc2.png)

**Comment by binary-ex-machina** [comment]
This strategy will make you lose your entire capital. At some point, you will hit 5-7 losses in a row. Trying to split the losses on subsequent trades is just useless. You may hit a loss while recovering from the previous loss and then it becomes impossible to recover.

@Pabzev checking your image of the logic, you are comparting all the last 4 digits more than 3 times, there is no need to do that. Also your prediction doesnt make much sense, since it changes all the time to a digit that will be part of the analysis, it's just random. The entire logic is just random. You will have the same result as sticking to a single digit or waiting for a sequence, it will be just the same. Forget about digit differ, all combinations you do, all the possible patterns you think you will find, they have the same risk/profit. You amy stay under 4 losses in a row for an entire month, at some point you will lose 5-7 times in a row and low it all

You may find a situation impossible to happen, but it will happen because digits are random, and the more you play, more are the chances of it happens


The same result of your multiple comparing digits
![image](https://user-images.githubusercontent.com/34610787/123209225-aeeeca80-d496-11eb-9b98-8989bc318adf.png)
