### ISSUE TITLE
Help, need for QQE new histo indicator 

### ISSUE THREAD

**Issue by radon222dose** [binary-com/binary-bot#3373]
Hello friends,
I need the QQE new histo indicator, can anyone help.
thank you

**Comment by binary-ex-machina** [comment]
Here is a way of calculating it. It will have a QQFast list representing the fast signal, and the QQSlow list will be the slow signal. Change RSI Length and Smooth as you need. It's hard to test this indicator since you can't check with the market data from Deriv, but it should be a good start for your development of the indicator. 

Both variables will work as a list, so use the list blocks to get the values (the last value of the list will be the most recent. Values will be around 50 value

![image](https://user-images.githubusercontent.com/34610787/129944145-88f6a4ee-5de8-488c-846d-84046654950a.png)
