### ISSUE TITLE
Fake Loss concept

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3375]
Fake loss concept base on

if entry condition met, example if SMA1 > SMA10, this is rise bet
but no actual bet and create fake bet
SMA1>SMA10 
duration of bet is 5 ticks
So need to count tick after condition met
Tick count 1,2,3,4,5
if tick = 5 and last tick > last 5 tick , it is WIN 
else it is Loss, Fake Loss

Here problem is how to count ticks
if one condition met, change tick count by 1
but after that this condition is not more met, cannot count next 1 tick

Do you have solution for this Tick count by logically.

@ex-machina

**Comment by trident2005** [comment]
The problem with the emulation of the fake loss on the binary.bot platform is that there are conditions on the server that do not make it possible.

Your approach is wrong because you are considering the 5 ticks that the contract would last, but you are not considering the ticks corresponding to the request and the placement of the contract within the server.

Then we have another event that corresponds to the real execution of the operations, when a real operation is placed on the server, the platform takes some time to return the result, this should also be able to emulate but it is not possible to do it in a precise way.

The best way to use fake loss is through an application, because through code we can evaluate results in advance and make a perfect execution.

**Comment by vnxz** [comment]
> 
> 
> The problem with the emulation of the fake loss on the binary.bot platform is that there are conditions on the server that do not make it possible.
> 
> Your approach is wrong because you are considering the 5 ticks that the contract would last, but you are not considering the ticks corresponding to the request and the placement of the contract within the server.
> 
> Then we have another event that corresponds to the real execution of the operations, when a real operation is placed on the server, the platform takes some time to return the result, this should also be able to emulate but it is not possible to do it in a precise way.
> 
> The best way to use fake loss is through an application, because through code we can evaluate results in advance and make a perfect execution.

What application use for this?
Can I know?

**Comment by trident2005** [comment]
The popular DEEGEEBOT and no too much popular BOS Digit System as far as I know.

**Comment by binary-ex-machina** [comment]
@vnxz, you can try like this. It will not simulate the delays caused by the internet slow connection or server loads, but it may do the trick. Personal opinion, virtual losses delay your losses. It doesn't avoid Them. Since you use a fixed amount of losses to start on real trades, this means your chance of winning is still 50%. It's not worth the time/risk.

![image](https://user-images.githubusercontent.com/34610787/129945778-47584fae-68be-41c5-8a90-66aa75186276.png)

**Comment by vnxz** [comment]
> 
> 
> @vnxz, you can try like this. It will not simulate the delays caused by the internet slow connection or server loads, but it may do the trick. Personal opinion, virtual losses delay your losses. It doesn't avoid Them. Since you use a fixed amount of losses to start on real trades, this means your chance of winning is still 50%. It's not worth the time/risk.
> 
> ![image](https://user-images.githubusercontent.com/34610787/129945778-47584fae-68be-41c5-8a90-66aa75186276.png)

something error happen when run votality index order
it show r is undefined
but not show when run forex order
what is problem
