### ISSUE TITLE
Do you have proven winning strategy for rise fall or higher lower 

### ISSUE THREAD

**Issue by vnxz** [binary-com/binary-bot#3378]
I made a lot of bot .But not satisfy .no perfect bot .
I also have many premium bot.All are scam .
Not profit in real.
Do you have any proven strategy?
I will convert to bot

**Comment by saidforex26** [comment]
bot can not run 24 hours.

**Comment by binary-ex-machina** [comment]
There is no perfect strategy. Also, on your tests, how many trades you did on each bot?

I will share my experience with a lot of strategies.

First strategy:  a simple call put bot, first trade call, next put, repeat. 1 tick duration
10.000 trades - win rate close to 50%, got 15 losses in a row. Starting applying martingale only after a 3 loss and with a balance of $5.000,00 you would have made around $1,750. Time would be around 1,5 day

Second strategy: following the color of the candle, green candle call, red candle put. 50 seconds duration
10.000 trades - win rate close to 50%, got 14 losses in a row. Applying martingale since the first trade. With $20.000,00, it would have made close to $1750. The time to complete the test is around 7 days.

Third Strategy: Cross between EMa 9 and EMA 26. Crossover Call, crossunder Put. 1min candles and 50 seconds duration
10.000 trades - Win rate close to 50%, got 14 losses in a row. Applying martingale since the first trade. With around $20.000, it would have made close to $1750. time to complete is around 30 days.

Fourth strategy: MACD cross, Stochastic Cross, Trend definition by SMA 20 and SMA 200 on 1min candles, 50 seconds duration. MACD crossover, stochastic crossover, SMA20 > SMA200 - CALL. MACD crossunder, Stochastic Crossunder, SMA20 < SMA200 - PUT
5.000 trades - Win rate close to 50%, got 12 losses in a row. Applying martingale since the first trade. With around $5.000, it would have made $875. Time to complete around 60 days

As you can see, all rise fall strategies have 50% accuracy, will get 10 or more losses in a row, no matter what you use as an indicator or filter for the signals. All those strategies were running 24/7, so there is no strategy that you can just play and make money without the risk of losing all your account.

I use for more than a year and can be done with XML bots (I have my own Binary/Deriv apps that I run everyday with this strategy and others) is the Hull Moving Average with 50 periods. When the candle crosses over the HMA (wait for the candle to end), I enter in favor of the cross with 54 seconds duration. In case of a loss, martingale until a win, always with 54 seconds duration and entering at 58 seconds of the minute. Using always 1 min candles. 

Target 1-3% a day. In more than 400 days of trading (not trading all days in sequence), I got 9 losses in a row.

Below the arrows show where you could start the trade. It would require a good amount of capital to start, and using virtual trades or applying martingale after a certain number of losses is not profitable. After these 400 days, with stop loss at 50% of the account, my average profit per day is 0,8%. Any sample data you use with less than 1000 trades is useless. If you tested with less than that, you just wasted your time. That's why a lot of people use strategies on demo accounts and then change to real accounts. They lose all. The test phase is too short and not even recorded for future consults

![image](https://user-images.githubusercontent.com/34610787/129949403-21475af5-b070-441c-9530-f0bf7af6c137.png)

**Comment by vnxz** [comment]
> 
> 
> There is no perfect strategy. Also, on your tests, how many trades you did on each bot?
> 
> I will share my experience with a lot of strategies.
> 
> First strategy: a simple call put bot, first trade call, next put, repeat. 1 tick duration
> 10.000 trades - win rate close to 50%, got 15 losses in a row. Starting applying martingale only after a 3 loss and with a balance of $5.000,00 you would have made around $1,750. Time would be around 1,5 day
> 
> Second strategy: following the color of the candle, green candle call, red candle put. 50 seconds duration
> 10.000 trades - win rate close to 50%, got 14 losses in a row. Applying martingale since the first trade. With $20.000,00, it would have made close to $1750. The time to complete the test is around 7 days.
> 
> Third Strategy: Cross between EMa 9 and EMA 26. Crossover Call, crossunder Put. 1min candles and 50 seconds duration
> 10.000 trades - Win rate close to 50%, got 14 losses in a row. Applying martingale since the first trade. With around $20.000, it would have made close to $1750. time to complete is around 30 days.
> 
> Fourth strategy: MACD cross, Stochastic Cross, Trend definition by SMA 20 and SMA 200 on 1min candles, 50 seconds duration. MACD crossover, stochastic crossover, SMA20 > SMA200 - CALL. MACD crossunder, Stochastic Crossunder, SMA20 < SMA200 - PUT
> 5.000 trades - Win rate close to 50%, got 12 losses in a row. Applying martingale since the first trade. With around $5.000, it would have made $875. Time to complete around 60 days
> 
> As you can see, all rise fall strategies have 50% accuracy, will get 10 or more losses in a row, no matter what you use as an indicator or filter for the signals. All those strategies were running 24/7, so there is no strategy that you can just play and make money without the risk of losing all your account.
> 
> I use for more than a year and can be done with XML bots (I have my own Binary/Deriv apps that I run everyday with this strategy and others) is the Hull Moving Average with 50 periods. When the candle crosses over the HMA (wait for the candle to end), I enter in favor of the cross with 54 seconds duration. In case of a loss, martingale until a win, always with 54 seconds duration and entering at 58 seconds of the minute. Using always 1 min candles.
> 
> Target 1-3% a day. In more than 400 days of trading (not trading all days in sequence), I got 9 losses in a row.
> 
> Below the arrows show where you could start the trade. It would require a good amount of capital to start, and using virtual trades or applying martingale after a certain number of losses is not profitable. After these 400 days, with stop loss at 50% of the account, my average profit per day is 0,8%. Any sample data you use with less than 1000 trades is useless. If you tested with less than that, you just wasted your time. That's why a lot of people use strategies on demo accounts and then change to real accounts. They lose all. The test phase is too short and not even recorded for future consults
> 
> ![image](https://user-images.githubusercontent.com/34610787/129949403-21475af5-b070-441c-9530-f0bf7af6c137.png)

thanks

**Comment by sundaybaezofficial** [comment]
> bot can not run 24 hours.

yes you can

24/7 bot but you need vps and for call put/even-odd/over4/under5/  
contracts with 95 % payout 
15 virtual loss 

17 index at the same time with 5 binary accounts a lot of money daily !!

**Comment by BEKKALI16** [comment]
I HAVE BEST STRATEGY WOR MANUAL DIGIT DIFFER BUT VERY SLOW MANUAL
I NEED YOU TO MAKE BOT FOR THIS.
WHO HELP ME TO MAKE BOT WE WILL SHEAR THE PROFIT.
bekkali2013@gmail.com
