### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by bobmeg** [binary-com/binary-bot#3410]
Hello...i have a digits bot ive been testing for almost a month now...recently its been freezing in the middle of the tests...yet on the bot it still shows that the bot is running..every time it does this i have to stop the bot and press play again..its so frustrating especially when there has been a loss...ive tried to clear my browser history but nothing has changed...can anyone help out here

**Comment by contatodeanet** [comment]
É horrível mesmo! tive que migrar minhas operações para o MT5 por contas desses erros!! Provavelmente deve ser configuração no próprio site para a gente não ter um bot com boa analise, tenho um bot de quase 2Mb e se eu tentar colocar no Deriv.com o site trava, já no Binary.com ele demora um pouco para carregar mas funciona!

**Comment by bobmeg** [comment]
What did you say...??

**Comment by binary-ex-machina** [comment]
@bobmeg, stop using the bots 24/7. They were not created to run like that. Make a small profit and stop the bot. Come back the next day.

**Comment by bobmeg** [comment]
Well thats good advice...but how will i ever know the bot is good enough to run on short profits without an endurance test...bcoz it doesnt matter whether i run it 24/7 or for 10 min...

**Comment by binary-ex-machina** [comment]
@bobmeg you can do endurance tests, take profit and rerun it on different market conditions. Example

1. Market is in an uptrend
2. Market is in a downtrend
3. Market is sideways
4. Higher time frame is an uptrend. The lower timeframe is a downtrend

just a few examples

Just play, make the target, play again, repeat will not give you valuable data. When you play in the real account, you will make the target and stop for the day. When you don't do the same on the tests (play, target, stop, next day, repeat), you are just testing against the rules you will use on a real account.

This is what I used to do.

Selected 10 strategies. Played each one on the same market condition (example, uptrend) until making 1% profit. This process takes typically takes 5-10min each. Recorded all the results. The next day I repeated the same strategies, now on a downtrend. Recorded the strategy results. The next day, on sideways. Recorded the results.

Doing this and filtering the strategies that aren't consistent (doing the strategy cycles for 10-15 days).

After the test phase, I started with a small amount on the real account with 1-3 strategies from those 10.

You can only achieve consistency if you do many tests on the strategy like you will use them in actual trades. When you run the bots, 24/7 doesn't show how it will perform in real trades because on a real account. You will not run without a stop.
