### ISSUE TITLE
[NEED HELP] Differs x Match bot

### ISSUE THREAD

**Issue by bitcoin-generator** [binary-com/binary-bot#3476]
I have three bots: match bot differs bot, differs x match bot. (feel free to use any of them)

differs bot: bets on the least frequent digit and multiplies the bet by 10 on
a loss reached 3 losses in a row (-25) before 2000 runs

match bot: bets on the most frequent digit in the last 1000 ticks, with a 
balance of 2000 it can make 200 in less than two hours, but sometimes it 
loses 1600, but it happened only once

differ x match bot: bets on differs and increases the bet by 5% every round
for like 10 rounds and resets to the default value, if it loses on differs
it changes the purchase contract to match until it wins, but only wins if
the last digit repeats

---------

What I need is to change the differs bot to behave kinda like the 
differ x match bot.

I want the differ bot to analyze the last 50 digits and bet on the least
frequent digit, if it wins, increase the bet amount by 10%
if it loses change the purchase contract to match and analyze
the last 1000 ticks and bet on the most frequent digit until it wins and then
go back to differs.

[bots and instructions.zip](https://github.com/binary-com/binary-bot/files/7567595/bots.and.instructions.zip)

**Comment by binary-ex-machina** [comment]
You can do it like this. But, first, you must create two custom functions, one to get the least frequent digit and the other to get the most frequent number. 

About the strategy, if you don't use any money management when the trades are of Match type, you will lose, since it can eat all the profit you made. Maybe increasing the stake by 10% when losing with Digit Match is better than fixed stake

![image](https://user-images.githubusercontent.com/34610787/149584157-66e4e68c-f0a3-4d9d-b1c5-6affef371fb6.png)

**Comment by rainmaker21111** [comment]
the blocks are not  working

**Comment by Ijesuoboikxp** [comment]
![Screenshot_20221229-172047](https://user-images.githubusercontent.com/72432620/209980846-02bec2ed-509e-4cf0-bcfb-e09c10f980fb.jpg)
It keeps showing number so how to reduce the numbers of numbers it will pick?
