### ISSUE TITLE
Create MACD and Stochastic Oscillator BOT in Binary Bot

### ISSUE THREAD

**Issue by Harshit120502** [binary-com/binary-bot#3486]
iam trying to make  a bot using MACD and Stochastict Oscillator for forex currency to call higher when MACD crosses when rising up below the central line and at the same in stochastict oscillator  crosses while also rising from or near the 20% line

this is the YouTube video iam following if you wanna check.

https://www.youtube.com/watch?v=TpfFyECsSag&t=925s

i have tried making some bot i was not able to understand how to get the MACD AND STOCASTIC in the BOT

![Inked2021-12-07](https://user-images.githubusercontent.com/95649800/144916626-fcd7d093-c86d-416e-aff2-a034d5957483.jpg)
a

**Comment by binary-ex-machina** [comment]
Here is an idea for you. I don't know the central line from MACD you are writing about, but I assume it is the MACD line with the signal line cross. The 20% line is from Stochastic. I think it is the band 20 because it is not a percentage. The "near" 20 I don't know how much it is, so I put 25

I used my stochastic indicator
https://github.com/binary-ex-machina/binary.com-bot/wiki/Indicators#stochastic

![image](https://user-images.githubusercontent.com/34610787/149580692-f4b8daff-b3c9-4edf-b009-7f6778953dd8.png)
