### ISSUE TITLE
RSI (higher/lower) with Virtual Loss and costummode martingale

### ISSUE THREAD

**Issue by dritonbytyqi** [binary-com/binary-bot#3508]
Here is the Bot instructions how to make a great bot and functional one with modified/alternatives 👍
RSI Period : 10 
Levels : when RSI touches or pass the 80% will go with function Lower +3.2 or equivalent to 150% to 200% return
Levels : when RSI touches or pass the 20% will go with function Higher +3.2 or equivalent to 150% to 200% return
Costummode Martingale/MoneyManagement for ex not 0.35 X 2.1 with next trade to cover loses but to go with a list :
0.35,0,37,0.42,0.47,0.55,0.70, etc 
Add Virtual Loss with trigger the number of virtual loss in a row 
This is a perfect bot and reliable with good logic 
But who can make it ~?

**Comment by binary-ex-machina** [comment]
There are many problems with your "perfect and reliable with good logic" strategy.

First thing, you didn't send the correct instructions since it lacks the following parameters.
• Source to calculate the RSI (Since you are using a small barrier, I will assume it's ticks)
• Duration of the trades (I will assume you are using the minimum, which is 15 seconds)
• Market (I will guess it's Index 100)
• Your entry rules are not against each other, so it's already a bad strategy. I will assume you want to trade against the RSI level cross, so the bot will use a negative barrier to place Higher trade type
• virtual loss in the XML file can be made only by simulating the trade, not trading on a virtual account, so the accuracy will always be bad

based on all those issues, and using my guess, I built the bot for you, without the virtual loss

Besides all the problems above, there are several issues with this strategy. First, It doesn't use martingale or other money management to recover fully on a win. Second, the strategy needs a lot of wins in sequence when a sequence of losses appears, so it's already bad. Third, RSI is a lagging indicator, so you always enter with a delay in the market movement. Finally, assuming that the price will go against the trend when it reaches level 80 or 20, it's just a 50% chance, so it's the same as you play without any rule. 

Using ticks as the source for indicators will produce so many false signals that it's almost the same as trade without indicators. 

This is a lousy strategy, unreliable, and basic logic to paraphrase your instructions.
But can you replicate the script and run it? can you make the strategy better? I don't think so

![image](https://user-images.githubusercontent.com/34610787/148704252-13592266-166c-43b8-acd2-8f7db5da5978.png)
