### ISSUE TITLE
Suggest me a bot that works on a small capital and is good

### ISSUE THREAD

**Issue by zakziko12** [binary-com/binary-bot#3523]
Suggest me a bot that works on a small capital and is good

**Comment by binary-ex-machina** [comment]
Any bot can work with small capital. The examples in this repository are reasonable and will work with small capital.

https://github.com/binary-com/binary-bot/tree/master/examples

But, if you reformulate the question to this: Suggest me a bot that will work with small capital and is consistent for months, then my answer is that there isn't any strategy, bot, system, an app that can work with small capital. 

Binary options are considered a gamble for a reason—high-risk, high-reward. You will find good strategies using a good amount of capital for the long term. Otherwise, it's just luck
