### ISSUE TITLE
How to stop mutliple bots when the total capital reaches a value?

### ISSUE THREAD

**Issue by zomuzco** [binary-com/binary-bot#353]
Hello, I'm working usually with 5-8 different bots workins simultaneously. I use martingale strategy and I set at the beginning take profit and stop loss. I would like to let the bots work with martingale setting for each bot tp and sl but I would like also that all the bots stop when I reach a precise amount of my total capital. For example: my initial capital is 1200 US. I run 7 bots working with martingale and I set tp and sl. How to say to the bot "if total capital reaches 1300 stop also if you didn't reach martingale tp"? I hope I gave a good explanation. Thanks.

**Comment by Fruitfella** [comment]
![capture](https://user-images.githubusercontent.com/26277327/28746915-11fc92ca-74be-11e7-9e51-8dc90982a0e8.PNG)

**Comment by Fruitfella** [comment]
using 5-8 bots simultaneously? thats a wow 😮

**Comment by sarderiftekhar** [comment]
That is a good idea..think about you are running digit match for all 10 digits at the same time. if the total makes $10 each time..continue it 10 times you make $100...

**Comment by Fruitfella** [comment]
I dont get it @sarderiftekhar 
match for all 10 digits, 9 of it would be lost

**Comment by sarderiftekhar** [comment]
If you keep them running...at one time all of them will start winning. So first one only for 0, second for 1 and so on...at one time the total profit loss will be that target total capital..

**Comment by zomuzco** [comment]
Every bot work on different market. Thank you for the answer, I'll try and check

**Comment by okovalov** [comment]
@sarderiftekhar you are not correct. 
let's say you have $100. so you placed 10 stakes , each one is a digit match from 0..9
so your balance is $90 now.
after the trade only one stake wins , which gives you payout of $9.09 , so you balance after that is $99.09 , total profit is -0.81
they cant start winning same time. you will drain your depo immediately trying to martingale 10 bots same time... and even though you have a really big depo, you still cant win using this approach , because of the math :)

**Comment by Fruitfella** [comment]
Thats what i thought, because only 1 can win and the other 9 will always loss.

**Comment by okovalov** [comment]
@Fruitfella exactly. do you think return % is a random thing? have ever though why it is 809% and non 909% :) same is for digit diff :) you CANT always win. what you COULD do , is to try to keep you win / loss ration a positive value. furthermore - your expected profit has to be your max acceptable loss * 2.5 or even better *3 . otherwise your failure and drained depo is just a matter of time. if you are risking all your depo to gain only 10% of your depo - it is not wise at all. very soon you will fail. so if you do so (risking 100% depo) your goal of finishing you trading session has to be 250% or 300% profit. then you might be expecting for stable profit on a long period of time. all this is my IMHO - if you guys want to continue risking 100% of your depo to gain less than that - it is up to you :)

**Comment by zomuzco** [comment]
Another thing: sometimes happen my balance on the bot is not updated, like in the screen. When happens, is the bot working anyway?or should I do something to fix it?
![screenshot_2017-07-31-10-09-35](https://user-images.githubusercontent.com/29904469/28768778-3d37dc58-75d9-11e7-9107-a18f30227d0b.png)

**Comment by Fruitfella** [comment]
when i tested more than 1 bot simultaneously, sometimes something like that happen. 1 bot profit, the balance increase, 1 bot loss, the balance decrease. and these 2 bots has different balance _Lol_
but no worry, the bot still running.

**Comment by aminmarashi** [comment]
If you stop the bot, balance in the trade info panel won't update.
