### ISSUE TITLE
strategy rise fall 

### ISSUE THREAD

**Issue by zakziko12** [binary-com/binary-bot#3542]
Please, can you make this strategy? You open the deal rise and continue, and if you lose, you open a fall and continue, and if you lose, you open rise ....

**Comment by hotmatrixx** [comment]
I made one for kicks that does that.

Hopeful it's simple enough for you to understand how it works.

I can't be bothered Zip filing it etc because it's tiny and easy to replicate so here is the screenshot.

There are more efficient way s of doing this but this one is easier to follow for a beginner.

Hopefully it will help to introduce you to the world of Deriv.
![image](https://user-images.githubusercontent.com/49715381/154291424-f5d1c9ee-ba03-4f42-acf7-838b8e03e851.png)

**Comment by hotmatrixx** [comment]
Pro tip:

this:
![image](https://user-images.githubusercontent.com/49715381/154291678-15fc8f00-cc73-44f6-bec9-2b95c37bf923.png)

is a shortcut way of doing this:
![image](https://user-images.githubusercontent.com/49715381/154291869-4fc76537-8926-4383-8f88-364a1ed4f0b3.png)

**Comment by zakziko12** [comment]
![Capture](https://user-images.githubusercontent.com/63886169/154367900-cf72f531-fa01-4fc8-9625-ca2d9b46e925.PNG)
thank sir for Time
can you halp me how to add stop loss and Martingale

**Comment by hotmatrixx** [comment]
look, I'm happy to help you on your "Learning to use Deriv|Bot"

But I'm not going to let you be lazy and just have someone else do all the coding for you.

What I gave you was so that you could have a basic understanding of how the bot works and it's work flow. I'm not doing it all for you.

however, in saying that, if you want a martingale: this is a good place to start.
save your bot first.

![image](https://user-images.githubusercontent.com/49715381/154386963-f18c458f-1586-4cf2-9633-0a25a53b5b14.png)

**Comment by zakziko12** [comment]
mister thank you 
This feature worked for me, thank you for your explanation ♥
