### ISSUE TITLE
Sir binary bot ceode not work 

### ISSUE THREAD

**Issue by lucky4911** [binary-com/binary-bot#3575]
@Binary Ex Machina
#3550 #3575 please help me sir
@Mahboobeh-binary  @Binary-Ex-Machina
@jy-binary @torsten-binary @tom-binary

**Comment by lucky4911** [comment]
I want to created this type stragy

**Comment by lucky4911** [comment]
Please help me 
BB PERIOD 20-2-2 
LAST TICK   BRECK BB 
AND 
RSI ≥70 PERIOD 8
AND
MACD ( ≥3
SIGNAL≥1.5
HISTOGRAM ≥2.  Op fall
Same op rise opposite

**Comment by binary-ex-machina** [comment]
There are a lot of missing things and wrong things in your strategy. 

1. Breck? What is this?
2. Assuming that you want to write break, break what? Upper band? Lower band? Assuming that this strategy is a reversal strategy, I used to cross over the upper band for Fall and cross the lower band for Rise
3. You put the same for Rise opposite... confusing
4. Assuming that you wanted to write the same indicators, opposite values for operation Rise, then we have more issues
5. When it's Rise, RSI >= 70? maybe RSI <= 30? this lacks info
6. When it's Rise, what would be the MACD, Signal, and histogram values?
7. What is the time frame?
8. What is the source for each indicator to calculate the signals? Ticks? since you put tick "break" BB, I assumed you wanted ticks.

The image below will help you in your journey to build this strategy, but you need more details to make it work. Asking for help when you need it is very humble, but copying paste from somewhere or asking it poorly is a lazy way. No problem is to use the opposite for Rise, but since your strategy needs specific numbers for each trade type, your hand or fingers will not fall if you type the strategy very detailed, so another person will spend less time guessing what you want than helping you.

![image](https://user-images.githubusercontent.com/34610787/163283168-c35338af-9018-4894-9d3b-599a5673cb9f.png)

**Comment by EbenezerOmotayo** [comment]
*How determined are you? Becoming stable financially* _Enough of clicking multiples of ads everytime only to get disappointed. Diversification is one key to wealth accumulation, it doesn't matter what you do a worker or a student even a parent._ *what if I show you how you can make a minimum of $10 daily all 7 days of the week? taking advantage of the stock exchange market, you need no knowledge it is as easy as clicking play on a video*
Get your binary trading bot at a cheap price 
https://wa.me/2349073936653

**Comment by lucky4911** [comment]
> There are a lot of missing things and wrong things in your strategy.
> 
> 1. Breck? What is this?
> 2. Assuming that you want to write break, break what? Upper band? Lower band? Assuming that this strategy is a reversal strategy, I used to cross over the upper band for Fall and cross the lower band for Rise
> 3. You put the same for Rise opposite... confusing
> 4. Assuming that you wanted to write the same indicators, opposite values for operation Rise, then we have more issues
> 5. When it's Rise, RSI >= 70? maybe RSI <= 30? this lacks info
> 6. When it's Rise, what would be the MACD, Signal, and histogram values?
> 7. What is the time frame?
> 8. What is the source for each indicator to calculate the signals? Ticks? since you put tick "break" BB, I assumed you wanted ticks.
> 
> The image below will help you in your journey to build this strategy, but you need more details to make it work. Asking for help when you need it is very humble, but copying paste from somewhere or asking it poorly is a lazy way. No problem is to use the opposite for Rise, but since your strategy needs specific numbers for each trade type, your hand or fingers will not fall if you type the strategy very detailed, so another person will spend less time guessing what you want than helping you.
> 
> ![image](https://user-images.githubusercontent.com/34610787/163283168-c35338af-9018-4894-9d3b-599a5673cb9f.png)

Thanks. You so much sir i m really so happy 💗 sir thanks sir

**Comment by lucky4911** [comment]
Thanks sir love ❤️ you sir 😊

**Comment by lucky4911** [comment]
This strategy never 2lose in row sir because higer lower 
Multiple BERRIOR  😊😊😊😊😊😊😊
