### ISSUE TITLE
Binary Bot 100% Gewinn Strategie

### ISSUE THREAD

**Issue by Blacky84** [binary-com/binary-bot#362]
Hallo Binary.com Freunde. 
Hat jemand ein fertiges Binary Bot? Als Download der zu 100 % funktioniert und Gewinne macht? 
Bitte um Vorschläge..! 

Gruß Mario

**Comment by okovalov** [comment]
well, @Blacky84 if that was so simple , I bet no one would be sitting here :) because it really depends what you mean by 100% working. if that is 100% winning , then I would say you are a funny guy LOL, if you mean 100% working in terms of properly reflecting your strategy logic being written in the code - then I am sure there are tons of the bots what work that way. the small problem is that no strategy would work 100% of time in profit L)
