### ISSUE TITLE
Sell to Market 

### ISSUE THREAD

**Issue by mnaseem01** [binary-com/binary-bot#373]
Hi,
Any idea how to get profit/Loss in (%) value showing in right side.
![image](https://user-images.githubusercontent.com/13481811/29025289-089d8d5e-7b87-11e7-8957-0732200437c4.png)

**Comment by blinksmith** [comment]
wikiHow to Calculate Percentage Increase
![capture](https://user-images.githubusercontent.com/409976/29036617-5c47d69c-7bca-11e7-8c8c-679848909694.PNG)

**Comment by mnaseem01** [comment]
@blinksmith thanks alot it's working

**Comment by tymu** [comment]
how to set sell profit loss to negative ex: -2 ??

**Comment by elyyyes** [comment]
Hi everybody,

Someone can tell me please if we can buy a second contract with this technique without selling at market ? 
Because on forex we can't sell

So i need to buy a second contract in the same direction if the first contract reach 66.66% loss

Thank you in advance for cooperate
Best regards

**Comment by mandakamitramedia** [comment]
Hi,
Any idea how to sell at market in (%) value showing in picture.

when profit




And  when loss



tq
