### ISSUE TITLE
Want to start 2 bot exactly at the same time

### ISSUE THREAD

**Issue by sarderiftekhar** [binary-com/binary-bot#375]
Hi, I want to start 2 bot at the exact same time. Any way to do that?

![image](https://user-images.githubusercontent.com/20506657/29096034-21c463f2-7c8b-11e7-88be-4c9d4e4d9bd5.png)

**Comment by Fruitfella** [comment]
**EXACT SAME TIME** ? you can start it at the same time. but if what you mean is make 2 purchases at exact same time, afaik you cant.
I tried using time as the condition to purchase so that 2 bots will purchase differently (1 rise, 1 fall) for the same strategy at exact same time, but its always end up differs 1tick, it seem like the server only accept 1 proposal from 1 account at a time so the other one need to queue.
well, dunno if its my bot that in wrong though, but i gave up on that idea.

**Comment by sarderiftekhar** [comment]
I want to start at the same time later on they differ dosnt matter....

**Comment by Fruitfella** [comment]
use **`Seconds since epoch`**
you can make it something like this
![capture](https://user-images.githubusercontent.com/26277327/29097217-de3aaae6-7cc2-11e7-98f9-3d81f78e19bc.png)
thats `60` mean minute, so the bot would start at the next minute (when the second clock is zero), like 01:24:00 or 12:00:00, i cant find the right word to explain it (blame my poor english) hope you get it.
change it to `3600` if you want the bot start at the next hour (when both minute and second clock is zero), like 01:00:00 or 08:00:00.

**Comment by sarderiftekhar** [comment]
Thanks will try and lets see.............

**Comment by okovalov** [comment]
@Fruitfella 


> EXACT SAME TIME ? you can start it at the same time. but if what you mean is make 2 purchases at exact same time, afaik you cant.
I tried using time as the condition to purchase so that 2 bots will purchase differently (1 rise, 1 fall) for the same strategy at exact same time, but its always end up differs 1tick, it seem like the server only accept 1 proposal from 1 account at a time so the other one need to queue.
well, dunno if its my bot that in wrong though, i just gave up on that idea.
>

not only that unfortunately... even if that was allowed by the broker, it would be still happening one after another because of the nature of the process how js calls are handled by the browser. it is a long story to explain, but to make long story short I would say it is not possible to run two js calls at the same time (it would be better to say - two events can not arrive at the same time immediately as well as they can not be triggered). theoretically speaking, you could almost get it started almost at same time by doing smth like this
```
function botA() {
    console.log(lastTick, 'a');
}

function botB() {
    console.log(lastTick, 'b');
}

(function () {
    setInterval(botA, 0);
    setInterval(botB, 0);
})();
```

having this you would very likely to get same last tick for both bots (I have not tested it though) AND having them started the purchase same time BUT that very likely is not allowed by the broker..

**Comment by aminmarashi** [comment]
@okovalov there are other obstacles, such as network delay, processing delay, etc. This requires careful investigation before implementation.

**Comment by sarderiftekhar** [comment]
@Fruitfella

Its not trading at all. I need them to start at the same only at the beginning. After that they can continue on their own.....

**Comment by okovalov** [comment]
@sarderiftekhar believe me , there is no reason to start them at same time :) what you need is:
- to create a variable , call it smth like "isActive" and set it to false right after the bot starts
- in the second block (or in a block what is called every second) you need to check whether isActive is false and whether beginning time condition satisfies certain criteria (the time you want to set isActive to true) - for instance beginning of the minute , as @Fruitfella shown (you could do other condition - it is up to you) and if both 'if' statements are true then set isActive to true
- in a second block have you strategy logic which checks whather isActive is true and only then performs certain calcuations etc..

**Comment by sarderiftekhar** [comment]
Thanks everyone.........

**Comment by JGihon** [comment]
Hey Guys,

I have managed this thing. My bots can enter trade exactly on the same tick and same second!
Just to be clear - by using the same account.
I can share and I also have questions especially to Okovalov...
Hi...

**Comment by folubebe** [comment]
pls share

**Comment by JGihon** [comment]
@folubebe 
Please send me an email and I will help you. (Can send you examples, etc.)
gihonlabs@gmail.com
You can ask questions I will answer according my best.

**Comment by folubebe** [comment]
Do you know how I can subtract the K and D values of Stochastic using the
bots?

**Comment by kkptra** [comment]
Hi, can you please share the bot or code, how you have managed to open 2 positions at exact same time... Mail me at Kkptra@gmail.com thanks

**Comment by bouhali00** [comment]
Hi, I have a aplication to use manualement for strat match bot at same time.
If you want, i can share with you...
![bouton autoclick](https://user-images.githubusercontent.com/44878529/50398244-e8cba280-076d-11e9-96bc-ed99e8a18e01.png)

**Comment by murali139** [comment]
please share to me , muralikumar1245@gmail.com

**Comment by bouhali00** [comment]
Her is the aplication.
[autoclick setup.zip](https://github.com/binary-com/binary-bot/files/2707718/autoclick.setup.zip)

**Comment by murali139** [comment]
thank you bro, happy christmas

**Comment by kudziubet** [comment]
Hi, can you please share the bot or code, how you have managed to open 2 positions at exact same time... Mail me at kudziubet@gmail.com thanks

**Comment by Tebu1429** [comment]
@bouhali00 ,how do you open this Autoclick.?
Thank you!
