### ISSUE TITLE
How to set trade condition to over 5 only 

### ISSUE THREAD

**Issue by oneal-1** [binary-com/binary-bot#3902]
![Screenshot_20230616-205526~2](https://github.com/binary-com/binary-bot/assets/135687206/72fabdce-2209-45d0-9d1f-db445999694b)
Can someone help build such a bot
Thanks in advance
My email is onealdavis5@gmail.com

**Comment by Andres-Guarin** [comment]
This is false, 100% edited the page in order to sell you a bot and scam you. the scammer will look for a way to sell emotions or false illusions. everything you see in that image or in the social networks of those bots with high return and a lot of victory is fake everything

open the bot here👇
https://bot.binarytools.io/platform
![image](https://github.com/binary-com/binary-bot/assets/131272671/0afaf03f-7521-4c9c-a963-529af8bc35f4)

We remind you that Neuronal Trader only has 3 groups:

✅ (SPANISH GROUP)
https://t.me/neuronaltrader_community
✅ (ENGLISH GROUP)
https://t.me/neuronaltrader_community
✅ (PORTUGUESE GROUP)
https://t.me/neuronaltrader_portugues

and there is only one channel for informational purposes:

👉(THE ONLY NEURONAL TRADER CHANNEL)👈
https://t.me/neuronaltrader

🔉🔊❕These are the official Neuronal Trader communities❕📢📣
