### ISSUE TITLE
Method collision : EMA - SMA : lenght sma

### ISSUE THREAD

**Issue by redbulls60** [binary-com/binary-bot#409]
Hi , 

I have a method of collision between SMA and EMA .

i would like to know if it was possible to limited the lenght of SMA.
When i try this code , i ve got a list ( in green ).

![image](https://user-images.githubusercontent.com/32522143/31191825-bced3a1c-a93f-11e7-838d-f92241f75315.png)

Does it was possible to fix the lenght to 3 digit after the coma and have like the EMA ( one value : 142.256 for exemple )?

Thanks a lot 

Ps : sorry for my english

**Comment by Whodiniz** [comment]
I’ll be honest with you I’m a newbie. Have you got any scripts that I could run and make a profit.
  

  
I haven’t got much money. But want to make some profit.
  

  
  

  
  
>

**Comment by Whodiniz** [comment]
Have you got a good bot?
  

  
  

  
  
>

**Comment by redbulls60** [comment]
hi , you can use this of @aminmarashi ON DEMO : 
https://gist.githubusercontent.com/aminmarashi/dfabc8eadfaf77bf270b0318f03ea8bb/raw/sma_compare_threshold.xml

if you want something , create a new issue , don't spam this .

thanks

**Comment by Whodiniz** [comment]
Thanks,
  

  
Can’t seem to open this link.
  

  
Can you check the link please.
  

  
  

  
  
>

**Comment by Fruitfella** [comment]
@redbulls60 you use the wrong indicator. you should use normal **SMA** instead of **SMA Array**
![capture](https://user-images.githubusercontent.com/26277327/31213352-5e41f3c2-a9d0-11e7-86b3-a07bd3c69be3.png)

if you dislike the normal one and you insist want to use **SMA Array** because you love it so much, you can make it like this. :rofl: 
![untitled](https://user-images.githubusercontent.com/26277327/31213369-7f120d30-a9d0-11e7-9639-fe052d92dde1.png)

**Comment by redbulls60** [comment]
thanks a lot Fruitfella , i see my error today.
We've got to SMA indicator : Simple and TAble
