### ISSUE TITLE
WARNING MESSAGE ON VIRTUAL ACCOUNT!

### ISSUE THREAD

**Issue by Jo-Hans** [binary-com/binary-bot#752]
i got this WARNING when i want to test my bot today. 
after https://bot.binary.com/bot.html opened (its on real account by default). i switched it to virtual account for bot testing, and i got this WARNING. 
it never happen before, so i have no idea what is it about, anyone?
![binerror](https://user-images.githubusercontent.com/32584948/41774681-f9a8be76-764a-11e8-8f28-89bfc7d518f4.PNG)

**Comment by Jo-Hans** [comment]
@gokula-krishna-dev what is the consequence if i click `**Yes**`? 
"Future trades will be stopped" does this means i can't trade again? with which account?

**Comment by zdradozhi** [comment]
Hi, I've got this message yesterday clicked YES and nothing dangerous happened. Looks like it is applying to current run or somewhat....2 successfull bot runs from this message

**Comment by gokula-krishna-dev** [comment]
@Jo-Hans in previous version of bot, when you switch the account while the bot is running the trade is placed on behalf on the account with which you started the bot. With the current version when you change the account all the trades will be stopped before switching to another account. 

Nothing dangerous happens when click "Yes" or "No".

**Comment by Jo-Hans** [comment]
okay, thanks for the response @gokula-krishna-dev 

and thank you to you @zdradozhi too
