### ISSUE TITLE
Open every xx:45 Based on Data Candle From xx:00, xx:15, xx:30 (TF15M)

### ISSUE THREAD

**Issue by daviduck123** [binary-com/binary-bot#843]
Hello,
I want to make a BOT that always running with TF15.
The Logic is simple : 
- Collect Information of Candle Bullish or Bearish (3 variable)
- OP at xx:45 (Candle 4)
How to make a setting like this?
I can't make a Attribute to Start every xx:00 (Reset value every xx:00)

**Comment by binary-ex-machina** [comment]
You can use the seconds since epoch to get the actual minutes on an hour interval. In the image below, you can see the bot will trade fall, if the last 3 candles are red, entering precisely at 45:00, trading 15min.

![image](https://user-images.githubusercontent.com/34610787/45642737-8177c580-ba8f-11e8-98d0-9fa3739a7c1d.png)

**Comment by daviduck123** [comment]
Thank you for your help.
Going to create the BOT, right now
